// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_021D()
{
    level _id_0A71::_id_C279( ::_id_ABC4 );
}

_id_F286( var_0 )
{
    if ( !self._id_7598 )
        return 0;

    var_1 = gettime() + var_0 * 1000;
    var_2 = level._id_90AE[self._id_0309["team"]];
    var_3 = level._id_10CB3[self._id_0309["team"]] * 1000;
    var_4 = ( var_1 - var_2 ) / var_3;
    var_5 = _func_0037( var_4 );
    var_6 = var_2 + var_5 * var_3;

    if ( isdefined( self._id_C6B8 ) )
    {
        var_7 = ( gettime() - self._id_C6B8 ) / 1000.0;

        if ( self._id_C6B8 < var_2 )
            return 0;
    }

    if ( isdefined( self._id_10CB7 ) )
        var_6 = var_6 + 50 * self._id_10CB7;

    return ( var_6 - gettime() ) / 1000;
}

_id_EF7C()
{
    var_0 = self._id_0309["teamkills"];

    if ( !isdefined( var_0 ) || level._id_9C39 < 0 || var_0 <= level._id_9C39 )
        return 0;

    var_1 = var_0 - level._id_9C39;
    return _id_07FB::_id_6DF7( "team", "teamkillspawndelay" ) * var_1;
}

_id_F284( var_0 )
{
    if ( level._id_7E95 && !self._id_7598 || level._id_609B )
        return 0;

    var_1 = 0;

    if ( self._id_7598 )
    {
        var_2 = self [[ level._id_AB79 ]]();

        if ( isdefined( var_2 ) )
            var_1 = var_2;
        else
            var_1 = getdvarfloat( "scr_" + _id_0A69::_id_6A43() + "_playerrespawndelay" );

        if ( var_0 && isdefined( self._id_0309["teamKillPunish"] ) && self._id_0309["teamKillPunish"] )
            var_1 = var_1 + _id_EF7C();

        if ( isdefined( self._id_EAF2 ) )
            var_1 = var_1 + getdvarfloat( "scr_" + _id_0A69::_id_6A43() + "_suicidespawndelay" );

        if ( isdefined( self._id_C6B8 ) && !isdefined( level._id_E292 ) )
        {
            var_3 = ( gettime() - self._id_C6B8 ) / 1000.0;
            var_1 = var_1 - var_3;

            if ( var_1 < 0 )
                var_1 = 0;
        }

        if ( isdefined( self._id_D6CF ) )
            var_1 = var_1 + level._id_F292;
    }

    var_4 = getdvarint( "scr_" + _id_0A69::_id_6A43() + "_waverespawndelay" ) > 0;

    if ( var_4 )
        var_1 = _id_F286( var_1 );

    if ( level._id_7E95 && !self._id_7598 || level._id_609B )
        var_1 = 0;
    else if ( getdvarint( "scr_cmd_camera_debug", 0 ) == 1 )
        var_1 = 999.0;

    var_1 = getdvarint( "scr_debug_respawn_delay", var_1 );
    return var_1;
}

_id_87E4( var_0 )
{
    return 0;
}

_id_9CB6()
{
    if ( istrue( level._id_A722 ) )
        return 0;

    if ( istrue( level._id_1A5B ) )
        return 0;

    if ( isdefined( self._id_9CB6 ) && !self._id_9CB6 )
        return 0;

    if ( _id_0A69::_id_6A46() || isdefined( level._id_4AC7 ) )
    {
        if ( isdefined( level._id_EFB0 ) && level._id_EFB0.size == 1 )
            return 1;

        if ( _id_0A69::_id_6A43() == "control" && _id_0A7C::_id_6DAC( self._id_0309["team"], "livesCount" ) == 0 )
            return 0;

        if ( istrue( level._id_4AC7 ) )
        {
            if ( !_id_87E4( self ) )
                return 0;
        }

        if ( istrue( self._id_0309["teamKillPunish"] ) )
            return 0;

        if ( self._id_0309["lives"] <= 0 && _id_0A69::_id_60A6() )
            return 0;
        else if ( _id_0A69::_id_60A6() )
        {
            if ( level._id_7E95 && !self._id_7598 )
                return 1;

            if ( !level._id_7E95 && !self._id_7598 && ( isdefined( level._id_1596 ) && !level._id_1596 ) )
            {
                if ( isdefined( self._id_DD2A ) && !self._id_DD2A )
                    return 1;

                if ( _id_87E4( self ) )
                    return 1;

                return 0;
            }
        }
    }

    return 1;
}

_id_E282( var_0 )
{
    self endon( "becameSpectator" );

    if ( isdefined( level._id_9FDC ) )
    {
        self [[ level._id_9FDC ]]( var_0 );
        return;
    }

    if ( isdefined( self._id_0309["next_round_class"] ) && !self._id_7598 )
        self._id_37D9 = self._id_0309["next_round_class"];

    if ( isdefined( self._id_10846 ) && self._id_10846 )
        self waittill( "okToSpawn" );

    if ( isdefined( self._id_114D ) )
    {
        _id_07C9::_id_114D( self._id_114D );
        self._id_114D = undefined;
    }

    if ( !_id_9CB6() )
    {
        waitframe();
        var_1 = self._id_02EA;
        var_2 = self._id_0054;
        self notify( "attempted_spawn" );

        if ( istrue( self._id_0309["teamKillPunish"] ) )
        {
            self._id_0309["teamkills"] = _func_0147( self._id_0309["teamkills"] - 1, 0 );
            _id_0A70::_id_D5DD( 24 );

            if ( !self._id_7598 && self._id_0309["teamkills"] <= level._id_9C39 )
                self._id_0309["teamKillPunish"] = 0;
        }
        else if ( _id_0A69::_id_89F1() && game["finalRound"] == 0 || _id_0A69::_id_6A46() != 0 && game["finalRound"] == 0 || istrue( level._id_4AC7 ) )
        {
            if ( isdefined( self._id_ED47 ) && self._id_ED47 )
                _id_0A70::_id_D5DD( 8 );
            else if ( istrue( self._id_C7E2 ) && level._id_EF67[self._id_045B]["aliveCount"] > 0 )
                _id_0A70::_id_D5DD( 64 );
            else if ( istrue( self._id_C7E1 ) )
            {
                if ( isdefined( self._id_F280 ) )
                {
                    if ( isdefined( self._id_BFAF ) )
                        _id_0A70::_id_D5DD( 25, int( gettime() + self._id_F280 * 1000 ) );
                    else if ( !istrue( self._id_5124 ) )
                        _id_0A70::_id_D5DD( 6, int( gettime() + self._id_F280 * 1000 ) );
                }
                else if ( level._id_EF67[self._id_045B]["aliveCount"] > 0 )
                    _id_0A70::_id_D5DD( 64 );
                else
                    _id_0A70::_id_D5DD( 2 );
            }
            else if ( _id_0A69::_id_6A43() == "siege" )
                _id_0A70::_id_D5DD( 4 );
            else if ( istrue( level._id_570B ) )
                _id_0A70::_id_D5DD( 26 );
            else
                _id_0A70::_id_D5DD( 2 );

            if ( !isdefined( self._id_C7E1 ) )
                thread _id_C514( 3.0 );
        }

        if ( self._id_0392 != "spectator" )
            var_1 = var_1 + ( 0, 0, 60 );

        if ( _id_0A74::_id_8AB5() )
        {
            self._id_E304 = 1;
            self._id_43D7 = self._id_02EA;
            self waittill( "stopped_using_remote" );
        }

        if ( !istrue( level._id_A722 ) )
            thread _id_E37A( var_1, var_2 );

        return;
    }

    if ( self._id_10847 )
        return;

    self._id_10847 = 1;
    _id_107DA( var_0 );

    if ( isdefined( self ) )
        self._id_10847 = 0;
}

_id_1094A( var_0 )
{
    self endon( "started_spawnPlayer" );

    for (;;)
    {
        waitframe();

        if ( self._id_045B == "spectator" || self._id_045B == "follower" )
            return;

        if ( isdefined( self ) && ( self._id_0392 == "spectator" || !_id_0A74::_id_89D3( self ) ) )
        {
            if ( istrue( var_0 ) )
                self._id_0309["teamKillPunish"] = 0;

            self._id_0309["lives"] = 1;
            thread _id_E282( var_0 );
            continue;
        }

        return;
    }
}

_id_107DA( var_0 )
{
    self endon( "disconnect" );
    self endon( "end_respawn" );
    level endon( "game_ended" );
    self notify( "attempted_spawn" );

    if ( isdefined( level._id_BC62 ) )
        [[ level._id_BC62 ]]( var_0 );

    if ( _id_0A74::_id_8AB5() )
    {
        self._id_E304 = 1;
        self._id_43D7 = self._id_02EA;
        self waittill( "stopped_using_remote" );

        if ( istrue( level._id_A722 ) )
            return;
    }

    self.wasusingfixeddeathcamera = self _meth_85B6();
    var_1 = 0;

    if ( istrue( self._id_0309["teamKillPunish"] ) )
    {
        var_2 = _id_EF7C();

        if ( var_2 > 0 )
        {
            _id_0A70::_id_D5DD( 65, int( gettime() + var_2 * 1000 ) );
            thread _id_C666( self._id_02EA + ( 0, 0, 60 ), self._id_0054 );
            var_1 = 1;
            wait( var_2 );
            _id_0A70::_id_D5DD( 0 );
            self._id_C6B8 = gettime();
        }

        self._id_0309["teamKillPunish"] = 0;
    }
    else if ( _id_EF7C() )
        self._id_0309["teamkills"] = _func_0147( self._id_0309["teamkills"] - 1, 0 );

    if ( !isdefined( self._id_10CB7 ) && isdefined( level._id_10CB4[self._id_045B] ) )
    {
        self._id_10CB7 = level._id_10CB4[self._id_045B];
        level._id_10CB4[self._id_045B]++;
    }

    if ( isdefined( self._id_D6CF ) && !_id_F296() )
        _id_09EF::_id_E340( 1 );

    var_3 = _id_F284( 0 );
    var_4 = 0.0;

    if ( !istrue( level._id_4AC6 ) )
        var_4 = _id_077B::_id_F07F( istrue( level._id_DEC3 ), 1.25, 2.0 );

    if ( istrue( level._id_FECC ) )
        var_4 = 0.5;

    if ( level._id_7E95 && !self._id_7598 || level._id_609B )
    {
        var_4 = 0;
        var_3 = 0;
    }

    var_5 = 0;

    if ( _id_0A69::_id_6A43() == "hq" && isdefined( level._id_110CD ) && level._id_110CD._id_AD9B == self._id_045B )
        var_5 = 1;

    if ( !istrue( self._id_DDBE ) && isdefined( self._id_8D54 ) && !var_5 )
    {
        var_3 = _func_0147( var_3 - self._id_8D54, 0 );
        self._id_8D54 = undefined;
    }

    if ( isdefined( self._id_D6CF ) )
    {
        var_4 = 0;
        var_3 = 0;
    }

    var_3 = _func_0147( var_3, var_4 );

    if ( _id_0784::_id_889C() )
    {
        var_6 = self _meth_8540();
        var_7 = anglestoup( var_6 );
        var_8 = var_7 * 60;
    }
    else
        var_8 = ( 0, 0, 60 );

    var_9 = istrue( _id_07A8::_id_609F( "prematch_done" ) );
    var_10 = _id_07A8::_id_609F( "infil_will_run" ) && !istrue( _id_07A8::_id_609F( "infil_started" ) );

    if ( _id_0A69::_id_6A43() == "arm" && !var_10 && !var_9 )
    {
        var_11 = scripts\mp\gametypes\arm::_id_6B41( self._id_045B );
        var_12 = _func_0205( "script_model", var_11._id_E703 );
        var_12 setmode( "tag_origin" );
        var_12._id_0054 = var_11._id_E677;
        self _meth_805E( var_12, "tag_origin" );
        var_12 _meth_823B( var_11._id_531C, 18 );
        var_12 rotateroll( var_11._id_52BF, 18 );
        _id_07A8::_id_60A3( "prematch_done" );
        var_9 = 1;
        self cameralinkto();
    }
    else if ( istrue( level._id_886B ) && !self._id_7598 )
    {
        var_9 = 1;
        var_3 = _id_077B::_id_F07F( istrue( level._id_DEC3 ), 1.25, 2.0 );
    }

    if ( !istrue( level._id_4AC6 ) && var_9 && !istrue( self._id_DDC4 ) && !istrue( level._id_FECC ) && var_3 > 0 )
        thread _id_07EC::_id_E71F();

    if ( istrue( level._id_FECC ) && !isdefined( self._id_D6CF ) )
        _id_07F0::_id_10828( var_3, !istrue( var_9 ) );
    else if ( var_3 > 0 )
    {
        var_13 = 9;

        if ( _id_0A69::_id_6A43() == "hq" )
        {
            if ( isdefined( level._id_110CD ) )
            {
                if ( level._id_110CD._id_AD9B == self._id_045B )
                {
                    _id_0A64::_id_9120( "hp_dead" );
                    var_13 = 30;

                    if ( isdefined( self._id_EAF2 ) )
                    {
                        var_3 = var_3 - getdvarfloat( "scr_hq_suicidespawndelay" );
                        var_3 = _func_0147( 0, var_3 );
                    }
                }
                else if ( isdefined( self._id_EAF2 ) && getdvarfloat( "scr_hq_suicidespawndelay" ) > 0 && level._id_110CD._id_AD9B == "neutral" )
                {
                    var_13 = 31;
                    self._id_EAF2 = undefined;
                }
            }
        }
        else if ( isdefined( self._id_EAF2 ) && getdvarfloat( "scr_" + _id_0A69::_id_6A43() + "_suicidespawndelay" ) > 0 )
        {
            var_13 = 31;
            self._id_EAF2 = undefined;
        }

        _id_0A70::_id_D5DD( var_13, int( gettime() + var_3 * 1000 ) );

        if ( !var_1 )
            thread _id_C666( self._id_02EA + var_8, self._id_0054 );

        var_1 = 1;
        _id_077B::_id_108AC( var_3, "force_spawn" );

        if ( !istrue( self._id_10846 ) )
            self notify( "stop_wait_safe_spawn_button" );
    }

    if ( _id_A3F5() )
    {
        if ( !istrue( self._id_10846 ) )
            _id_0A70::_id_D5DD( 1 );

        if ( !var_1 )
            thread _id_C666( self._id_02EA + var_8, self._id_0054 );

        var_1 = 1;
        _id_10859();
    }

    if ( !istrue( level._id_4AC6 ) || _id_0A69::_id_6A43() == "arm" )
        thread _id_07EC::_id_532A();

    _id_107E4();

    if ( _func_0107( self ) )
    {
        if ( !scripts\mp\bots\bots::_id_27E8() )
            self waittill( "bot_ready_to_spawn" );
    }

    self._id_10847 = 0;
    _id_0A70::_id_D5DD( 0 );
    self._id_10CB7 = undefined;
    thread _id_E334( undefined, var_0 );
}

_id_DC0B()
{
    return 0;
}

_id_BEBD()
{
    while ( !level._id_E48B[self._id_045B][self._id_E493]._id_885A && !level._id_E48B[self._id_045B][self._id_E493]._id_8A48 )
        waitframe();
}

_id_107E4()
{
    while ( istrue( self._id_10846 ) )
        waitframe();
}

_id_A3F5()
{
    if ( _id_07FB::_id_6DF7( "player", "forcerespawn" ) != 0 )
        return 0;

    if ( !self._id_7598 )
        return 0;

    var_0 = getdvarint( "scr_" + _id_0A69::_id_6A43() + "_waverespawndelay" ) > 0;

    if ( var_0 )
        return 0;

    if ( self._id_109C4 )
        return 0;

    return 1;
}

_id_10859()
{
    self endon( "disconnect" );
    self endon( "end_respawn" );

    for (;;)
    {
        if ( self useanimtree() )
            break;

        wait 0.05;
    }
}

_id_C514( var_0 )
{
    self endon( "disconnect" );
    level endon( "game_ended" );
    waittillframeend;
    self endon( "end_respawn" );
    wait( var_0 );
    _id_0A70::_id_D5DD( 0 );
}

_id_F296()
{
    if ( !isdefined( self._id_D6CF ) )
        return 0;

    if ( isdefined( level._id_31BA ) && ![[ level._id_31BA ]]( self ) )
        return 0;

    var_0 = getentarray( "care_package", "targetname" );

    foreach ( var_2 in var_0 )
    {
        if ( distancesquared( var_2._id_02EA, self._id_D6CF._id_B7BE ) > 4096 )
            continue;

        if ( isdefined( var_2._id_02F2 ) )
            _id_07B9::_id_DCE0( "destroyed_insertion", undefined, var_2._id_02F2 );

        _id_09EF::_id_E340();
        return 0;
    }

    var_4 = ( 30, 30, 80 );
    var_5 = self._id_D6CF._id_B7BE - var_4;
    var_6 = self._id_D6CF._id_B7BE + var_4;
    var_7 = _func_02C4( [ "physicscontents_vehicle" ] );
    var_8 = [];
    var_9 = isbotmatchmakingenabled( var_5, var_6, var_7, var_8 );

    if ( isdefined( var_9 ) && var_9.size > 0 )
    {
        var_10 = 1;

        foreach ( var_12 in var_9 )
        {
            var_13 = var_12._id_00E1 == "scriptable" || var_12._id_00E1 == "worldspawn";

            if ( !var_13 )
            {
                var_10 = 0;
                break;
            }
        }

        if ( !var_10 )
            return 0;
    }

    var_15 = self._id_D6CF._id_B7BE + ( 0, 0, 60 );
    var_16 = self._id_D6CF._id_B7BE + ( 0, 0, 1 );
    var_17 = [];
    var_17[0] = self;
    var_17[1] = self._id_D6CF;
    var_18 = _func_02C4( [ "physicscontents_characterproxy", "physicscontents_playerclip", "physicscontents_glass" ] );

    if ( !_id_077A::_id_C047( var_15, var_16, var_17, var_18 ) )
        return 0;

    var_19 = self._id_D6CF._id_B7BE + ( 0, 0, 1 );
    var_20 = physicsexplosionsphere( var_19, self._id_D6CF._id_B7BE + ( 0, 0, -16 ) );

    if ( var_19[2] == var_20[2] )
        return 0;

    return 1;
}

_id_C7DE()
{
    if ( !isdefined( self._id_5EA7 ) )
        return 0;

    var_0 = _func_020F();
    var_0._id_E350 = self._id_5EA7;
    var_0._id_8AD2 = 1;
    var_1 = [];
    var_1[0] = self;
    var_2 = _id_077A::_id_3EC3( 1, 1, 1, 0, 0, 1, 1 );

    if ( !_id_077A::_id_C047( self._id_5EA7 + ( 0, 0, 60 ), self._id_5EA7, var_1, var_2 ) )
    {
        var_0._id_8AD2 = 0;
        return var_0;
    }

    var_3 = anglestoforward( self._id_0054 );
    var_4 = _func_025A( var_3 ) * 5;

    if ( !_id_077A::_id_C047( self._id_5EA7 + var_4, self._id_5EA7 + var_4 - ( 0, 0, 16 ), var_1, var_2 ) )
    {
        var_0._id_8AD2 = 0;
        return var_0;
    }

    var_5 = self._id_5EA7 + ( 0, 0, 1 );
    var_6 = physicsexplosionsphere( var_5, self._id_5EA7 + ( 0, 0, -16 ) );

    if ( var_5[2] == var_6[2] )
    {
        var_0._id_8AD2 = 0;
        return var_0;
    }
    else
    {
        var_0._id_E350 = var_6;
        var_0._id_8AD2 = 0;
    }

    self._id_59BF = "crouch";
    var_0._id_8AD2 = 1;
    return var_0;
}

_id_E305()
{
    self notify( "spawningClientThisFrameReset" );
    self endon( "spawningClientThisFrameReset" );
    waitframe();
    level._id_A783--;
}

_id_6C23( var_0 )
{
    var_1 = _func_020F();

    if ( var_0._id_9671 != "none" )
        var_1._id_0326 = var_0._id_9671;

    if ( var_0._id_9680 != "none" )
        var_1._id_038F = var_0._id_9680;

    var_2 = _id_07F7::_id_699A();

    if ( isdefined( var_2["body"] ) )
        var_1._id_25A4 = var_2["body"];

    if ( isdefined( var_2["head"] ) )
        var_1._id_75BF = var_2["head"];

    return var_1;
}

_id_968F( var_0, var_1, var_2 )
{
    var_3 = [];

    foreach ( var_5 in var_0 )
    {
        if ( isdefined( var_5._id_0326 ) )
            var_3[var_3.size] = var_5._id_0326;

        if ( isdefined( var_5._id_038F ) )
            var_3[var_3.size] = var_5._id_038F;

        if ( !istrue( var_2 ) )
            self _meth_8526( var_5._id_25A4, var_5._id_75BF, var_1 );
    }

    if ( var_3.size > 0 )
        self _meth_8518( var_3, var_1 );
}

_id_15C1( var_0 )
{
    var_1 = [];

    if ( isdefined( var_0._id_0326 ) )
        var_1[var_1.size] = var_0._id_0326;

    if ( isdefined( var_0._id_038F ) )
        var_1[var_1.size] = var_0._id_038F;

    if ( !self loadweaponsforplayer( var_1 ) )
        return 0;

    if ( !self _meth_8539( var_0._id_25A4 ) )
        return 0;

    return 1;
}

_id_6D2C()
{
    var_0 = undefined;
    var_1 = undefined;
    var_2 = undefined;
    self._id_F1D6 = 0;

    if ( getdvarint( "scr_useProfileSpawn", 0 ) != 0 )
    {
        if ( level._id_60D1 == "br" )
            var_3 = _func_00CB( "mp_dm_spawn_start" );
        else
            var_3 = _func_00CB( "mp_tdm_spawn_allies_start" );

        var_0 = var_3[0];
        var_1 = var_0._id_02EA;
        var_2 = var_0._id_0054;
    }
    else if ( isdefined( self._id_5EA7 ) )
    {
        var_4 = _id_C7DE();

        if ( !var_4._id_8AD2 && isdefined( self._id_BC4F ) && !isdefined( self._id_BFAF ) )
            var_1 = self._id_BC4F;
        else
        {
            var_1 = self._id_5EA7;
            self._id_5EA7 = undefined;
        }

        if ( isdefined( self._id_5EA2 ) )
        {
            var_2 = self._id_5EA2;
            self._id_5EA2 = undefined;
        }
        else
            var_2 = ( 0, _func_01B7( 0, 360 ), 0 );

        if ( isdefined( self._id_C7DC ) )
        {
            if ( _func_01A0( var_1 ) || !var_4._id_8AD2 )
            {
                var_0 = _id_07EF::_id_5AE7( self._id_C7DC );
                self._id_C7DC = undefined;

                if ( isdefined( var_0 ) )
                {
                    var_1 = var_0._id_02EA;
                    var_2 = var_0._id_0054;
                }
            }
            else
                var_1 = var_4._id_E350;
        }
    }
    else if ( isdefined( self._id_D6CF ) )
    {
        var_0 = self._id_D6CF;

        if ( !istrue( self._id_D6CF._id_A6AD ) )
        {
            if ( istrue( level._id_886B ) && istrue( self._id_D6CF._id_8A5A ) && level._id_9AA7 != "mp_aniyah" )
            {
                var_5 = _func_0148( level._id_7E07 - self._id_D6CF._id_B7BE[2], level._id_7E07 );
                self._id_D6CF._id_B7BE = self._id_D6CF._id_B7BE + ( 0, 0, var_5 );
            }

            self._id_F1D6 = 1;
            thread _id_0A64::_id_9120( "ti_spawn" );
        }

        foreach ( var_7 in level._id_F903 )
        {
            if ( distancesquared( var_7._id_02EA, var_0._id_B7BE ) < 1024 )
                var_7 notify( "damage", 5000, var_7._id_02F2, ( 0, 0, 0 ), ( 0, 0, 0 ), "MOD_EXPLOSIVE", "", "", "", undefined, _func_034C( "killstreak_jammer_mp" ) );
        }

        var_1 = self._id_D6CF._id_B7BE;
        var_2 = self._id_D6CF._id_B7B8;
        _id_09EF::_id_E340( 0, 1 );
        var_0 = undefined;
    }
    else if ( istrue( level._id_FECC ) && istrue( _id_07A8::_id_609F( "prematch_done" ) ) )
    {
        var_0 = _id_07F0::_id_6D2C();
        var_1 = var_0._id_02EA;
        var_2 = var_0._id_0054;
    }
    else
    {
        var_0 = self [[ level._id_6D2C ]]();
        var_1 = var_0._id_02EA;
        var_2 = var_0._id_0054;
    }

    var_9 = _func_020F();
    var_9._id_E33F = var_0;
    var_9._id_E32F = var_1;
    var_9._id_E264 = ( 0, var_2[1], 0 );
    return var_9;
}

_id_E334( var_0, var_1 )
{
    self endon( "disconnect" );
    self endon( "joined_spectators" );
    self notify( "spawned" );
    self notify( "end_respawn" );
    self notify( "started_spawnPlayer" );

    if ( !isdefined( var_0 ) )
        var_0 = 0;

    if ( !isdefined( var_1 ) )
        var_1 = 0;

    if ( _id_0A69::_id_EF73( self._id_045B ) && !_id_07A8::_id_609F( "infil_started" ) && !isdefined( level._id_2DCE ) )
        self _meth_82F6( "ui_options_menu", 2 );
    else if ( !isdefined( game["state"] ) || game["state"] != "playing" )
        self _meth_82F6( "ui_options_menu", 0 );

    _id_0A69::_id_352C();
    self _meth_82F6( "ui_hud_shake", 0 );
    self._id_8FE8 = undefined;
    self._id_CC15 = undefined;
    self._id_3E72 = undefined;

    if ( getdvarint( "scr_game_forceuav" ) > 1 )
        level thread _id_0994::_id_D55D( self );

    level._id_A783++;

    if ( level._id_A783 > 1 )
    {
        self._id_10848 = 1;
        wait( level._id_5F1B * ( level._id_A783 - 1 ) );
    }

    thread _id_E305();
    self._id_10848 = 0;

    if ( !isdefined( self._id_0309["copiedClass"] ) )
        var_2 = scripts\cp_mp\hostmigration::_id_BB8A( self._id_37D9, 1 );
    else
    {
        var_3 = scripts\cp_mp\hostmigration::_id_9617( self._id_37D9 );
        scripts\cp_mp\hostmigration::_id_9610( self._id_0309["copiedClass"], var_3 );
        scripts\cp_mp\hostmigration::_id_BB8B( self._id_0309["copiedClass"], 1 );
        var_2 = self._id_0309["copiedClass"];
        self._id_0309["copiedClass"] = undefined;
    }

    var_4 = gettime();
    self._id_E290 = _id_6D2C();
    _id_D6D2();
    var_5 = self._id_7598;
    self._id_EAF2 = undefined;
    self._id_59C0 = undefined;
    self disableoffhandthrowback( 0 );
    self _meth_884D( 2, self._id_045B );

    if ( !var_0 )
    {
        self._id_8D8C = [];

        if ( !istrue( self._id_82D6 ) )
            _id_0A74::_id_FD24( "playing" );

        _id_0A74::_id_392A();
        self._id_3137 = undefined;
        self._id_027F = _id_07FB::_id_6DF7( "player", "maxhealth" );

        if ( istrue( var_1 ) )
        {
            var_6 = _id_0A66::getvehicle( "lastStandReviveHealth" );

            if ( !isdefined( var_6 ) )
                self._id_01FF = getdvarint( "scr_player_lastStandReviveHealth", 50 );
            else
                self._id_01FF = var_6;

            thread _id_A6A0();
        }
        else
            self._id_01FF = self._id_027F;

        if ( istrue( self._id_5F94 ) )
        {
            self._id_5F94 = undefined;
            thread scripts\mp\gametypes\common::_id_59E7();
        }

        self._id_5F85 = undefined;
        self._id_E390 = gettime();
        self._id_10A20 = self._id_F1D6;
        self._id_42D5 = [];
        self._id_A8D9 = 1;
        self._id_D9CC = 0;
        self._id_C0ED = 0;
        self._id_C6B8 = undefined;
        self._id_8FC4 = undefined;
        self._id_9032 = undefined;
        self._id_8FE0 = undefined;
        self._id_8F87 = undefined;
        self._id_8F9F = undefined;
        self._id_9090 = undefined;

        if ( isdefined( self._id_EA8A ) && self._id_EA8A._id_EA8C == self )
            self._id_EA8A._id_EA8C = undefined;

        self._id_EA8A = undefined;
        self._id_EA8B = undefined;
        self._id_9355 = 0;

        if ( isdefined( self._id_0309["deaths"] ) )
            self._id_9355 = self._id_0309["deaths"];

        _id_0996::_id_3911();
        _id_07BE::_id_3929();
    }

    self._id_A24C = 1;

    if ( !var_0 )
    {
        self._id_1F87 = 5.0;
        var_7 = self._id_0309["lives"];

        if ( var_7 == _id_0A69::_id_6A46() && _id_0A69::_id_6A43() != "control" )
            _id_113A();

        if ( var_7 )
            self._id_0309["lives"]--;

        if ( !istrue( self._id_7245 ) && !istrue( self._id_C699 ) )
            _id_112E();

        if ( !var_5 || _id_0A69::_id_60A6() || _id_0A69::_id_60A6() && level._id_7E95 && self._id_7539 )
            _id_C4A1();

        if ( !self._id_10A08 )
        {
            var_8 = 20;

            if ( _id_0A69::_id_6DC7() > 0 && var_8 < _id_0A69::_id_6DC7() / 4 )
                var_8 = _id_0A69::_id_6DC7() / 4;

            if ( level._id_7E95 || _id_0A69::_id_6DC8() < var_8 * 1000 )
                self._id_10A08 = 1;
        }
    }

    thread _id_0793::_id_AB8D();
    var_9 = getdvar( "scr_overrideFOV", "65" );

    if ( self _meth_8682() )
        self _meth_82F4( "#x3c3ebf4db8eac6762", var_9 );

    if ( isdefined( self._id_E290._id_E33F ) )
    {
        if ( !istrue( self._id_DB60 ) )
            _id_07EE::_id_5A80( self._id_E290._id_E33F );

        self._id_9038 = gettime();
    }
    else if ( !isdefined( self._id_59BE ) )
        self._id_9038 = gettime();

    self._id_E34F = self._id_E290._id_E32F;

    if ( var_0 && _id_07AD::_id_F38B() )
    {
        if ( self _meth_81D7() )
        {
            self _meth_8541();
            self._id_E290._id_E32F = self._id_E290._id_E32F - ( 0, 0, 80 );
        }

        var_10 = self _meth_8540();
    }

    _id_07F1::_id_D6D7();
    self solid( self._id_E290._id_E32F, self._id_E290._id_E264 );
    self _meth_8362( ( 0, self._id_E290._id_E264[1], 0 ) );
    _id_0A74::_id_BD13( "playerlogic::spawnPlayer() !!!CODE SPAWN!!! @" + self._id_E290._id_E32F );

    if ( !isdefined( level._id_9036 ) )
        level._id_9036 = [];

    level._id_9036[self._id_045B] = self._id_E290._id_E32F;
    self _meth_85B5( 0 );
    self._id_0143 = 1023;

    if ( ( var_0 || var_1 ) && isdefined( self._id_59BF ) )
    {
        self _meth_8382( self._id_59BF );
        self._id_59BF = undefined;
    }

    if ( _func_0104( self ) )
        _id_0A74::_id_0BC4( 1 );

    self _meth_8235();

    if ( !var_0 && !( _id_0A69::_id_6A43() == "br" ) )
        self painvisionoff();

    self _meth_8768();
    [[ level._id_AB91 ]]();
    _id_06B9::_id_4C09( "callback_on_player_spawned", self );
    self _meth_8282();
    var_11 = !var_0 || istrue( self._id_59BE );

    if ( var_11 )
    {
        if ( _func_0104( self ) && isdefined( level._id_2777 ) && isdefined( level._id_2777["player_spawned"] ) )
            self [[ level._id_2777["player_spawned"] ]]();

        if ( isdefined( level._id_9BC3 ) )
            [[ level._id_9BC3 ]]( self._id_3979, self._id_045B, "SPAWN", self._id_E34F[0], self._id_E34F[1], self._id_E390 );

        if ( !_func_0104( self ) )
        {
            if ( !isdefined( self._id_0309["distTrackingPassed"] ) )
                thread _id_F375( self._id_E290._id_E32F );
            else
            {
                var_12 = scripts\mp\gamelogic::_id_E75E( "round", "timePlayed", 0 );

                if ( var_12 - self._id_0309["afkResetTime"] > 240 )
                {
                    self._id_0309["afkResetTime"] = var_12;
                    self._id_0309["distTrackingPassed"] = undefined;
                    self._id_0309["totalDistTraveledAFK"] = undefined;
                    thread _id_F375( self._id_E290._id_E32F );
                }
            }
        }
    }

    if ( !var_0 )
    {
        self._id_9BA9 = -1;

        if ( !_id_06B9::is_valid_client( self ) )
        {
            self._id_9BA9 = game["life_count"];
            game["life_count"]++;
        }

        self._id_8FF7 = -1;

        if ( getdvarint( "#x3ca3a59bedef3457" ) != 0 )
            _func_01DA( "lifeCount", game["life_count"] );
    }

    if ( isdefined( self._id_D059 ) )
        _id_0780::_id_9771( self, self._id_D059 );

    if ( !istrue( self._id_DB60 ) )
        self._id_D059 = undefined;

    scripts\engine\trace::_id_38F9();
    scripts\cp_mp\hostmigration::_id_D4C6( self._id_37D9 );

    if ( isdefined( level._id_4228 ) )
        self [[ level._id_4228 ]]( var_0 );
    else
        scripts\cp_mp\hostmigration::_id_6F94( self._id_045B, self._id_37D9, undefined, undefined, var_1 || self._id_9355 > 0 );

    if ( _func_00BE( "ui_prematch_period" ) )
        thread _id_DCAC();

    if ( !istrue( game["isLaunchChunk"] ) )
    {
        thread _id_979C();

        if ( level._id_39F9 && !self _meth_81D2() )
            thread _id_FC30( self );
    }

    if ( isdefined( game["roundsPlayed"] ) && game["roundsPlayed"] > 0 )
    {
        if ( !isdefined( self._id_37E1 ) || !self._id_37E1 )
        {
            if ( isdefined( self._id_37DB ) )
                self._id_37E1 = 1;
        }
    }

    if ( getdvarint( "#x3863d66ab814c070" ) )
        _id_0A74::_id_D717( 1 );

    if ( _func_0104( self ) )
        _id_0A74::_id_0BC4( 0 );

    _id_06BB::_id_1552( 0 );

    if ( istrue( game["inLiveLobby"] ) || _id_0A69::_id_6A43() == "br" && !_id_07A8::_id_609F( "prematch_done" ) )
    {

    }
    else if ( !_id_07A8::_id_609F( "prematch_done" ) )
        _id_15A3( self );
    else
    {
        var_13 = !self._id_7598;
        _id_0A74::_id_0BC4( 0, var_13 );
        _id_0A74::_id_0BC5( 0, var_13 );
    }

    if ( !istrue( self._id_7598 ) )
        _id_07AC::_id_FCBB();

    self._id_7598 = 1;
    self._id_0309["hasSpawned"] = 1;
    waittillframeend;
    self._id_E304 = undefined;
    self._id_46A2 = undefined;

    if ( !istrue( level._id_4AC6 ) && isdefined( self._id_E274 ) || istrue( level._id_4AC6 ) && isdefined( self._id_E274 ) && _id_0A69::_id_6A43() == "arm" )
    {
        self._id_10A1C = var_1;
        self._id_46A2 = 1;
        self notify( "spawncamera_start" );
    }

    if ( !istrue( self._id_46A2 ) )
    {
        self notify( "spawned_player" );
        level notify( "player_spawned", self, var_1 );
        thread _id_D6CE();
    }

    if ( game["state"] == "postgame" )
        _id_07AC::_id_5F45();

    if ( _id_0780::_id_1747() && !var_0 )
    {
        if ( _id_0780::_id_173C() )
            level._id_E28C = level._id_E28C + 1;
        else
            _id_0780::_id_173E();

        if ( _id_0780::_id_1743( level._id_E28C ) )
        {
            if ( isdefined( level._id_E2F1._id_E34D ) )
            {
                _id_0780::_id_1744( self, self._id_E34D, level._id_E28C, self._id_E290._id_E33F );
                _id_0780::_id_1746( self._id_E290._id_E33F._id_02EA, self._id_045B, self._id_9355, level._id_E28C );
                _id_0780::_id_1745( self, self._id_E290._id_E33F._id_02EA, level._id_E28C );
            }
        }

        self._id_9035 = self._id_E290._id_E33F;
    }

    if ( !istrue( self._id_46A2 ) )
        self._id_E290 = undefined;

    if ( !isdefined( self._id_C7AF ) )
        thread scripts\cp_mp\hostmigration::_id_FC8E();

    var_14 = 0;

    if ( var_14 || _id_0A69::_id_60D8() && _id_0A69::_id_9AB3() )
    {
        self _meth_86B1( 1 );
        self _meth_86B0( 1 );
    }
}

_id_979C()
{
    self endon( "death_or_disconnect" );
    level endon( "game_ended" );

    if ( _id_07A8::_id_609F( "prematch_done" ) )
        return;

    _id_07A8::_id_60A3( "prematch_done" );

    if ( isdefined( self._id_4118 ) && self._id_4118 != "juggernaut" )
        scripts\cp_mp\hostmigration::_id_961E( self._id_702D, self._id_37E4, self._id_4118 );
}

_id_A6A0()
{
    waitframe();
    self notify( "force_regeneration" );
}

_id_D6CE()
{
    self endon( "disconnect" );
    waitframe();
    self _meth_82F6( "ui_player_spawned_notify", gettime() );
}

_id_B748( var_0 )
{
    self allowdoublejump( var_0 );
    _id_06BB::_id_1516( var_0 );

    if ( !( var_0 && _id_0A69::_id_8743() ) )
        scripts\engine\trace::_id_1512( var_0 );

    _id_06BB::_id_155F( var_0 );
    _id_06BB::_id_1526( var_0 );
    _id_06BB::_id_152C( var_0 );
    _id_06BB::_id_1559( var_0 );
    _id_06BB::_id_1527( var_0 );

    if ( !istrue( level._id_4AAC ) )
    {
        _id_06BB::_id_1530( var_0 );
        _id_06BB::_id_152F( var_0 );
    }
}

_id_15A3( var_0 )
{
    var_0 [[ level._id_BB91 ]]( 0 );
    var_0._id_BB9D = 1;
}

_id_394C( var_0 )
{
    if ( istrue( var_0._id_BB9D ) && !level._id_609B )
    {
        var_0 [[ level._id_BB91 ]]( 1 );
        var_0._id_BB9D = undefined;
    }
}

_id_10833()
{
    level endon( "prematch_over" );
    self endon( "versus_menu_done" );

    for (;;)
    {
        self waittill( "luinotifyserver", var_0, var_1 );

        if ( var_0 == "versus_done" )
            self notify( "versus_menu_done" );
    }
}

_id_FC30( var_0 )
{
    var_0 endon( "death_or_disconnect" );

    for (;;)
    {
        var_0 _meth_8772();
        var_0 _meth_8779();
        wait 0.05;
    }
}

_id_E37B( var_0 )
{
    var_1 = 6;
    self endon( "disconnect" );

    if ( _func_0104( self ) )
        return;

    if ( level._id_E427 || self _meth_81E1() )
        self _meth_82F5( "cg_fovscale", "0.65" );
    else
        self _meth_82F5( "cg_fovscale", "1" );

    self _meth_82F6( "ui_mapshot_camera", 1 );
    self _meth_8576( "mapflyover" );
    var_2 = _id_077B::_id_6D7C( "camera_intro", "targetname" );

    if ( var_2.size == 0 || _id_07A8::_id_609F( "infil_will_run" ) )
    {
        self _meth_844D( "", 0.75 );
        return;
    }

    var_3 = undefined;
    var_4 = undefined;
    _id_D6D2();
    _id_0A70::_id_D5DD( 0 );
    _id_0A74::_id_FD24( "spectator" );
    self._id_0309["team"] = "spectator";
    self._id_045B = "spectator";
    _id_0A74::_id_392A();
    self._id_5F85 = undefined;
    _id_C642();

    foreach ( var_6 in level._id_EF86 )
        self allowprone( var_6, 0 );

    self allowprone( "freelook", 0 );
    self allowprone( "none", 0 );

    if ( isdefined( var_2 ) && var_2.size > 1 )
    {
        var_8 = _func_01B9( 0, var_2.size - 1 );
        var_3 = var_2[var_8];
    }
    else if ( isdefined( var_2 ) )
        var_3 = var_2[0];
    else
    {

    }

    var_3._id_5A0F = 1;
    _id_0A74::_id_0BC4( 1 );
    self _meth_837F( var_3._id_02EA, var_3._id_0054 );
    self solid( var_3._id_02EA, var_3._id_0054 );
    _id_0A74::_id_BD13( "playerlogic::spawnSpectatorMapCam() !!!CODE SPAWN!!! @" + var_3._id_02EA );

    if ( isdefined( level._id_84B7 ) )
        self visionsetmissilecamforplayer( level._id_84B7, 0 );

    thread sun_flare_vfx();
    thread stage_lighting();
    var_9 = _func_0205( "script_model", var_3._id_02EA );
    var_9 setmode( "tag_origin" );
    var_9._id_0054 = var_3._id_0054;
    thread _id_10833();

    if ( isdefined( var_0 ) && var_0 == 99 )
        var_10 = "debug";
    else if ( _id_07A8::_id_609F( "prematch_done" ) )
        var_10 = "prematch_over";
    else if ( self._id_103AA )
        var_10 = "versus_menu_done";
    else
        var_10 = _id_077B::_id_108A6( 2, "versus_menu_done", "prematch_over" );

    if ( var_10 == "timeout" )
    {
        if ( _id_07A8::_id_609F( "prematch_done" ) )
            var_10 = "prematch_over";
        else
            var_10 = "versus_menu_done";
    }

    if ( var_10 == "prematch_over" )
    {
        self _meth_844D( "", 0.75 );
        return;
    }

    if ( self _meth_81E1() && self _meth_81E2() )
    {
        var_11 = self _meth_81E3();
        var_11 notify( "versus_menu_done" );
        waitframe();
    }

    self _meth_805E( var_9, "tag_origin", 1 );
    var_12 = _id_0999::_id_6B0E();
    self notify( "mapCamera_start" );

    switch ( var_12 )
    {
        case "mp_parkour":
            var_9 _meth_82CB( "iw7_mp_intro_camera_parkour" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_frontier":
            var_9 _meth_82CB( "iw7_mp_intro_camera_frontier" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_fallen":
            var_9 _meth_82CB( "iw7_mp_intro_camera_fallen" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_proto":
            var_9 _meth_82CB( "iw7_mp_intro_camera_proto" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_metropolis":
            var_9 _meth_82CB( "iw7_mp_intro_camera_metropolis" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_dome_iw":
            var_9 _meth_82CB( "iw7_mp_intro_camera_dome_iw" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_breakneck":
            var_9 _meth_82CB( "iw7_mp_intro_camera_breakneck" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_desert":
            var_9 _meth_82CB( "iw7_mp_intro_camera_desert" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_divide":
            var_9 _meth_82CB( "iw7_mp_intro_camera_divide" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_quarry":
            var_9 _meth_82CB( "iw7_mp_intro_camera_quarry" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_skyway":
            var_9 _meth_82CB( "iw7_mp_intro_camera_skyway" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_rivet":
            var_9 _meth_82CB( "iw7_mp_intro_camera_rivet" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_riot":
            var_9 _meth_82CB( "iw7_mp_intro_camera_riot" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_dome_dusk":
            var_9 _meth_82CB( "iw7_mp_intro_camera_dome_iw" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_geneva":
            var_9 _meth_82CB( "iw7_mp_intro_camera_geneva" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_afghan":
            var_9 _meth_82CB( "iw7_mp_intro_camera_afghan" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_neon":
            var_9 _meth_82CB( "iw7_mp_intro_camera_neon" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_prime":
            var_9 _meth_82CB( "iw7_mp_intro_camera_prime" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_flip":
            var_9 _meth_82CB( "iw7_mp_intro_camera_flip" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_mansion":
            var_9 _meth_82CB( "iw7_mp_intro_camera_mansion" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_marsoasis":
            var_9 _meth_82CB( "iw7_mp_intro_camera_marsoasis" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        case "mp_junk":
            var_9 _meth_82CB( "iw7_mp_intro_camera_junk" );
            self _meth_844D( "", 0.75 );
            self _meth_8275( "mp_camera_intro_whoosh" );
            wait( var_1 - 0.25 );
            return;
        default:
            break;
    }

    wait 0.25;
    self _meth_844D( "", 0.75 );
    var_13 = var_3;
    var_4 = _id_077B::_id_6D7A( var_3._id_0457, "targetname" );
    var_14 = 0;

    for (;;)
    {
        if ( isdefined( var_13._id_E3F4 ) )
        {
            var_15 = 1 / var_13._id_E3F4;
            var_16 = var_15 * distance( var_13._id_02EA, var_4._id_02EA );
        }
        else
            var_16 = distance( var_13._id_02EA, var_4._id_02EA );

        var_14 = var_14 + var_16;
        var_13._id_4B76 = var_16;
        var_13 = var_4;

        if ( isdefined( var_13._id_0457 ) )
        {
            var_4 = _id_077B::_id_6D7A( var_13._id_0457, "targetname" );
            continue;
        }

        break;
    }

    var_13._id_5519 = 1;
    var_13 = var_3;
    var_4 = _id_077B::_id_6D7A( var_3._id_0457, "targetname" );

    for (;;)
    {
        var_17 = var_13._id_4B76 / var_14;
        var_18 = var_17 * var_1;

        if ( isdefined( var_4._id_5519 ) )
            var_19 = var_18 / 2;
        else
            var_19 = 0;

        if ( isdefined( var_13._id_5A0F ) )
            var_20 = var_18 / 2;
        else
            var_20 = 0;

        var_9 _meth_823B( var_4._id_02EA, var_18, var_20, var_19 );
        var_9 rotateroll( var_4._id_0054, var_18, var_20, var_19 );

        if ( isdefined( var_4._id_5519 ) )
        {
            var_21 = int( var_18 / 2 );
            wait( var_21 );
            wait( var_21 );
        }
        else
            wait( var_18 );

        var_13 = var_4;

        if ( isdefined( var_13._id_0457 ) )
        {
            var_4 = _id_077B::_id_6D7A( var_13._id_0457, "targetname" );
            continue;
        }

        break;
    }

    _id_0A74::_id_0BC4( 0 );

    if ( isdefined( level._id_45AD ) )
        self visionsetmissilecamforplayer( level._id_45AD, 0 );

    self._id_E688 = var_9;
    self _meth_82F6( "ui_mapshot_camera", 0 );
}

_id_E37A( var_0, var_1, var_2 )
{
    self notify( "spawned" );
    self notify( "end_respawn" );
    self notify( "joined_spectators" );
    level notify( "joined_spectators", self );

    if ( isdefined( self._id_43F0 ) )
    {
        var_0 = self._id_43F0;
        var_1 = _func_025B( self._id_02EA - self._id_43F0 );
    }

    if ( isdefined( self._id_E688 ) && !isdefined( var_0 ) )
    {
        var_0 = self._id_E688._id_02EA;
        var_1 = self._id_E688._id_0054;
        self._id_E688 _meth_809A();
    }

    _id_7D60( var_0, var_1, var_2 );
}

_id_C666( var_0, var_1 )
{
    if ( isdefined( self._id_43F0 ) )
    {
        var_0 = self._id_43F0;

        if ( isdefined( self._id_43EF ) )
            var_1 = self._id_43EF;
        else
            var_1 = _func_025B( self._id_02EA - self._id_43F0 );
    }

    _id_7D60( var_0, var_1 );

    if ( self.wasusingfixeddeathcamera )
    {
        self.wasusingfixeddeathcamera = 0;
        self _meth_85B5( 1 );
    }
}

_id_7D60( var_0, var_1, var_2 )
{
    _id_D6D2();
    var_3 = self._id_0309["team"];

    if ( isdefined( var_3 ) && ( var_3 == "spectator" || var_3 == "follower" ) && !level._id_609B )
        _id_0A70::_id_D5DD( 0 );

    scripts\cp_mp\hostmigration::_id_9607();
    _id_0A74::_id_FD24( "spectator" );
    _id_0A74::_id_392A();
    self._id_5F85 = undefined;
    _id_C642();
    _id_07F1::_id_D6D7();
    _id_AB93( var_0, var_1, var_2 );

    if ( level._id_EF62 && !level._id_E427 && !self _meth_81E1() )
        _id_0A74::_id_D51D();
}

_id_6C31( var_0 )
{
    if ( var_0 < 0 )
        return undefined;

    for ( var_1 = 0; var_1 < level._id_B758.size; var_1++ )
    {
        if ( level._id_B758[var_1] getentitynumber() == var_0 )
            return level._id_B758[var_1];
    }

    return undefined;
}

_id_AB93( var_0, var_1, var_2 )
{
    if ( isdefined( var_0 ) && isdefined( var_1 ) )
    {
        self _meth_837F( var_0, var_1 );
        self solid( var_0, var_1 );
        _id_0A74::_id_BD13( "playerlogic::onSpawnSpectator() !!!CODE SPAWN!!! @" + var_0 );
        return;
    }

    var_3 = _id_6D4C();

    if ( istrue( level._id_FECC ) )
    {
        if ( self._id_0393 == "allies" )
            var_3 = level._id_E275["gw_fob_alliesHQ"]["allies"];
        else if ( self._id_0393 == "axis" )
            var_3 = level._id_E275["gw_fob_axisHQ"]["axis"];
    }

    var_4 = 8;

    if ( isdefined( level._id_3079 ) && level._id_3079.size )
    {
        for ( var_5 = 0; var_5 < level._id_3069 + 1 && var_5 < var_4; var_5++ )
        {
            if ( !isdefined( level._id_3079[var_5] ) || !isdefined( level._id_305D[var_5] ) )
                continue;

            self setmissileminimapvisible( var_5, level._id_3079[var_5], level._id_305D[var_5] );
            level._id_3072[var_5]._id_02EA = level._id_3079[var_5];
            level._id_A760[var_5]._id_02EA = level._id_3079[var_5];
            level._id_3072[var_5]._id_0054 = level._id_305D[var_5];
            level._id_A760[var_5]._id_0054 = level._id_305D[var_5];
        }
    }
    else
    {
        for ( var_5 = 0; var_5 < var_4; var_5++ )
            self setmissileminimapvisible( var_5, var_3._id_02EA, var_3._id_0054 );
    }

    self _meth_837F( var_3._id_02EA, var_3._id_0054 );

    if ( isdefined( var_2 ) )
    {
        self allowprone( "freelook", 1 );
        self allowprone( "none", 1 );
    }

    if ( istrue( level._id_886B ) && !self._id_7598 )
        self _meth_8281( var_3._id_02EA );

    self solid( var_3._id_02EA, var_3._id_0054 );
    _id_0A74::_id_BD13( "playerlogic::onSpawnSpectator() !!!CODE SPAWN!!! @" + var_3._id_02EA );
}

_id_6D4C()
{
    var_0 = getentarray( "mp_global_intermission", "classname" );
    var_1 = [];

    if ( isdefined( _id_0999::_id_6AF9() ) )
    {
        if ( level._id_96B5 == "locale_6" )
        {
            var_2 = _func_0205( "script_origin", ( 25642, -26550, 1818 ) );
            var_2._id_0054 = ( 14, 101, 0 );
            return var_2;
        }
        else if ( level._id_96B5 == "locale_3" )
        {
            var_2 = _func_0205( "script_origin", ( 34440, -18522, 995 ) );
            var_2._id_0054 = ( 10, 281, 0 );
            return var_2;
        }

        var_2 = undefined;

        foreach ( var_4 in var_0 )
        {
            if ( isdefined( var_4._id_0375 ) && var_4._id_0375 == level._id_96B5 )
                var_2 = var_4;
        }

        if ( isdefined( var_2 ) )
            return var_2;
        else
        {
            foreach ( var_4 in var_0 )
            {
                if ( !isdefined( var_4._id_0375 ) || !_func_0121( var_4._id_0375, "locale" ) )
                {
                    var_1[var_1.size] = var_4;
                    continue;
                }

                var_4 _meth_809A();
            }
        }
    }
    else if ( var_0.size != 1 )
    {
        foreach ( var_4 in var_0 )
        {
            if ( !isdefined( var_4._id_0375 ) || !_func_0121( var_4._id_0375, "locale" ) )
            {
                var_1[var_1.size] = var_4;
                continue;
            }

            var_4 _meth_809A();
        }
    }
    else
        var_1 = var_0;

    var_4 = _id_07EE::_id_6D2E( var_1 );
    return var_4;
}

_id_E30B( var_0, var_1, var_2 )
{
    if ( _id_07FF::_id_86C2() )
        return;

    self endon( "disconnect" );
    self notify( "spawned" );
    self notify( "end_respawn" );

    if ( !isdefined( var_1 ) )
        var_1 = "intermission";

    if ( !isdefined( var_2 ) )
        var_2 = 1;

    _id_D6D2();
    _id_0A70::_id_D5DD( 0 );
    _id_0A70::_id_3935();
    _id_0A74::_id_0BC4( 1 );

    if ( var_2 )
        self _meth_82F4( "#x35055a6cbabf80c5e", 1 );

    if ( isdefined( level._id_5A83 ) && level._id_5A83 != "none" && isdefined( level._id_9B8E ) && _id_0A69::_id_10A14() && !istrue( level._id_4CD9 ) )
        wait( level._id_9B8E );

    if ( !istrue( level._id_4CD9 ) )
        _id_0A74::_id_FD24( var_1 );

    _id_0A74::_id_392A();
    self._id_5F85 = undefined;

    if ( !isdefined( var_0 ) )
    {
        if ( !isdefined( level._id_96B5 ) )
        {
            var_3 = getentarray( "mp_global_intermission", "classname" );
            var_3 = _id_07EF::_id_34D2( var_3 );
            var_0 = var_3[0];
        }
        else
            var_0 = _id_6D4C();
    }

    if ( !isdefined( level._id_4220 ) )
    {
        self solid( var_0._id_02EA, var_0._id_0054 );
        _id_0A74::_id_BD13( "playerlogic::spawnIntermission() !!!CODE SPAWN!!! @" + var_0._id_02EA );
        _id_0A74::_id_D51D();
    }

    _id_0A74::_id_0BC4( 1 );
}

_id_E2BE()
{
    if ( isdefined( level._id_9FDD ) && self [[ level._id_9FDD ]]() )
        return;

    if ( isdefined( level._id_4220 ) && _id_0A69::_id_10A14() )
        level notify( "start_custom_ending" );

    if ( !istrue( self._id_3C45 ) )
        _id_0A74::_id_0BC4( 1 );

    if ( istrue( level._id_4CD9 ) )
    {
        self notify( "spawned" );
        _id_0A74::_id_392A();
    }
    else
        _id_E37A();
}

_id_D6D2()
{
    _id_099F::_id_0D60();
    self _meth_83F3( "damage_heavy" );
    self._id_43D7 = undefined;
}

_id_2F14( var_0 )
{
    if ( !isdefined( self._id_3B5D ) )
        return;

    if ( getdvarint( "#x3ca3a59bedef3457" ) != 0 )
    {
        var_1 = _func_00AC( "commonMatchData", "player_count_left" );
        var_1++;
        _func_01DA( "commonMatchData", "player_count_left", var_1 );
    }

    if ( _id_0A6F::_id_87A6() )
        self _meth_850E();

    _id_06BB::_id_F737( level._id_9B9F, var_0 );
    var_2 = _func_020F();
    var_2._id_030F = self;
    var_2.disconnectreason = var_0;
    _id_06B9::_id_4C09( "callback_on_player_disconnect", var_2 );
    removeperk();
    _id_07EE::_id_C4A2();
    _id_07EE::_id_C499();
    _id_099C::_id_C49A();
    var_3 = self getentitynumber();

    if ( !level._id_EF62 )
        game["roundsWon"][self._id_723F] = undefined;

    if ( level._id_E427 )
    {
        var_4 = level._id_B758;

        if ( var_4.size <= 1 )
            level thread _id_07AC::_id_5E7E();
    }

    if ( isdefined( self._id_024B ) && isdefined( self._id_0146 ) )
    {
        if ( _id_0A69::_id_8744() && 3 > self._id_F23F["total"] )
        {
            if ( !isdefined( self._id_1A77 ) )
                return;

            var_5 = self._id_1A77;
            _func_01E8( self, self._id_3979, var_5 );
        }
        else if ( 120 < self._id_F23F["total"] )
        {
            var_6 = ( self._id_024B - self._id_0146 ) / ( self._id_F23F["total"] / 60 );
            _func_01E8( self, self._id_3979, var_6 );
        }
    }
    else
    {

    }

    var_7 = self getentitynumber();
    var_8 = self._id_723F;
    _func_013E( "Q;" + var_8 + ";" + var_7 + ";" + self._id_02BA + "\n" );

    if ( _func_038C() )
        _func_038A( "Q;" + var_8 + ";" + var_7 + ";" + self._id_02BA + "\n" );

    thread _id_07A5::_id_4AF6();

    if ( level._id_609B )
        _id_07AE::_id_C482();

    if ( isdefined( self._id_045B ) )
        _id_C4AF();

    _id_09A2::_id_3931( self );

    if ( isdefined( self._id_045B ) && isdefined( self._id_E493 ) && self._id_045B != "spectator" && self._id_045B != "follower" )
        _id_07C9::_id_9153( self._id_045B, self._id_E493 );

    if ( self._id_0392 == "playing" && !( isdefined( self._id_59C0 ) && self._id_59C0 ) )
        _id_C496( 1 );
    else if ( self._id_0392 != "playing" && ( scripts\mp\gametypes\br_public::_id_8AE7( self ) || scripts\mp\gametypes\br_public::_id_88F5( self ) || scripts\mp\gametypes\br_public::_id_89E8( self ) ) )
        _id_C496( 1 );
    else if ( self._id_0392 == "intermission" && isdefined( self._id_045B ) && _id_077B::_id_1B78( level._id_EF67[self._id_045B]["alivePlayers"], self ) )
        _id_C496( 1 );
    else if ( self._id_0392 == "spectator" || self._id_0392 == "dead" )
        level thread [[ level._id_FC72 ]]();

    if ( isdefined( self._id_045B ) )
        _id_0A7C::_id_FF40( "disconnect", self._id_045B, self );

    _id_0A65::_id_CA24( self );
    _id_07AC::_id_FCBA();
}

removeperk()
{
    var_0 = 0;

    for ( var_1 = 0; var_1 < level._id_B758.size; var_1++ )
    {
        if ( level._id_B758[var_1] == self )
        {
            for ( var_0 = 1; var_1 < level._id_B758.size - 1; var_1++ )
                level._id_B758[var_1] = level._id_B758[var_1 + 1];

            level._id_B758[var_1] = undefined;
            break;
        }
    }

    if ( !_func_0107( self ) )
        level._id_B674[self getentitynumber()] = undefined;

    level._id_B77B[self getentitynumber()] = undefined;
}

_id_8148()
{
    if ( level._id_E427 || self _meth_81E1() )
    {
        self _meth_82F5( "cg_fovscale", "0.75" );
        _func_01D0( "r_materialBloomHQScriptMasterEnable", 0 );
    }
    else
        self _meth_82F5( "cg_fovscale", "1" );
}

_id_8147()
{
    _func_01D0( "#x32ffe930f83bee667", 1 );
    _func_01D0( "#x3c7ddb09585c5a055", 1 );

    if ( level._id_74A8 )
    {
        _func_01D0( "#x32ffe930f83bee667", 0 );
        _func_01D0( "#x3c7ddb09585c5a055", 1 );
    }

    if ( isdefined( level._id_1630 ) && level._id_1630 )
        _func_01D0( "#x3ab3d8fbdc5691bb", 1 );
    else
        _func_01D0( "#x3ab3d8fbdc5691bb", 0 );

    self _meth_82F5( "cg_drawSpectatorMessages", 1 );
    _id_8148();

    if ( _id_0A69::_id_6A46() )
        self _meth_82F5( "#x37934954127a2383d", 0, "#x3b3c6c58425dfe28a", 1, "#x3fe767194384b10f1", 1, "#x36aeaa9eea9f6efb9", 0 );
    else
        self _meth_82F5( "#x37934954127a2383d", 0, "#x3b3c6c58425dfe28a", 1, "#x3fe767194384b10f1", 1, "#x36aeaa9eea9f6efb9", 0 );

    if ( level._id_EF62 )
        self _meth_82F5( "cg_everyonehearseveryone", 0 );

    self _meth_82F4( "ui_altscene", 0 );

    if ( getdvarint( "scr_hitloc_debug" ) )
    {
        for ( var_0 = 0; var_0 < 6; var_0++ )
            self _meth_82F4( "ui_hitloc_" + var_0, "" );

        self._id_7990 = 1;
    }
}

_id_3B5C()
{
    if ( !isdefined( self ) )
        return;

    if ( self._id_0393 == "none" && _id_0A69::_id_9BB3() && level._id_EF62 && !_func_0107( self ) && !_func_03D5( self ) && !self _meth_81D2() && _id_0A69::_id_6A43() != "infect" )
    {
        wait 1.5;
        _func_012D( self getentitynumber(), "EXE/PLAYERKICKED_INVALIDTEAM" );
    }
}

_id_BEBE()
{
    for (;;)
    {
        if ( !isdefined( level._id_B773 ) )
        {
            waitframe();
            continue;
        }

        break;
    }

    for (;;)
    {
        for ( var_0 = 0; var_0 < level._id_B773.size; var_0++ )
        {
            var_1 = level._id_B773[var_0];

            if ( isdefined( var_1 ) )
            {
                level notify( "connected", var_1 );
                var_1 notify( "connected_continue" );
                level._id_B773[var_0] = undefined;
                break;
            }
        }

        var_2 = _id_077B::_id_1BA9( level._id_B773 );
        level._id_B773 = var_2;
        waitframe();
    }
}

_id_ABC4( var_0, var_1 )
{
    if ( var_0 != "versus_done" )
        return;

    self._id_103AA = 1;
}

_id_826F()
{
    level endon( "game_ended" );
    level thread _id_C13F();

    for (;;)
    {
        level waittill( "connected", var_0 );
        level thread _id_4010( var_0 );
    }
}

_id_C13F()
{
    level endon( "game_ended" );
    _id_07A8::_id_60A3( "prematch_done" );
    wait 4;

    for (;;)
    {
        wait 1;

        foreach ( var_1 in level._id_B758 )
        {
            if ( istrue( var_1._id_3195 ) )
                var_1 thread _id_FCFF();
        }
    }
}

_id_4010( var_0 )
{
    var_0 endon( "disconnect" );
    var_0 waittill( "spawned_player" );
    var_0._id_D022 = [];
    var_0._id_D022["distanceTotal"] = 0;
    var_0._id_D022["movingTotal"] = 0;
    var_0._id_D022["movementUpdateCount"] = 0;
    var_0._id_CB40 = var_0._id_02EA;
    var_0._id_B9FF = var_0._id_02EA;
    var_0._id_3195 = 1;
}

_id_FCFF()
{
    self endon( "disconnect" );

    if ( !isdefined( self._id_CB40 ) )
    {
        self._id_CB40 = self._id_02EA;
        self._id_B9FF = self._id_02EA;
    }

    if ( _id_0A74::_id_8AB5() )
    {
        self waittill( "stopped_using_remote" );
        self._id_CB40 = self._id_02EA;
        self._id_B9FF = self._id_02EA;
        return;
    }

    self._id_D022["movementUpdateCount"]++;
    self._id_D022["distanceTotal"] = self._id_D022["distanceTotal"] + distance2d( self._id_CB40, self._id_02EA );
    self._id_CB40 = self._id_02EA;

    if ( self._id_D022["movementUpdateCount"] % 5 == 0 )
    {
        var_0 = distance2d( self._id_B9FF, self._id_02EA );
        self._id_B9FF = self._id_02EA;

        if ( var_0 > 16 )
            self._id_D022["movingTotal"]++;
    }
}

_id_DBCF( var_0 )
{
    return _id_0A69::_id_6A43() != "br" && var_0 < level._id_BB9F && !istrue( self._id_2C42 ) && !_id_07A8::_id_609F( "infil_will_run" );
}

_id_D730( var_0 )
{
    var_1 = _func_0152( self );
    var_1._id_04DE = 0;
    var_1._id_04E1 = 0;
    var_1._id_003A = "left";
    var_1.alignx = "top";
    var_1._id_03BD = 1;
    var_1._id_020C = "fullscreen";
    var_1._id_04B8 = "fullscreen";
    var_1._id_01C0 = 1;
    var_2 = 0.0;
    var_3 = 0.5;

    if ( isdefined( var_2 ) && var_2 > 0 )
        var_1._id_0047 = 0;
    else
        var_1._id_0047 = 1;

    var_1 _meth_8378( "black", 640, 480 );

    if ( isdefined( var_2 ) && var_2 > 0 )
    {
        if ( isdefined( self ) )
            self notify( "fadeDown_start" );

        var_1 fadeovertime( var_2 );
        var_1._id_0047 = 1.0;
        wait( var_2 );
    }

    if ( isdefined( self ) )
        self waittill( var_0 );

    var_1 fadeovertime( var_3 );
    var_1._id_0047 = 0.0;
    wait( var_3 );

    if ( isdefined( var_1 ) )
        var_1 delete();
}

_id_2F10()
{
    self._id_0309["streamSyncComplete"] = 1;
    self notify( "player_active" );
}

_id_6B1D()
{
    if ( level._id_60D1 != "br" )
        return 30;
    else
        return 200;
}

_id_2F11()
{
    self._id_103AA = 0;
    self._id_0309["afkResetTime"] = 0;
    self._id_03E0 = "hud_status_connecting";
    self waittill( "begin" );
    self._id_03E0 = "";

    if ( _func_0104( self ) || getdvarint( "#x3c7c37ec2ae95353e", 0 ) == 1 )
        _id_2F10();

    self._id_3B62 = undefined;
    self _meth_8282();

    if ( _id_0A69::_id_6A43() != "br" )
        self _meth_86A2();

    var_0 = 1;

    if ( isdefined( level._id_AB4D ) )
        var_0 = self thread [[ level._id_AB4D ]]();

    if ( _id_07A8::_id_609F( "prematch_done" ) && istrue( level._id_FECC ) && isdefined( self._id_0393 ) )
    {
        if ( self._id_0393 == "allies" )
        {
            var_1 = level._id_E275["gw_fob_alliesHQ"]["allies"];
            self _meth_86A1( var_1._id_02EA, 1 );
        }
        else if ( self._id_0393 == "axis" )
        {
            var_1 = level._id_E275["gw_fob_axisHQ"]["axis"];
            self _meth_86A1( var_1._id_02EA, 1 );
        }
    }

    self _meth_844D( "bw", 0 );
    var_2 = "connected_continue";
    var_3 = _id_0A69::_id_6DC8() / 1000 + 6;

    if ( !isdefined( self._id_0309["streamSyncComplete"] ) && _id_DBCF( var_3 ) )
        var_2 = "player_active";

    thread _id_D730( var_2 );
    _id_0A69::_id_352C();
    level._id_B773[level._id_B773.size] = self;
    self waittill( "connected_continue" );
    self._id_3B5D = 1;

    if ( !isdefined( level._id_F94F ) )
        level._id_F94F = 1;
    else
        level._id_F94F++;

    _id_81E4();
    self _meth_82F6( "ui_scoreboard_freeze", 0 );

    if ( self _meth_81C3() )
        level._id_030F = self;

    if ( getdvar( "#x3d2f7b504fac9f5cf" ) == "1" )
    {
        if ( _id_07A8::_id_609F( "prematch_done" ) )
            _func_01E4( "ui_last_player_connected", self getentitynumber() );
    }
    else if ( !level._id_E427 && !isdefined( self._id_0309["score"] ) )
    {
        var_4 = 0;
        var_5 = getdvarint( "scr_skip_connected_msg_until_time", 0 );

        if ( var_5 > 0 )
        {
            if ( isdefined( level._id_E72A ) )
            {
                var_6 = ( gettime() - level._id_E72A ) / 1000;

                if ( var_6 <= var_5 )
                    var_4 = 1;
            }
            else
                var_4 = 1;
        }

        if ( var_4 == 0 )
        {

        }
    }

    self._id_FF12 = self _meth_81F2();
    _id_8147();
    _id_8255();
    _id_077E::_id_199C();

    if ( getdvar( "#x3cdea067225b5e163" ) == "1" )
        level waittill( "eternity" );

    self._id_723F = _id_0A74::_id_6E04();
    var_7 = 0;

    if ( !isdefined( self._id_0309["clientid"] ) )
    {
        self._id_0309["clientid"] = game["clientid"];
        game["clientid"]++;
        var_8 = _id_6B1D();

        if ( game["clientid"] >= var_8 )
        {
            game["clientid"] = var_8 - 1;
            self._id_0309["clientid"] = var_8 - 1;
        }

        var_7 = 1;
        self._id_0309["matchdataWeaponStats"] = [];
        self._id_0309["matchdataScoreEventCounts"] = [];
        self._id_0309["xpAtLastDeath"] = 0;
        self._id_0309["scoreAtLastDeath"] = 0;
    }

    _id_0796::_id_C75C();

    if ( istrue( level._id_5CB3 ) )
        thread _id_07A9::_id_5CB0( self );

    if ( var_7 )
    {
        scripts\mp\gamelogic::_id_E76E( "round", "timePlayed", 0, 1 );
        self _meth_8364( "common", "round", "totalXp", 0 );
        _id_0999::_id_E6DB();

        if ( !isdefined( game["uniquePlayerCount"] ) )
            game["uniquePlayerCount"] = 1;
        else
            game["uniquePlayerCount"]++;
    }

    self._id_3979 = self._id_0309["clientid"];
    self._id_0309["teamKillPunish"] = 0;
    _func_013E( "J;" + self._id_723F + ";" + self getentitynumber() + ";" + self._id_02BA + "\n" );

    if ( _func_038C() )
        _func_038A( "J;" + self._id_723F + ";" + self getentitynumber() + ";" + self._id_02BA + "\n" );

    if ( getdvarint( "#x3ca3a59bedef3457" ) != 0 )
    {
        var_9 = _func_00AC( "commonMatchData", "player_count" );

        if ( var_7 )
        {
            var_9++;
            _func_01DA( "commonMatchData", "player_count", var_9 );
        }

        if ( _func_0107( self ) || _func_03D5( self ) || _func_0104( self ) )
            var_10 = 1;
        else
            var_10 = 0;

        if ( _id_0A69::_id_9BB3() && !_id_0A69::_id_47A6() && !var_10 )
        {

        }
    }

    if ( var_7 )
        _id_06B9::_id_4C09( "callback_on_player_connect", self );

    if ( level._id_F94F <= _id_6B1D() )
    {
        if ( var_7 && isdefined( level._id_9BC5 ) )
            [[ level._id_9BC5 ]]( self._id_3979, self._id_045B, self._id_02BA );
    }

    if ( !level._id_EF62 )
        game["roundsWon"][self._id_723F] = 0;

    if ( !isdefined( self._id_0309["cur_kill_streak"] ) )
        self._id_0309["cur_kill_streak"] = 0;

    if ( !isdefined( self._id_0309["cur_death_streak"] ) )
        self._id_0309["cur_death_streak"] = 0;

    if ( level._id_AB13 )
        self._id_24AA = _id_07DB::_id_6C45( "bestStats", "killStreak" );

    self._id_8FC7 = -1;
    self._id_7598 = 0;
    self._id_10847 = 0;
    self._id_109C4 = 0;
    self._id_10A08 = 0;
    self._id_A24C = 1;
    self._id_A8D9 = 1;
    self._id_8D56 = 0;
    self._id_9355 = 0;

    if ( isdefined( self._id_0309["deaths"] ) )
        self._id_9355 = self._id_0309["deaths"];

    _id_C641();
    waittillframeend;
    level._id_B758[level._id_B758.size] = self;
    level._id_B77B[self getentitynumber()] = self;
    _id_07EE::_id_113C();
    _id_07EE::_id_1131();
    _id_099C::_id_1132();

    if ( game["state"] == "postgame" )
    {
        self._id_3B5E = 1;
        thread _id_E37A();
        self _meth_82F5( "cg_drawSpectatorMessages", 0 );
        self _meth_844D( "", 0.25 );
        _id_E30B();
        return;
    }

    if ( var_7 && ( _id_0A69::_id_6DC8() >= 60000 || game["roundsPlayed"] > 0 ) )
        self._id_8BC0 = 1;

    if ( _func_0104( self ) && isdefined( level._id_2777 ) && isdefined( level._id_2777["think"] ) )
        self thread [[ level._id_2777["think"] ]]();

    if ( _func_038C() && !_func_0104( self ) )
        _func_038B( self._id_723F );

    level endon( "game_ended" );

    if ( isdefined( level._id_7A93 ) )
        thread _id_07B7::_id_7A94();

    if ( isdefined( level._id_AB48 ) )
        [[ level._id_AB48 ]]();

    thread _id_09B8::_id_100F9( self );
    thread _id_0A42::_id_9B21();

    if ( !isdefined( self._id_0309["team"] ) )
    {
        var_3 = _id_0A69::_id_6DC8() / 1000 + 6;

        if ( _id_DBCF( var_3 ) )
        {
            _id_E37B();
            self _meth_8576( "default" );
            self _meth_82F6( "ui_mapshot_camera", 0 );
            _id_8148();
            self._id_0309["team"] = "";
            self._id_045B = "free";
        }
        else
            self _meth_844D( "", 0.5 );

        _id_3B5C();

        if ( self _meth_81D2() )
        {
            if ( self _meth_8156() )
                thread _id_07C9::_id_D558();
            else
                thread _id_07C9::_id_D6D9();
        }
        else if ( _func_038F() && ( self._id_0393 == "spectator" || self._id_0393 == "follower" ) )
        {
            self._id_0309["team"] = self._id_0393;
            self._id_045B = self._id_0393;
            thread _id_E37A();
        }
        else if ( ( _id_0A69::_id_9BB3() || _id_0A69::_id_96A2() || _func_0329() ) && self._id_0393 != "none" )
        {
            if ( var_0 )
                thread _id_E37A();

            if ( getdvar( "scr_br_gametype", "" ) == "dmz" && getdvarint( "scr_br_manual_team_assignment", 0 ) == 1 )
                thread _id_07F7::_id_AFFD();
            else
                thread _id_07C9::_id_D702( self._id_0393 );

            if ( _id_0A69::_id_1575() || _id_0A69::_id_DCA5() && !_func_0104( self ) )
                self _meth_82F6( "ui_options_menu", 2 );

            if ( !_id_0A69::_id_CA3E() && _id_0A69::_id_9BB3() && !_func_0329() )
                thread _id_8CCA();

            _id_3946();
            return;
        }
        else
        {
            if ( var_0 )
                thread _id_E37A();

            _id_07C9::_id_1EF5();

            if ( _id_0A69::_id_1575() || _id_0A69::_id_DCA5() && !_func_0104( self ) )
                self _meth_82F6( "ui_options_menu", 2 );

            if ( !_id_0A69::_id_CA3E() && _id_0A69::_id_9BB3() )
                thread _id_8CCA();

            _id_3946();
            return;
        }
    }
    else
    {
        self _meth_844D( "", 0.5 );
        _id_3B5C();
        var_14 = self._id_0309["team"];

        if ( _id_0A69::_id_9BB3() && !_func_0107( self ) && !_func_03D5( self ) && !self _meth_81D2() && getdvarint( "#x36e762e09a77fe062" ) )
            var_14 = self._id_0393;

        _id_07C9::_id_114D( var_14, 1 );

        if ( self _meth_81D2() )
        {
            thread _id_E37A();
            _id_3946();
            return;
        }

        if ( scripts\cp_mp\hostmigration::_id_8AC7( self._id_0309["class"] ) && var_14 != "spectator" )
        {
            thread _id_E282();
            _id_3946();
            return;
        }

        thread _id_E37A();

        if ( self._id_0309["team"] == "spectator" )
        {
            if ( _id_0A69::_id_4C58() && !istrue( self._id_0309["playerChoseSpectatorTeam"] ) )
                _id_07C9::_id_2490();
        }
        else
            _id_07C9::_id_247F();
    }

    _id_3946();
}

_id_2F18()
{
    if ( isdefined( self._id_3B5D ) && self._id_3B5D )
        _id_0A69::_id_FCD0();

    if ( self _meth_81C3() )
        _id_8148();

    var_0 = 0;

    foreach ( var_2 in level._id_B758 )
    {
        if ( !_func_0107( var_2 ) && !_func_03D5( var_2 ) )
            var_0++;
    }

    if ( !_func_0107( self ) && !_func_03D5( self ) )
    {
        level._id_7A91++;

        if ( level._id_7A91 >= var_0 * 2 / 3 )
            level notify( "hostmigration_enoughplayers" );
    }
}

_id_10B8( var_0, var_1 )
{
    var_2 = _id_07E1::_id_6CB8( var_0 );
    var_3 = _id_07E1::_id_6CBE( var_2 );
    var_4 = _id_07E1::_id_6CBD( var_2 );
    var_2 = var_2 + ( var_0 - var_3 ) / ( var_4 - var_3 );
    var_2 = var_2 + var_1;

    if ( var_2 < 0 )
    {
        var_2 = 0;
        var_5 = 0.0;
    }
    else if ( var_2 >= level._id_9C85 + 1.0 )
    {
        var_2 = level._id_9C85;
        var_5 = 1.0;
    }
    else
    {
        var_5 = var_2 - floor( var_2 );
        var_2 = int( floor( var_2 ) );
    }

    var_3 = _id_07E1::_id_6CBE( var_2 );
    var_4 = _id_07E1::_id_6CBD( var_2 );
    return int( var_5 * ( var_4 - var_3 ) ) + var_3;
}

_id_5EA1()
{
    self endon( "death_or_disconnect" );
    self endon( "spawned" );
    wait 60.0;

    if ( self._id_7598 )
        return;

    if ( self._id_0309["team"] == "spectator" || self._id_0309["team"] == "follower" )
        return;

    if ( !scripts\cp_mp\hostmigration::_id_8AC7( self._id_0309["class"] ) )
    {
        self._id_0309["class"] = "CLASS/CUSTOM1";
        self._id_37D9 = self._id_0309["class"];
    }

    thread _id_E282();
}

_id_8CCA()
{
    if ( getdvarint( "#x3d481e5995355da20", 0 ) == 1 )
        return;

    self endon( "death_or_disconnect" );
    self endon( "spawned" );
    self endon( "attempted_spawn" );
    var_0 = getdvarfloat( "scr_kick_time", 90 );
    var_1 = getdvarfloat( "scr_kick_mintime", 45 );
    var_2 = getdvarfloat( "scr_kick_hosttime", 120 );
    var_3 = gettime();

    if ( self _meth_81C3() )
        _id_8CD2( var_2 );
    else
        _id_8CD2( var_0 );

    var_4 = ( gettime() - var_3 ) / 1000;

    if ( var_4 < var_0 - 0.1 && var_4 < var_1 )
        return;

    if ( self._id_7598 )
        return;

    if ( self._id_0309["team"] == "spectator" || self._id_0309["team"] == "follower" )
        return;

    _func_012D( self getentitynumber(), "EXE/PLAYERKICKED_INACTIVE", 1 );
    level thread [[ level._id_FC72 ]]();
}

_id_8CD2( var_0 )
{
    level endon( "game_ended" );
    _id_07B7::_id_1084D( var_0 );
}

_id_A139()
{
    level endon( "game_ended" );
    self endon( "disconnect" );

    for ( self._id_106AF = 0; self._id_106AF < 2; self._id_106AF++ )
        self waittill( "voteToKick" );

    _func_012D( self getentitynumber(), "EXE/PLAYERKICKED_TEAMKILLS" );
}

_id_5937()
{
    wait 1.0;
    self notify( "voteToKick" );
    wait 3.0;
    self notify( "voteToKick" );
    wait 2.0;
    self notify( "voteToKick" );
}

_id_F375( var_0 )
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "spawned" );
    self notify( "distFromSpawnTracking" );
    self endon( "distFromSpawnTracking" );
    var_1 = var_0;

    if ( !_id_07A8::_id_609F( "prematch_done" ) )
    {
        _id_07A8::_id_60A3( "prematch_done" );
        var_1 = self._id_02EA;
    }

    var_2 = 0;
    var_3 = 0;

    for (;;)
    {
        var_4 = _id_077B::_id_108A8( 5.0, "death", "vehicle_enter", "vehicle_change_seat", "vehicle_exit" );

        if ( var_4 == "vehicle_exit" && !isdefined( self._id_90AC ) )
            continue;

        if ( !isdefined( self._id_0309["totalDistTraveled"] ) )
            _id_0A7B::_id_823D( "totalDistTraveled" );

        if ( !isdefined( self._id_0309["totalDistTraveledAFK"] ) )
            _id_0A7B::_id_823D( "totalDistTraveledAFK" );

        var_5 = distance( var_1, self._id_02EA );
        _id_0A7B::_id_7D93( "totalDistTraveled", var_5 );
        _id_0A7B::_id_7D93( "totalDistTraveledAFK", var_5 );

        if ( var_4 == "vehicle_exit" || isdefined( self._id_FFF1 ) )
            _id_0A7B::_id_7D93( "distanceTraveledInVehicle", var_5 );

        if ( var_4 == "vehicle_enter" )
        {
            var_3 = _id_09BA::_id_101E6( self );
            self._id_90AC = gettime();
        }

        if ( var_4 == "vehicle_change_seat" )
            var_3 = _id_09BA::_id_101E6( self );

        if ( var_2 != var_3 || var_4 == "vehicle_exit" )
        {
            var_6 = self._id_90AC;
            var_7 = ( gettime() - var_6 ) / 1000;

            if ( var_2 )
                _id_0A7B::_id_7D93( "timeSpentAsDriver", var_7 );
            else
                _id_0A7B::_id_7D93( "timeSpentAsPassenger", var_7 );
        }

        if ( var_4 == "vehicle_enter" || var_4 == "vehicle_change_seat" )
            var_2 = var_3;

        if ( var_4 == "vehicle_change_seat" )
            self._id_90AC = gettime();

        var_1 = self._id_02EA;

        if ( _id_0A69::_id_8744() )
        {
            if ( self._id_0309["totalDistTraveledAFK"] > 50 )
            {
                self._id_0309["distTrackingPassed"] = 1;
                self._id_0309["afkRounds"] = 0;
            }
        }
        else if ( !istrue( self._id_0309["distTrackingPassed"] ) )
        {
            if ( self._id_0309["totalDistTraveledAFK"] > 300 )
                self._id_0309["distTrackingPassed"] = 1;
        }
        else
        {
            var_8 = _id_0A69::_id_6A43() != "br";

            if ( var_8 )
            {
                var_9 = scripts\mp\gamelogic::_id_E75E( "round", "timePlayed", 0 );

                if ( var_9 - self._id_0309["afkResetTime"] > 240 )
                {
                    self._id_0309["afkResetTime"] = var_9;
                    self._id_0309["distTrackingPassed"] = undefined;
                    self._id_0309["totalDistTraveledAFK"] = undefined;
                }
            }
        }

        _id_0A7B::_id_7D93( "averageAltitude", self._id_02EA[2] );
        _id_0A7B::_id_7D93( "averageAltitudeCount", 1 );
    }
}

_id_81F2()
{
    if ( !isdefined( self._id_0309["deaths"] ) )
    {
        _id_0A7B::_id_823D( "deaths" );
        scripts\mp\gamelogic::_id_E76D( "round", "deaths", 0 );
    }

    self._id_0146 = _id_0A7B::_id_6C0A( "deaths" );
    _id_0A7B::_id_81F1( "deaths" );

    if ( !isdefined( self._id_0309["score"] ) )
    {
        _id_0A7B::_id_823D( "score" );
        scripts\mp\gamelogic::_id_E76D( "round", "score", 0 );
    }

    self._id_0369 = _id_0A7B::_id_6C0A( "score" );
    _id_0A7B::_id_81F1( "score" );

    if ( !isdefined( self._id_0309["kills"] ) )
    {
        _id_0A7B::_id_823D( "kills" );
        scripts\mp\gamelogic::_id_E76D( "round", "kills", 0 );
    }

    self._id_024B = _id_0A7B::_id_6C0A( "kills" );
    _id_0A7B::_id_81F1( "kills" );
}

_id_8255()
{
    _id_07DA::_id_8241();
    scripts\mp\gamelogic::_id_813D();

    if ( !isdefined( self._id_911D ) )
        self._id_911D = [];

    _id_81F2();

    if ( !isdefined( self._id_0309["suicides"] ) )
        _id_0A7B::_id_823D( "suicides" );

    _id_0A7B::_id_81F1( "suicides" );

    if ( !isdefined( self._id_0309["headshots"] ) )
        _id_0A7B::_id_823D( "headshots" );

    _id_0A7B::_id_81F1( "headshots" );

    if ( !isdefined( self._id_0309["executions"] ) )
        _id_0A7B::_id_823D( "executions" );

    if ( !isdefined( self._id_0309["assists"] ) )
    {
        _id_0A7B::_id_823D( "assists" );
        scripts\mp\gamelogic::_id_E76D( "round", "assists", 0 );
    }

    self._id_006A = _id_0A7B::_id_6C0A( "assists" );
    _id_0A7B::_id_81F1( "assists" );

    if ( !isdefined( self._id_0309["captures"] ) )
    {
        _id_0A7B::_id_823D( "captures" );
        scripts\mp\gamelogic::_id_E76D( "round", "captures", 0 );
    }

    _id_0A7B::_id_81F1( "captures" );

    if ( !isdefined( self._id_0309["returns"] ) )
    {
        _id_0A7B::_id_823D( "returns" );
        scripts\mp\gamelogic::_id_E76D( "round", "returns", 0 );
    }

    _id_0A7B::_id_81F1( "returns" );

    if ( !isdefined( self._id_0309["defends"] ) )
    {
        _id_0A7B::_id_823D( "defends" );
        scripts\mp\gamelogic::_id_E76D( "round", "defends", 0 );
    }

    _id_0A7B::_id_81F1( "defends" );

    if ( !isdefined( self._id_0309["assaults"] ) )
    {
        _id_0A7B::_id_823D( "assaults" );
        scripts\mp\gamelogic::_id_E76D( "round", "assaults", 0 );
    }

    _id_0A7B::_id_81F1( "assaults" );

    if ( !isdefined( self._id_0309["plants"] ) )
    {
        _id_0A7B::_id_823D( "plants" );
        scripts\mp\gamelogic::_id_E76D( "round", "plants", 0 );
    }

    _id_0A7B::_id_81F1( "plants" );

    if ( !isdefined( self._id_0309["defuses"] ) )
    {
        _id_0A7B::_id_823D( "defuses" );
        scripts\mp\gamelogic::_id_E76D( "round", "defuses", 0 );
    }

    _id_0A7B::_id_81F1( "defuses" );

    if ( !isdefined( self._id_0309["destructions"] ) )
    {
        _id_0A7B::_id_823D( "destructions" );
        scripts\mp\gamelogic::_id_E76D( "round", "destructions", 0 );
    }

    _id_0A7B::_id_81F1( "destructions" );

    if ( !isdefined( self._id_0309["confirmed"] ) )
    {
        _id_0A7B::_id_823D( "confirmed" );
        scripts\mp\gamelogic::_id_E76D( "round", "confirmed", 0 );
    }

    _id_0A7B::_id_81F1( "confirmed" );

    if ( !isdefined( self._id_0309["denied"] ) )
    {
        _id_0A7B::_id_823D( "denied" );
        scripts\mp\gamelogic::_id_E76D( "round", "denied", 0 );
    }

    _id_0A7B::_id_81F1( "denied" );

    if ( !isdefined( self._id_0309["rescues"] ) )
    {
        _id_0A7B::_id_823D( "rescues" );
        scripts\mp\gamelogic::_id_E76D( "round", "rescues", 0 );
    }

    _id_0A7B::_id_81F1( "rescues" );

    if ( !isdefined( self._id_0309["touchdowns"] ) )
    {
        _id_0A7B::_id_823D( "touchdowns" );
        scripts\mp\gamelogic::_id_E76D( "round", "touchdowns", 0 );
    }

    _id_0A7B::_id_81F1( "touchdowns" );

    if ( !isdefined( self._id_0309["fieldgoals"] ) )
    {
        _id_0A7B::_id_823D( "fieldgoals" );
        scripts\mp\gamelogic::_id_E76D( "round", "fieldgoals", 0 );
    }

    _id_0A7B::_id_81F1( "fieldgoals" );

    if ( !isdefined( self._id_0309["killChains"] ) )
    {
        _id_0A7B::_id_823D( "killChains" );
        scripts\mp\gamelogic::_id_E76D( "round", "killChains", 0 );
    }

    _id_0A7B::_id_81F1( "killChains" );

    if ( !isdefined( self._id_0309["killsAsSurvivor"] ) )
    {
        _id_0A7B::_id_823D( "killsAsSurvivor" );
        scripts\mp\gamelogic::_id_E76D( "round", "killsAsSurvivor", 0 );
    }

    _id_0A7B::_id_81F1( "killsAsSurvivor" );

    if ( !isdefined( self._id_0309["killsAsInfected"] ) )
    {
        _id_0A7B::_id_823D( "killsAsInfected" );
        scripts\mp\gamelogic::_id_E76D( "round", "killsAsInfected", 0 );
    }

    _id_0A7B::_id_81F1( "killsAsInfected" );

    if ( !isdefined( self._id_0309["teamkills"] ) )
        _id_0A7B::_id_823D( "teamkills" );

    _id_0A7B::_id_81F1( "teamkills" );

    if ( !isdefined( self._id_0309["extrascore0"] ) )
        _id_0A7B::_id_823D( "extrascore0" );

    _id_0A7B::_id_81F1( "extrascore0" );

    if ( !isdefined( self._id_0309["extrascore1"] ) )
        _id_0A7B::_id_823D( "extrascore1" );

    _id_0A7B::_id_81F1( "extrascore1" );

    if ( !isdefined( self._id_0309["stabs"] ) )
    {
        _id_0A7B::_id_823D( "stabs" );
        scripts\mp\gamelogic::_id_E76D( "round", "stabs", 0 );
    }

    _id_0A7B::_id_81F1( "stabs" );

    if ( !isdefined( self._id_0309["setbacks"] ) )
    {
        _id_0A7B::_id_823D( "setbacks" );
        scripts\mp\gamelogic::_id_E76D( "round", "setbacks", 0 );
    }

    _id_0A7B::_id_81F1( "setbacks" );

    if ( !isdefined( self._id_0309["objTime"] ) )
    {
        _id_0A7B::_id_823D( "objTime" );
        scripts\mp\gamelogic::_id_E76D( "round", "objTime", 0 );
    }

    _id_0A7B::_id_81F1( "objTime" );

    if ( !isdefined( self._id_0309["gamemodeScore"] ) )
    {
        _id_0A7B::_id_823D( "gamemodeScore" );
        scripts\mp\gamelogic::_id_E76D( "round", "gamemodeScore", 0 );
    }

    _id_0A7B::_id_81F1( "gamemodeScore" );

    if ( !isdefined( self._id_0309["damage"] ) )
    {
        _id_0A7B::_id_823D( "damage" );
        scripts\mp\gamelogic::_id_E76D( "round", "damage", 0 );
    }

    _id_0A7B::_id_81F1( "damage" );

    if ( !isdefined( self._id_0309["supersEarned"] ) )
        _id_0A7B::_id_823D( "supersEarned" );

    _id_0A7B::_id_81F1( "supersEarned" );

    if ( !isdefined( self._id_0309["downs"] ) )
    {
        _id_0A7B::_id_823D( "downs" );
        scripts\mp\gamelogic::_id_E76D( "round", "downs", 0 );
    }

    _id_0A7B::_id_81F1( "downs" );

    if ( !isdefined( self._id_0309["contracts"] ) )
    {
        _id_0A7B::_id_823D( "contracts" );
        scripts\mp\gamelogic::_id_E76D( "round", "contracts", 0 );
    }

    _id_0A7B::_id_81F1( "contracts" );

    if ( !isdefined( self._id_0309["wins"] ) )
        _id_0A7B::_id_823D( "wins" );

    _id_0A7B::_id_81F1( "wins" );

    if ( !isdefined( self._id_0309["topFive"] ) )
        _id_0A7B::_id_823D( "topFive" );

    _id_0A7B::_id_81F1( "topFive" );

    if ( !isdefined( self._id_0309["topTen"] ) )
        _id_0A7B::_id_823D( "topTen" );

    _id_0A7B::_id_81F1( "topTen" );

    if ( !isdefined( self._id_0309["topTwentyFive"] ) )
        _id_0A7B::_id_823D( "topTwentyFive" );

    _id_0A7B::_id_81F1( "topTwentyFive" );

    if ( !isdefined( self._id_0309["gamesPlayed"] ) )
        _id_0A7B::_id_823D( "gamesPlayed" );

    _id_0A7B::_id_81F1( "gamesPlayed" );

    if ( !isdefined( self._id_0309["cash"] ) )
        _id_0A7B::_id_823D( "cash" );

    _id_0A7B::_id_81F1( "cash" );

    if ( !isdefined( self._id_0309["teamKillPunish"] ) )
        self._id_0309["teamKillPunish"] = 0;

    _id_0A7B::_id_823D( "longestStreak" );
    _id_0A7B::_id_81F1( "longestStreak" );
    self._id_0309["lives"] = _id_0A69::_id_6A46();
    scripts\mp\gamelogic::_id_E76D( "round", "killStreak", 0 );
    scripts\mp\gamelogic::_id_E76D( "round", "loss", 0 );
    scripts\mp\gamelogic::_id_E76D( "round", "win", 0 );
    scripts\mp\gamelogic::_id_E76D( "round", "scoreboardType", "none" );
    _id_0A7B::_id_81F1( "killStreak" );
    _id_0A7B::_id_81F1( "loss" );
    _id_0A7B::_id_81F1( "win" );
    _id_0A7B::_id_823D( "damageTaken" );
}

_id_114E( var_0 )
{
    thread _id_0A7C::_id_10EB( self, self._id_045B, var_0 );
    [[ level._id_FC72 ]]();
}

_id_C4AF()
{
    _id_0A7C::_id_C4FB( self, self._id_045B );
}

_id_112E()
{
    var_0 = self._id_045B;

    if ( !( isdefined( self._id_161B ) && self._id_161B ) )
    {
        _id_0A7C::_id_9FFD( var_0, "hasSpawned", 1 );
        _id_7DCD( var_0 );
    }

    self._id_161B = undefined;
    var_1 = 0;

    foreach ( var_3 in level._id_EF86 )
        var_1 = var_1 + _id_0A7C::_id_6DAC( var_3, "aliveCount" );

    if ( var_1 > level._id_9C7A )
        level._id_9C7A = var_1;
}

_id_7DCD( var_0, var_1 )
{
    _id_0A7C::_id_114F( self, var_0, var_1 );
    [[ level._id_FC72 ]]();
}

_id_C496( var_0 )
{
    var_1 = self._id_0309["lives"];
    var_2 = _id_0A69::_id_6A46() != 0 && var_1 == 0;
    self notify( "remove_from_alive_count" );
    var_3 = self._id_045B;

    if ( isdefined( self._id_EC30 ) && self._id_EC30 && isdefined( self._id_8BC1 ) && self._id_8BC1 == self._id_045B )
        var_3 = self._id_9157;

    if ( isdefined( var_0 ) )
        _id_C461();
    else if ( isdefined( self._id_EC30 ) )
    {
        if ( !level._id_7E95 || self._id_7539 )
        {
            _id_0A7C::_id_9FFD( var_3, "hasSpawned", -1 );

            if ( var_1 )
                self._id_0309["lives"]--;
        }
    }

    _id_4533( var_3, var_2 );
}

_id_4533( var_0, var_1 )
{
    _id_0A7C::_id_C4B0( self, var_0, var_1 );
    [[ level._id_FC72 ]]();
}

_id_113A()
{
    _id_0A7C::_id_9FFD( self._id_045B, "livesCount", self._id_0309["lives"] );
}

_id_C4A1()
{
    _id_0A7C::_id_D704( self._id_045B, "livesCount", int( _func_0147( 0, _id_0A7C::_id_6DAC( self._id_045B, "livesCount" ) - 1 ) ) );
}

_id_C461()
{
    _id_0A7C::_id_D704( self._id_045B, "livesCount", int( _func_0147( 0, _id_0A7C::_id_6DAC( self._id_045B, "livesCount" ) - self._id_0309["lives"] ) ) );
}

_id_C644()
{
    if ( isdefined( level._id_C643 ) )
        [[ level._id_C643 ]]();

    self _meth_82F6( "ui_objective_state", 0 );
    self _meth_82F6( "ui_securing", 0 );
    self _meth_82F6( "ui_reviver_id", -1 );
    self _meth_82F6( "ui_killcam_end_milliseconds", 0 );
    self _meth_82F6( "ui_edge_glow", 0 );
    self _meth_82F6( "ui_edge_glow_secondary", 0 );
    self _meth_82F6( "ui_cranked_bomb_timer_end_milliseconds", 0 );
    self _meth_82F6( "ui_life_kill_count", 0 );
    self _meth_82F6( "ui_is_laststand", 0 );
}

_id_C641()
{
    _id_C644();
    self _meth_82F4( "ui_eyes_on_end_milliseconds", 0 );
    self _meth_82F6( "ui_match_status_hint_text", -1 );
    self _meth_82F6( "post_game_state", 0 );

    if ( _id_07A8::_id_609F( "prematch_done" ) )
        self _meth_82F6( "ui_match_in_progress", 1 );
    else
        self _meth_82F6( "ui_match_in_progress", 0 );
}

_id_C642()
{
    _id_C644();
    self _meth_82F4( "ui_eyes_on_end_milliseconds", 0 );
}

_id_3946()
{
    if ( _func_0107( self ) )
        return;

    if ( isdefined( level._id_A8D5 ) )
    {
        foreach ( var_1 in level._id_A8D5 )
        {
            if ( isdefined( var_1._id_A8F5 ) )
                _id_07D0::_id_A8BC( var_1._id_A8F5, self, var_1._id_DCCE );
        }
    }

    if ( isdefined( level._id_F932 ) )
    {
        foreach ( var_1 in level._id_F932 )
        {
            if ( isdefined( var_1._id_A8F5 ) )
                _id_07D0::_id_A8BC( var_1._id_A8F5, self, var_1._id_DCCE );
        }
    }
}

_id_10C11()
{
    self endon( "death_or_disconnect" );
    self._id_EEA2 = [];

    for (;;)
    {
        var_0 = ( self._id_02EA[0], self._id_02EA[1], self._id_02EA[2] + 64 );
        var_1 = self getplayerangles();
        var_2 = anglestoforward( var_1 );
        var_3 = var_0 + var_2 * 10000;
        var_4 = _id_077A::_id_0B4C( var_0, var_3, 1, self, 0, 0, 0, 0, 0 );
        var_5 = var_4["entity"];

        if ( isdefined( var_5 ) && _func_0117( var_5 ) && var_5._id_045B != self._id_045B )
        {
            if ( isdefined( var_5 ) )
                _id_FD50( "ui_target_health", var_5._id_01FF );

            if ( isdefined( var_5 ) )
                _id_FD50( "ui_target_max_health", var_5._id_027F );

            if ( isdefined( var_5 ) )
                _id_FD50( "ui_target_entity_num", var_5 getentitynumber() );
        }
        else
            _id_FD50( "ui_target_entity_num", -1 );

        wait 0.1;
    }
}

_id_FD50( var_0, var_1 )
{
    waitframe();

    if ( !isdefined( self ) )
        return;

    if ( !isdefined( var_1 ) )
        return;

    if ( !isdefined( self._id_EEA2[var_0] ) || var_1 != self._id_EEA2[var_0] )
    {
        self _meth_82F6( var_0, var_1 );
        self._id_EEA2[var_0] = var_1;
    }
}

_id_DCAC()
{
    if ( self._id_7598 )
        return;

    if ( !_id_DCBF() )
        return;

    if ( _id_07A8::_id_609F( "prematch_done" ) )
        return;

    _id_07A8::_id_60A3( "prematch_done" );
    self endon( "disconnect" );
    wait 1.0;

    if ( !isdefined( self ) )
        return;

    if ( !isdefined( self._id_0309["team"] ) )
        return;

    var_0 = self._id_0309["team"];
    var_1 = _id_0A69::_id_6B9F( var_0 );

    if ( isdefined( var_1 ) )
    {
        var_2 = 0;

        if ( game["defenders"] == var_0 )
            var_2 = 1;

        self _meth_82F6( "ui_objective_text", var_2 );
        wait 6;
        self _meth_82F6( "ui_objective_text", -1 );
    }
}

_id_DCBF()
{
    var_0 = _id_0A69::_id_6A43();

    switch ( var_0 )
    {
        case "arena_evo":
        case "arena":
            if ( isdefined( game["roundsPlayed"] ) && game["roundsPlayed"] > 0 )
                return 0;

            break;
        default:
            break;
    }

    return 1;
}

_id_F73A()
{
    if ( _id_0A74::_id_1634() || _id_0A69::_id_6A43() == "br" )
        return;

    if ( !istrue( self._id_DCF5 ) && !scripts\mp\tac_ops\hostage_utility::_id_0BF6( "specialty_always_minimap" ) )
        _id_0A74::_id_78ED( 1 );

    self._id_DCF5 = 0;
}

_id_81E4()
{
    self._id_60C1 = _id_077B::_id_864F();
}

_id_FC8D()
{
    var_0 = _id_077B::_id_864F();

    if ( self._id_60C1 != var_0 )
    {
        self notify( "input_type_changed", var_0 );
        self._id_60C1 = var_0;
    }
}

_id_FC4D()
{
    self endon( "disconnect" );
    level endon( "game_ended" );

    for (;;)
    {
        foreach ( var_1 in level._id_B758 )
        {
            if ( !isdefined( var_1 ) )
                continue;

            if ( !_id_0A74::_id_89D3( var_1 ) )
                continue;

            var_1 _id_08E2::_id_B651();
        }

        wait 0.1;
    }
}

_id_FD05()
{
    var_0 = 100;
    var_1 = 700;
    var_2 = var_1 - var_0;
    var_3 = 0;
    var_4 = 10;

    for (;;)
    {
        foreach ( var_6 in level._id_B758 )
        {
            if ( !isdefined( var_6 ) )
                continue;

            if ( !_id_0A74::_id_89D3( var_6 ) )
                continue;

            if ( istrue( var_6._id_9A50 ) )
                continue;

            if ( isdefined( var_6._id_FFF1 ) )
                var_7 = clamp( _func_0130( var_6._id_FFF1 _meth_8430() ), var_0, var_1 );
            else
                var_7 = clamp( _func_0130( var_6 getvelocity() ), var_0, var_1 );

            var_8 = ( var_7 - var_0 ) / var_2;
            var_8 = var_8 * 10;
            var_8 = int( var_8 );

            if ( !isdefined( var_6._id_10E2F ) || var_6._id_10E2F != var_8 )
            {
                switch ( var_8 )
                {
                    case 0:
                        var_6 _meth_8373( "wind", "0", 0 );
                        break;
                    case 1:
                        var_6 _meth_8373( "wind", "10", 0 );
                        break;
                    case 2:
                        var_6 _meth_8373( "wind", "20", 0 );
                        break;
                    case 3:
                        var_6 _meth_8373( "wind", "30", 0 );
                        break;
                    case 4:
                        var_6 _meth_8373( "wind", "40", 0 );
                        break;
                    case 5:
                        var_6 _meth_8373( "wind", "50", 0 );
                        break;
                    case 6:
                        var_6 _meth_8373( "wind", "60", 0 );
                        break;
                    case 7:
                        var_6 _meth_8373( "wind", "70", 0 );
                        break;
                    case 8:
                        var_6 _meth_8373( "wind", "80", 0 );
                        break;
                    case 9:
                        var_6 _meth_8373( "wind", "90", 0 );
                        break;
                    case 10:
                        var_6 _meth_8373( "wind", "100", 0 );
                        break;
                }
            }

            var_6._id_10E2F = var_8;
            var_3++;

            if ( var_3 == var_4 )
            {
                waitframe();
                var_3 = 0;
            }
        }

        wait 0.1;
    }
}

_id_D489( var_0 )
{
    self._id_24A0 = var_0;
    self _meth_8773( var_0 );
}

_id_68EB()
{
    return istrue( self._id_24A0 ) || istrue( self.isroundbased );
}

stage_lighting()
{
    var_0 = getentarray( "lgts_infil", "targetname" );
    var_1 = getentarray( "lgt_winner", "targetname" );

    if ( isdefined( var_0 ) )
    {
        foreach ( var_3 in var_0 )
            var_3._id_AC74 = var_3 _meth_8146();

        foreach ( var_3 in var_0 )
            var_3 _meth_8337( 0 );

        thread stage_lighting_infil_manage( var_0 );
    }

    if ( isdefined( var_1 ) )
    {
        foreach ( var_3 in var_1 )
            var_3._id_AC74 = var_3 _meth_8146();

        foreach ( var_3 in var_1 )
            var_3 _meth_8337( 0 );

        thread stage_lighting_winner_manage( var_1 );
    }
}

stage_lighting_infil_manage( var_0 )
{
    level waittill( "infil_start" );

    foreach ( var_2 in var_0 )
        var_2 _meth_8337( var_2._id_AC74 );
}

stage_lighting_winner_manage( var_0 )
{
    level waittill( "winner_start" );

    foreach ( var_2 in var_0 )
        var_2 _meth_8337( var_2._id_AC74 );
}

sun_flare_vfx()
{
    wait 10;

    if ( isdefined( level.sunvfx ) )
        _id_077B::_id_579A( level.sunvfx );
}
