// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_021D()
{
    if ( _id_099D::_id_8A10( "airdrop", "init" ) )
        [[ _id_099D::_id_6D05( "airdrop", "init" ) ]]();

    level._id_0BA3["airdrop_crate_impact"] = _func_0139( "vfx/iw8_mp/killstreak/vfx_carepkg_landing_dust.vfx" );
    level._id_0BA3["airdrop_crate_capture"] = _func_0139( "vfx/iw8_mp/killstreak/vfx_carepackage_base_fx_fade.vfx" );
    level._id_0BA3["airdrop_crate_ui"] = _func_0139( "vfx/s4/test/test_rtt_diegetic_ui_01.vfx" );
    level._id_0BA3["airdrop_death"] = _func_0139( "vfx/s4/explosion/vfx_airdrop_explosion.vfx" );
    level._id_3247 = getentarray( "carepackage_drop_area", "targetname" );
    _id_81E8();
    _id_818E();
    _id_8158();

    if ( _id_099D::_id_8A10( "airdrop", "airdropMultipleInit" ) )
        [[ _id_099D::_id_6D05( "airdrop", "airdropMultipleInit" ) ]]();
}

_id_81E8()
{

}

_id_818E()
{
    level._id_957C = [];

    if ( _id_099D::_id_8A10( "airdrop", "registerScoreInfo" ) )
        [[ _id_099D::_id_6D05( "airdrop", "registerScoreInfo" ) ]]();
}

_id_8158()
{
    var_0 = _func_020F();
    var_0._id_3B50 = [];
    var_0._id_3E79 = [];
    var_0._id_FDB1 = [];
    level._id_3E63 = var_0;
    level._id_A2A2 = _id_06BB::_id_1507;
    level._id_3E63._id_A1AD = getent( "care_package_col", "targetname" );

    if ( _id_099D::_id_8A10( "airdrop", "registerActionSet" ) )
        [[ _id_099D::_id_6D05( "airdrop", "registerActionSet" ) ]]();

    var_2 = "mp";

    if ( _id_099D::_id_8A10( "game", "getGameType" ) )
        var_2 = [[ _id_099D::_id_6D05( "game", "getGameType" ) ]]();

    switch ( var_2 )
    {
        case "cp_wave_sv":
        case "cp_survival":
            if ( _id_099D::_id_8A10( "airdrop", "getGameModeSpecificCrateData" ) )
                [[ _id_099D::_id_6D05( "airdrop", "getGameModeSpecificCrateData" ) ]]();
        case "br":
            _id_8130();
            _id_8131();
            _id_812F();
            _id_8132();
        case "arm":
            _id_811E();
            _id_81E9();
            _id_8130();
        case "base":
            _id_812C();
            _id_81E9();
        case "grnd":
            _id_816D();
        default:
            _id_81E9();
    }

    _id_8159();

    if ( _id_099D::_id_8A10( "game", "registerPlayerFrameUpdateCallback" ) )
        [[ _id_099D::_id_6D05( "game", "registerPlayerFrameUpdateCallback" ) ]]( ::_id_F3F6 );

    thread _id_10A88();
}

_id_6AE1( var_0 )
{
    var_1 = level._id_3E63._id_3B50[var_0];

    if ( !isdefined( var_1 ) )
    {
        var_1 = _id_69DB();
        level._id_3E63._id_3B50[var_0] = var_1;
    }

    return var_1;
}

_id_69DB()
{
    var_0 = _func_020F();
    var_0._id_5F99 = "vm_equip_gen_care_package_00";
    var_0._id_5400 = "vm_equip_gen_care_package_00";
    var_0._id_506A = "vm_equip_gen_care_package_00";
    var_0._id_739D = 27.5;
    var_0._id_A1AD = _id_69B6();
    var_0._id_A90B = _func_0370();
    var_0._id_F221 = 90;
    var_0._id_75DA = 20;
    var_0._id_75D3 = 10000;
    var_0._id_75D9 = 400;
    var_0._id_9F0C = "icon_minimap_carepackage";
    var_0._id_FED9 = "tag_use";
    var_0._id_FEAE = 128;
    var_0._id_2B76 = 30625;
    var_0._id_FE70 = 360;
    var_0._id_049F = 0;
    var_0._id_ADA0 = 0.5;
    var_0._id_AC8C = 3;
    var_0._id_5FA0 = 0;
    var_0._id_A3D3 = ( 30, 10, 64 );
    var_0._id_A3D5 = 64;
    var_0._id_4327 = 1000;
    var_0._id_432A = 128;
    var_0._id_0EBE = undefined;
    var_0._id_4369 = undefined;
    var_0._id_3201 = undefined;
    var_0._id_C57E = undefined;
    var_0._id_4820 = undefined;
    var_0._id_483C = 1;
    var_0._id_AAAB = 0;
    var_0._id_4845 = _id_69B1();
    var_0._id_4846 = _id_69B2();
    var_0._id_3211 = _id_69AF();
    var_0._id_3212 = _id_69B0();
    var_0._id_320E = &"KILLSTREAKS_HINTS/CRATE_PICKUP";
    var_0._id_C581 = &"KILLSTREAKS_HINTS/UAV_REROLL";
    var_0._id_75CE = "hud_icon_head_killstreak_carepackage";
    var_0._id_EB9C = 0;
    var_0._id_EB9B = 1;
    var_0._id_EB9A = 1;
    return var_0;
}

_id_7562( var_0 )
{
    return isdefined( level._id_3E63._id_3B50[var_0] );
}

_id_3F95( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    var_9 = _id_6AE1( var_2 );

    if ( var_9._id_EB9B )
    {

    }

    if ( var_9._id_EB9C )
    {

    }

    var_10 = _func_0205( "script_model", var_3 );
    var_10._id_0054 = var_4;

    if ( !istrue( var_7 ) && var_2 != "battle_royale_c130_loot" || var_2 != "battle_royale_loadout" )
    {
        if ( _id_099D::_id_8A10( "entity", "touchingBadTrigger" ) )
        {
            if ( var_10 [[ _id_099D::_id_6D05( "entity", "touchingBadTrigger" ) ]]() )
            {
                var_10 _meth_809A();
                return undefined;
            }
        }
    }

    var_10._id_02F2 = var_0;
    var_10._id_045B = var_1;
    var_10._id_A90B = var_9._id_A90B;
    var_10._id_3E7E = var_2;
    var_10._id_FE90 = undefined;
    var_10._id_A3D2 = undefined;
    var_10._id_75D8 = undefined;
    var_10._id_9F0F = undefined;
    var_10._id_4328 = undefined;
    var_10._id_A3D4 = undefined;
    var_10._id_4802 = var_5;
    var_10._id_75D0 = 0;
    var_10._id_9F0E = 0;
    var_10._id_7570 = istrue( var_6 );
    var_10._id_B03C = 0;
    var_10._id_87E1 = 0;
    var_10._id_432F = var_8;
    var_10._id_75CE = var_9._id_75CE;
    var_10._id_9F0C = var_9._id_9F0C;
    var_10._id_320E = var_9._id_320E;
    var_10._id_C581 = var_9._id_C581;
    var_10._id_EB9C = var_9._id_EB9C;
    var_10 setmode( var_9._id_506A );
    var_10 hide();
    var_10 setneargoalnotifydist( 1 );
    var_10 _meth_82F0( 0 );
    var_10 _meth_8225();
    var_10 _meth_86FB( "killstreak" );
    var_10 _meth_884D( 3, var_1 );

    if ( level._id_EF62 )
        var_10 _meth_8703( var_10._id_045B );
    else
        var_10 _meth_8703( var_10._id_02F2 );

    var_11 = undefined;

    if ( isdefined( var_9._id_5F99 ) )
    {
        var_11 = _func_0205( "script_model", var_3 );
        var_11._id_0054 = var_4;
        var_11._id_3E4B = var_10;
        var_11 setmode( var_9._id_5F99 );
        var_11 _meth_820B( var_10 );
        var_10._id_3555 = [ var_11 ];
    }
    else
        var_11 = var_10;

    var_10._id_5F99 = var_11;
    var_12 = undefined;

    if ( isdefined( var_9._id_5400 ) )
    {
        if ( level._id_EF62 )
        {

        }
        else
        {

        }

        var_12 = _func_0205( "script_model", var_3 );
        var_12._id_0054 = var_4;
        var_12._id_3E63 = var_10;
        var_12 setmode( var_9._id_5400 );
        var_12 _meth_820B( var_10 );
    }

    var_10._id_5400 = var_12;

    if ( isdefined( var_10._id_5400 ) )
        var_10 thread _id_10C26();

    var_13 = undefined;

    if ( !var_10._id_7570 )
    {
        if ( _id_099D::_id_8A10( "game", "getGameType" ) )
        {
            if ( [[ _id_099D::_id_6D05( "game", "getGameType" ) ]]() != "br" )
            {
                var_13 = _func_0205( "script_model", var_3 + ( 0, 0, 300 ) );
                var_13 setscriptablepartstate( "explosive" );

                if ( isdefined( self._id_CBC3 ) )
                {
                    if ( var_7 )
                        var_13 thread _id_9835( var_10, ( 0, 0, 0 ) );
                    else
                        var_13 _meth_820B( var_10 );
                }
            }
        }
    }

    if ( isdefined( var_10._id_02F2 ) )
        var_10._id_02F2._id_883D = 1;

    var_10._id_8D49 = var_13;
    var_10 _id_3FF7();
    var_10 _id_1138();

    if ( !_id_077B::_id_85A4( level._id_036A, "mp_bm_tut" ) )
        var_10 thread _id_10AB6();

    if ( var_10._id_7570 )
        var_10 _id_0EC0();
    else if ( var_7 )
        var_10 _id_3E77();

    return var_10;
}

_id_0EC0()
{
    _id_0EBF( 1 );
}

_id_0EBF( var_0 )
{
    self notify( "activateCrate" );

    if ( istrue( self._id_483B ) )
    {
        thread _id_4822();
        return;
    }

    _id_0B80();
    self notify( "crate_dropped" );

    if ( istrue( self._id_10811 ) )
        self waittill( "objective_activate" );

    if ( istrue( var_0 ) && self._id_3E7E != "battle_royale_loadout" && !istrue( self._id_DDB1 ) )
        _id_3FF0();

    var_1 = _func_0205( "script_model", self gettagorigin( "tag_use" ) );
    var_1 setmode( "tag_origin" );
    var_1._id_045B = self._id_045B;
    var_1._id_75CE = self._id_75CE;
    var_1._id_4AE5 = self._id_4AE5;
    var_1._id_75D8 = self._id_75D8;
    var_1._id_3E7E = self._id_3E7E;
    var_1._id_02F2 = self._id_02F2;
    var_1 _id_0B7F();
    self._id_ED68 = var_1;
    _id_99CD();
    var_2 = _id_6AE1( self._id_3E7E );

    if ( isdefined( var_2._id_0EBE ) )
        self thread [[ var_2._id_0EBE ]]( var_0 );
}

_id_436A( var_0 )
{
    if ( istrue( var_0 ) )
        _id_4838();

    if ( isdefined( self._id_ED68 ) )
        self._id_ED68 _id_0B91();

    _id_99CC();
    var_1 = _id_6AE1( self._id_3E7E );

    if ( isdefined( var_1._id_4369 ) )
        self thread [[ var_1._id_4369 ]]( var_0 );
}

_id_3204( var_0 )
{
    var_1 = _id_6AE1( self._id_3E7E );

    if ( isdefined( self._id_02F2 ) && istrue( self._id_02F2._id_883D ) )
        self._id_02F2._id_883D = 0;

    if ( isdefined( var_1._id_3201 ) )
        self thread [[ var_1._id_3201 ]]( var_0 );

    if ( var_1._id_483C )
    {
        var_2 = 0;
        thread _id_0823::carepackage_open( var_0, self._id_02F2 );

        if ( isdefined( var_1._id_3211 ) )
        {
            self thread [[ var_1._id_3211 ]]( self._id_5F99 );

            if ( isdefined( self._id_5400 ) )
                self thread [[ var_1._id_3211 ]]( self._id_5400 );

            var_2 = var_1._id_3212;
        }

        thread _id_473F( var_2 );
    }
}

_id_4822( var_0 )
{
    if ( istrue( self._id_87E1 ) )
        return;

    if ( !isdefined( var_0 ) )
    {
        if ( isdefined( self._id_CBC3 ) )
        {
            if ( isdefined( self._id_1879 ) )
            {
                if ( gettime() >= self._id_1879 )
                {
                    self._id_483B = 1;
                    return;
                }
                else
                    var_0 = 1;
            }
        }
        else if ( istrue( self._id_B03C ) )
        {
            if ( !istrue( self._id_B03F ) )
            {
                self._id_483B = 1;
                return;
            }
        }
    }

    self._id_483B = undefined;
    var_1 = _id_6AE1( self._id_3E7E );

    if ( isdefined( self._id_02F2 ) && istrue( self._id_02F2._id_883D ) )
        self._id_02F2._id_883D = 0;

    if ( isdefined( var_1._id_4820 ) )
        self thread [[ var_1._id_4820 ]]( var_0 );

    if ( !istrue( var_0 ) )
    {
        var_2 = undefined;

        if ( !istrue( self._id_B03C ) || !istrue( self._id_B03F ) )
        {
            if ( isdefined( var_1._id_4845 ) )
            {
                self thread [[ var_1._id_4845 ]]( self._id_5F99 );

                if ( isdefined( self._id_5400 ) )
                    self thread [[ var_1._id_4845 ]]( self._id_5400 );

                var_2 = var_1._id_4846;
            }
        }
        else if ( isdefined( var_1._id_3211 ) )
        {
            self thread [[ var_1._id_3211 ]]( self._id_5F99 );

            if ( isdefined( self._id_5400 ) )
                self thread [[ var_1._id_3211 ]]( self._id_5400 );

            var_2 = var_1._id_3212;
        }

        thread _id_473F( var_2 );
    }
    else
        thread _id_4740();
}

_id_473F( var_0 )
{
    if ( istrue( self._id_87E1 ) )
        return;

    self notify( "death" );
    self._id_87E1 = 1;
    var_1 = isdefined( self._id_5F99 ) && self._id_5F99 != self;

    if ( isdefined( self._id_CBC3 ) )
    {
        if ( isdefined( self._id_CBC3._id_3E79 ) )
            self._id_CBC3._id_3E79[self getentitynumber()] = undefined;

        if ( isdefined( self._id_CBC3._id_3E4B ) )
            self._id_CBC3._id_3E4B = undefined;

        self._id_CBC3 = undefined;
    }

    _id_C49F( self getentitynumber() );
    self _meth_86FC( "killstreak" );
    self _meth_82F0( 0 );
    self setnodeploy( 1 );

    if ( var_1 )
        self hide();

    _id_99CC();

    if ( isdefined( self._id_FE90 ) )
        self._id_FE90 _meth_809A();

    _id_4824();
    _id_0B92();
    _id_483A();
    _id_3E76();
    _id_4838();

    if ( isdefined( self._id_ED68 ) )
        self._id_ED68 _id_0B91();

    if ( isdefined( self._id_8D49 ) )
        self._id_8D49 _meth_809A();

    wait( var_0 );

    if ( var_1 )
        self._id_5F99 _meth_809A();

    if ( isdefined( self._id_5400 ) )
        self._id_5400 _meth_809A();

    self _meth_809A();
}

_id_4740()
{
    var_0 = level._id_5F1B;

    if ( isdefined( self _meth_86E8() ) && self _meth_8677( "visibility" ) )
        self _meth_8373( "visibility", "hide", 1 );

    _id_473F( var_0 );
}

_id_10AB6()
{
    self endon( "death" );
    var_0 = _id_6AE1( self._id_3E7E );

    if ( isdefined( var_0._id_F221 ) )
    {

    }

    _id_10AB7( var_0._id_F221 );

    if ( istrue( self._id_A430 ) )
        return;

    thread _id_4822();
}

_id_10AB7( var_0 )
{
    if ( isdefined( self._id_02F2 ) )
    {
        self._id_02F2 endon( "disconnect" );
        self._id_02F2 endon( "joined_team" );
        self._id_02F2 endon( "joined_spectators" );
    }

    level endon( "game_ended" );

    if ( isdefined( var_0 ) )
        _id_076B::_id_7A8B( var_0 );
    else
        level waittill( "forever" );
}

_id_4823()
{
    if ( _id_099D::_id_8A10( "entity", "touchingBadTrigger" ) )
    {
        if ( self [[ _id_099D::_id_6D05( "entity", "touchingBadTrigger" ) ]]() )
            thread _id_4822();
    }
}

_id_8159()
{
    var_0 = _func_020F();
    var_0._id_77BE = [];
    var_0._id_77A1 = 4000;
    var_0._id_77A2 = 128;
    level._id_3E64 = var_0;
    _id_826D();
}

_id_826D()
{

}

_id_826C()
{

}

_id_826E()
{

}

_id_8139()
{

}

_id_B146( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    return _id_3F95( var_0, var_1, var_2, var_3, var_4, undefined, 1, 0, var_5 );
}

_id_5008( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    if ( !isdefined( var_5 ) )
    {
        var_7 = _id_6976( var_3, 0 );
        var_5 = _id_6977( var_7, _id_6975( var_7, 0 ) );
    }

    return _id_3F95( var_0, var_1, var_2, var_3, var_4, var_5, undefined, 1, var_6 );
}

_id_5009( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    var_3 = _id_6976( var_3, 1 );
    var_9 = var_3[2];

    if ( !isdefined( var_7 ) )
    {
        var_7 = _id_6977( var_3, _id_6975( var_3, 1 ) );

        if ( !isdefined( var_7 ) )
            return undefined;
    }

    var_10 = _func_020F();
    var_10._id_02F2 = var_0;
    var_10._id_045B = var_1;
    var_10._id_7574 = isdefined( var_0 );
    var_4 = var_4 * ( 0, 1, 0 );
    var_11 = var_3 + -1 * anglestoforward( var_4 ) * var_5;
    var_10._id_5035 = var_3;
    var_10._id_576A = var_3 + anglestoforward( var_4 ) * var_6;
    var_12 = undefined;

    if ( isdefined( var_8 ) )
        var_12 = var_8._id_10313;

    var_13 = _id_3FC9( var_0, var_1, var_11, var_4, var_12 );
    var_13._id_5046 = var_10;
    var_10._id_7652 = var_13;
    var_14 = _id_3F95( var_0, var_1, var_2, var_11, var_13._id_0054, var_7, undefined, 0, var_8 );
    var_14._id_5046 = var_10;
    var_14 _meth_820B( var_13, "tag_origin", ( 16, 0, -156 ), ( 0, 0, 0 ) );
    var_10._id_3E4B = var_14;
    var_10 thread _id_10ACC();
    return var_10;
}

_id_10ACC()
{
    self endon( "death" );
    _id_10ACD();

    if ( isdefined( self._id_3E4B ) )
        self._id_3E4B thread _id_4822();

    if ( isdefined( self._id_7652 ) )
        self._id_7652 thread _id_4831();
}

_id_10ACD()
{
    if ( self._id_7574 )
    {
        self._id_02F2 endon( "disconnect" );
        self._id_02F2 endon( "joined_team" );
        self._id_02F2 endon( "joined_spectators" );
    }

    level endon( "game_ended" );
    self._id_7652 _meth_83A3( self._id_5035, 1 );
    self._id_7652 _id_077B::_id_108F3( "death", 2 );

    if ( !isdefined( self._id_7652 ) || istrue( self._id_7652._id_87E1 ) )
    {
        thread _id_4C2F();
        return;
    }

    self._id_7652 _meth_83BA( 40, 20, 20, 0.3 );

    if ( distancesquared( self._id_7652._id_02EA, self._id_5035 ) > 5184 )
    {
        self._id_7652 _id_077B::_id_1087E( "death", "goal" );

        if ( !isdefined( self._id_7652 ) || istrue( self._id_7652._id_87E1 ) )
        {
            thread _id_4C2F();
            return;
        }

        self._id_7652 _id_077B::_id_108F3( "death", 0.25 );

        if ( isdefined( self._id_3E4B ) && !istrue( self._id_3E4B._id_87E1 ) )
            thread _id_4C2F();

        if ( !isdefined( self._id_7652 ) || istrue( self._id_7652._id_87E1 ) )
            return;

        self._id_7652 _id_077B::_id_108F3( "death", 0.5 );

        if ( !isdefined( self._id_7652 ) || istrue( self._id_7652._id_87E1 ) )
            return;

        if ( distancesquared( self._id_7652._id_02EA, self._id_576A ) > 5184 )
        {
            if ( _id_099D::_id_8A10( "game", "getGameType" ) )
            {
                if ( [[ _id_099D::_id_6D05( "game", "getGameType" ) ]]() == "br" )
                    self._id_7652 _meth_8436( 100, 60 );
                else
                    self._id_7652 _meth_8436( 150, 50 );
            }

            self._id_7652 _meth_83A3( self._id_576A, 1 );
            self._id_7652 _id_077B::_id_1087E( "death", "goal" );
        }
    }
}

_id_4C2F()
{
    var_0 = self._id_3E4B;
    self._id_3E4B._id_5046 = undefined;
    self._id_3E4B = undefined;
    var_0 _id_3E77();
}

_id_3F96( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 )
{
    var_11 = _id_3F95( var_0, var_1, var_2, var_8._id_02EA, var_8._id_0054, var_3, var_4, var_5, var_6 );

    if ( !isdefined( var_11 ) )
        return undefined;

    var_11._id_EA0B = var_7;

    if ( !isdefined( var_8._id_3E79 ) )
        var_8._id_3E79 = [];

    var_8._id_3E79[var_11 getentitynumber()] = var_11;
    var_11._id_5F99 hide();

    if ( isdefined( var_11._id_5400 ) )
        var_11._id_5400 hide();

    return var_11;
}

_id_4821()
{
    if ( isdefined( self._id_CBC3 ) )
        self._id_CBC3._id_36DE[self getentitynumber()] = undefined;

    self _meth_809A();
}

_id_500A( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7 )
{
    if ( _id_099D::_id_8A10( "killstreak", "currentActiveVehicleCount" ) && _id_099D::_id_8A10( "killstreak", "maxVehiclesAllowed" ) )
    {
        if ( [[ _id_099D::_id_6D05( "killstreak", "currentActiveVehicleCount" ) ]]() >= [[ _id_099D::_id_6D05( "killstreak", "maxVehiclesAllowed" ) ]]() )
            return undefined;
    }

    var_8 = _id_6976( var_3, 1 );
    var_9 = var_4 * ( 0, 1, 0 );

    if ( !isdefined( var_5 ) )
    {
        var_5 = _id_6977( var_8, _id_6975( var_8, 1 ) );

        if ( !isdefined( var_5 ) )
            return undefined;
    }

    var_10 = undefined;

    if ( isdefined( var_6 ) )
        var_10 = var_6._id_10313;

    var_11 = _id_3FC9( var_0, var_1, var_8, var_9, var_10, var_7 );

    if ( !isdefined( var_11 ) )
        return undefined;

    var_12 = _id_3F96( var_0, var_1, var_2, var_5, undefined, 0, var_6, var_7, var_11, "care_package", "care_package_drop" );

    if ( !isdefined( var_12 ) )
        return undefined;

    var_11 thread _id_10ACE( var_8 );
    return var_11;
}

_id_10ACE( var_0 )
{
    self endon( "death" );
    _id_10ACF( var_0 );
    self _meth_809A();
}

_id_10ACF( var_0 )
{
    var_1 = _func_025A( anglestoforward( self._id_0054 ) );
    var_2 = var_0 - var_1 * 70000 / 2.0;
    var_3 = var_0 + var_1 * 70000 / 2.0;
    self._id_02EA = var_2;
    self _meth_823B( var_3, 19.5 );
    var_4 = 3589.74;
    var_5 = 0.5;
    var_6 = var_0 - var_1 * var_4 * var_5;

    foreach ( var_8 in self._id_3E79 )
    {
        if ( isdefined( var_8 ) )
            var_8._id_02EA = var_6;
    }

    wait( 9.75 - var_5 );

    foreach ( var_8 in self._id_3E79 )
    {
        if ( isdefined( var_8 ) )
        {
            var_8 _meth_83C3();
            thread _id_4C30( var_8, var_1 );
        }
    }

    wait( 9.75 + var_5 );
}

_id_4C30( var_0, var_1 )
{
    var_0._id_CBC3 = undefined;
    self._id_3E79[var_0 getentitynumber()] = undefined;
    var_0._id_187C = undefined;
    var_0._id_1879 = undefined;
    var_0._id_18BE = undefined;
    var_0 notify( "anim_finished" );
    var_2 = var_0 gettagorigin( "tag_fx" ) - var_0._id_02EA;
    var_0 _id_3E77( var_2, var_1 );
}

_id_6976( var_0, var_1 )
{
    var_2 = undefined;

    if ( istrue( var_1 ) )
        var_2 = var_0 * ( 1, 1, 0 ) + ( 0, 0, _id_6CF6() );
    else
        var_2 = var_0 + ( 0, 0, 25 );

    return var_2;
}

_id_6975( var_0, var_1 )
{
    return var_0 + ( 0, 0, -1 * _id_077B::_id_F07F( istrue( var_1 ), 8000, 8000 ) );
}

_id_6977( var_0, var_1 )
{
    var_2 = undefined;
    var_3 = _func_02C4( [ "physicscontents_itemclip", "physicscontents_glass", "physicscontents_water", "physicscontents_item" ] );
    var_4 = _id_6978();
    var_5 = _func_02BC( var_0, var_1, var_3, var_4, 0, "physicsquery_closest", 1 );

    if ( isdefined( var_5 ) && var_5.size > 0 )
        var_2 = var_5[0]["position"];

    return var_2;
}

_id_6978()
{
    if ( isdefined( level._id_3E63._id_77BE ) && isdefined( level._id_3E63._id_0E1C ) )
        return _id_077B::_id_1B73( [ level._id_3E64._id_77BE, level._id_3E64._id_0E1C, level._id_3E63._id_3E79 ] );
    else
        return _id_077B::_id_1B73( [ level._id_3E64._id_77BE, level._id_3E63._id_3E79 ] );
}

_id_3FC9( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    var_6 = undefined;
    var_7 = "plane_juniform52_00";

    if ( isdefined( var_0 ) && _id_099C::_id_6C48( var_0 ) )
        var_7 = "plane_juniform52_00";

    var_6 = _func_0205( "script_model", var_2 );
    var_6._id_0054 = var_3;
    var_6 setmode( var_7 );
    var_6._id_02F2 = var_0;
    var_6._id_045B = var_1;
    thread _id_0823::_id_323C( var_6 );

    if ( isdefined( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "killstreak", "addToActiveKillstreakList" ) )
            var_6 [[ _id_099D::_id_6D05( "killstreak", "addToActiveKillstreakList" ) ]]( "airdrop", "Killstreak_Air", var_0, 0, 0 );

        if ( var_1 != "neutral" && _id_099D::_id_8A10( "sentient", "registerSentient" ) )
            var_6 [[ _id_099D::_id_6D05( "sentient", "registerSentient" ) ]]( "Killstreak_Air", var_0 );
    }

    var_6 _meth_82F0( 1 );
    var_6._id_8725 = 1;
    var_6 thread [[ _id_099D::_id_6D05( "airdrop", "monitorDamage" ) ]]( 100, "hitequip", ::_id_7418, undefined, 1 );
    return var_6;
}

_id_10B7A()
{
    self endon( "death" );
    _id_10B7B();
    thread _id_4831();
}

_id_10B7B()
{
    self endon( "death" );

    if ( isdefined( self._id_02F2 ) )
    {
        self._id_02F2 endon( "disconnect" );
        self._id_02F2 endon( "joined_team" );
        self._id_02F2 endon( "joined_spectators" );
    }

    level endon( "game_ended" );
    level waittill( "forever" );
}

_id_7418( var_0 )
{
    var_1 = var_0._id_006E;
    _id_4831();
}

_id_4831()
{
    var_0 = anglestoforward( self._id_0054 );
    _func_0196( level._id_0BA3["airdrop_death"], self._id_02EA, var_0 );
    thread _id_0823::plane_explode( self._id_02EA );
    thread _id_474F( 0 );
}

_id_474F( var_0 )
{
    self notify( "death" );
    self._id_87E1 = 1;

    if ( isdefined( self._id_CBC3 ) )
    {
        self._id_CBC3._id_7652 = undefined;
        self._id_CBC3 = undefined;
    }

    _id_C4C1( self getentitynumber() );
    wait( var_0 );
    _id_09BC::_id_0B8F( self );
}

_id_4832( var_0 )
{
    _id_4831();
}

_id_6CF7()
{
    return level._id_3E64._id_77A1;
}

_id_6CF6()
{
    return _id_6CF7() + level._id_3E64._id_77BE.size * level._id_3E64._id_77A2;
}

_id_1091( var_0 )
{
    var_1 = var_0 getentitynumber();
    level._id_3E64._id_77BE[var_1] = var_0;
}

_id_C4C1( var_0 )
{
    level._id_3E64._id_77BE[var_0] = undefined;
}

_id_99CD()
{
    var_0 = _id_6AE1( self._id_3E7E );

    if ( istrue( var_0._id_756E ) )
        return;

    level._id_3E63._id_FDB1[self getentitynumber()] = self;
    self._id_8AAA = 1;

    if ( var_0._id_EB9B && var_0._id_EB9A )
    {
        thread _id_10ABC( 1 );
        var_1 = self._id_FE90;

        if ( !isdefined( var_1 ) )
        {
            var_1 = _func_0205( "script_model", self gettagorigin( var_0._id_FED9 ) );
            var_1 setmode( "tag_origin" );
            var_1 _meth_820B( self );
            var_1 _meth_8225();
            self._id_FE90 = var_1;
        }

        thread _id_10ABC( 2, var_1 );
    }
    else if ( var_0._id_EB9B )
        thread _id_10ABC( 1 );
    else
        thread _id_10ABC( 2 );
}

_id_10ABC( var_0, var_1 )
{
    self endon( "death" );
    self endon( "makeCrateUnusable" );

    if ( isdefined( var_1 ) )
        var_1 endon( "death" );

    if ( var_0 == 1 )
    {
        self._id_02F2 endon( "disconnect" );
        self._id_02F2 endon( "joined_team" );
        self._id_02F2 endon( "joined_spectators" );
        self._id_02F2._id_883D = 1;
    }

    var_2 = _id_6AE1( self._id_3E7E );
    var_3 = _id_6DE2( var_1 );
    var_3._id_FEEB = var_0;
    var_3 _meth_8305( "HINT_NOICON" );
    var_3 _meth_84D8( "show" );
    var_3 sethintdisplayfov( var_2._id_FED9 );
    var_3 _meth_84D3( var_2._id_FEAE );
    var_3 setusefov( var_2._id_FE70 );
    var_3 _meth_84CE( var_2._id_FEAE );
    var_3 _meth_84D4( var_2._id_FE70 );
    var_3 _meth_83A0( var_2._id_049F );
    var_3 setuserange( "duration_none" );

    if ( var_3._id_FEEB == 1 && self._id_EB9C )
        var_3 _meth_832B( self._id_C581 );
    else
        var_3 _meth_832B( self._id_320E );

    self._id_FE48 = getdvarint( "#x3507317ed00b8f54c", 0 );

    if ( self._id_FE48 == 1 )
        _func_0197( level._id_0BA3["airdrop_crate_ui"], self, var_2._id_FED9 );

    var_3._id_FEAF = 1;
    var_3._id_4122 = 0;

    if ( isdefined( var_3._id_FEE7 ) )
        var_3._id_FEE5 = var_3._id_FEE7;
    else if ( _id_099D::_id_8A10( "game", "getGameType" ) )
        var_3._id_FEE5 = _id_077B::_id_F07F( var_0 == 1, var_2._id_ADA0, var_2._id_AC8C );

    var_3._id_84D5 = 0;
    var_3._id_B7FB = undefined;

    for (;;)
    {
        var_3 waittill( "trigger", var_4 );

        if ( _id_31BD( var_4, var_1 ) )
        {
            _id_E735( var_4, var_1 );
            var_4._id_883D = 1;
            var_3._id_B7FB = var_4;
            var_5 = _id_10ABD( var_4, var_1 );

            if ( isdefined( var_4 ) )
                _id_E946( var_4, var_1 );

            var_4._id_883D = 0;
            var_3._id_B7FB = undefined;

            if ( istrue( var_5 ) )
            {
                if ( var_2._id_AAAB && self._id_3E7E != "battle_royale_loadout" )
                {
                    if ( !isdefined( self._id_B77D ) )
                        self._id_B77D = [];

                    self._id_B77D[var_4 getentitynumber()] = var_4;
                }

                if ( !isdefined( self._id_045A ) || self._id_045A != "btm_flag_primary_inside" )
                    thread _id_3204( var_4 );
            }
        }
    }
}

_id_10ABD( var_0, var_1 )
{
    var_2 = _id_6DE2( var_1 );

    if ( var_2._id_FEEB != 1 )
    {
        var_0 endon( "disconnect" );
        var_0 endon( "joined_team" );
        var_0 endon( "joined_spectators" );
    }

    var_2._id_7C71 = "care_package";
    var_2._id_FEAF = _id_077B::_id_F07F( isdefined( var_0._id_A8D9 ), var_0._id_A8D9, 1 );
    _id_B903( var_0, var_1 );

    while ( isdefined( var_0 ) && var_0 _id_099C::_giveweapon() && _id_316A( var_0, var_1 ) && var_0 useanimtree() )
    {
        var_2._id_4122 = var_2._id_4122 + level._id_5F1B * var_2._id_FEAF;

        if ( var_2._id_4122 >= var_2._id_FEE5 )
        {
            var_2._id_4122 = 0.0;
            return 1;
        }

        if ( _id_099D::_id_8A10( "airdrop", "updateUIProgress" ) )
            var_0 [[ _id_099D::_id_6D05( "airdrop", "updateUIProgress" ) ]]( var_2, 1 );

        waitframe();
    }

    var_2._id_4122 = 0.0;
    return 0;
}

_id_99CC()
{
    self notify( "makeCrateUnusable" );
    level._id_3E63._id_FDB1[self getentitynumber()] = undefined;
    self._id_8AAA = 0;

    if ( isdefined( self._id_B7FB ) )
        _id_E946( self._id_B7FB );

    self._id_B7FB = undefined;
    self _meth_8225();

    if ( isdefined( self._id_FE90 ) )
    {
        if ( isdefined( self._id_FE90._id_B7FB ) )
            _id_E946( self._id_FE90._id_B7FB, self._id_FE90 );

        self._id_FE90 _meth_8225();
    }

    var_0 = _id_6AE1( self._id_3E7E );

    if ( isdefined( self._id_FE48 ) && self._id_FE48 == 1 )
        _func_0218( level._id_0BA3["airdrop_crate_ui"], self, var_0._id_FED9 );
}

_id_E735( var_0, var_1 )
{
    var_2 = _id_6DE2( var_1 );
    var_3 = _id_6AE1( self._id_3E7E );
    var_4 = getdvarint( "scr_airDrop_use_weapon", 1 );

    if ( var_4 )
        var_0 thread _id_1355();

    if ( _id_099D::_id_8A10( "airdrop", "allowActionSet" ) )
        var_0 [[ _id_099D::_id_6D05( "airdrop", "allowActionSet" ) ]]( "crateUse", 0 );

    if ( _id_099D::_id_8A10( "airdrop", "updateUIProgress" ) )
        var_0 [[ _id_099D::_id_6D05( "airdrop", "updateUIProgress" ) ]]( var_2, 0 );
}

_id_1355()
{
    self endon( "disconnect" );
    level endon( "game_ended" );
    var_0 = _func_034C( "s4_ks_care_package_mp" );
    _id_099A::_id_0BEB( var_0 );
    thread _id_137A( var_0 );
    self _meth_83FF( var_0 );
}

_id_137A( var_0 )
{
    self endon( "disconnect" );
    level endon( "game_ended" );
    self waittill( "crate_use_end" );

    if ( _id_099A::_id_8A6D( var_0 ) )
        _id_099A::_id_0DE3( var_0 );
    else
    {
        _id_099A::_id_0D6A( var_0 );
        self _meth_83FF( self._id_8FAB );
    }
}

_id_E946( var_0, var_1 )
{
    var_2 = _id_6DE2( var_1 );
    var_3 = _id_6AE1( self._id_3E7E );

    if ( _id_099D::_id_8A10( "airdrop", "allowActionSet" ) )
        var_0 [[ _id_099D::_id_6D05( "airdrop", "allowActionSet" ) ]]( "crateUse", 1 );

    if ( _id_099D::_id_8A10( "airdrop", "updateUIProgress" ) )
        var_0 [[ _id_099D::_id_6D05( "airdrop", "updateUIProgress" ) ]]( var_2, 0 );

    _id_E945( var_0, var_1 );
    var_0 notify( "crate_use_end" );
}

_id_31BD( var_0, var_1, var_2 )
{
    if ( !var_0 _id_06BB::_id_8570() )
        return 0;

    if ( !var_0 _id_099C::_giveweapon() )
        return 0;

    if ( var_0 isonground() )
        return 0;

    if ( !var_0 _meth_81D7() )
        return 0;

    if ( isdefined( self._id_B77D ) && isdefined( self._id_B77D[var_0 getentitynumber()] ) )
        return 0;

    if ( istrue( self.issp ) )
    {
        if ( isdefined( self._id_B7D6 ) && _id_077B::_id_1B78( self._id_B7D6, var_0 ) )
            return 0;

        if ( var_0._id_E493 != self._id_E493 || var_0._id_045B != self._id_045B )
            return 0;
    }

    if ( _func_0107( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "airdrop", "botIsKillstreakSupported" ) )
        {
            if ( _id_099D::_id_8A10( "game", "getGameType" ) )
            {
                if ( [[ _id_099D::_id_6D05( "game", "getGameType" ) ]]() != "grnd" && ![[ _id_099D::_id_6D05( "airdrop", "botIsKillstreakSupported" ) ]]( self._id_3E7E ) )
                    return 0;
            }
        }

        if ( _id_099D::_id_8A10( "airdrop", "isKillstreakBlockedForBots" ) )
        {
            if ( [[ _id_099D::_id_6D05( "airdrop", "isKillstreakBlockedForBots" ) ]]( self._id_3E7E ) )
                return 0;
        }
    }

    if ( !self._id_8AAA )
        return 0;

    if ( !isdefined( var_2 ) )
        var_2 = 1;

    if ( var_2 )
        return _id_31BE( var_0, var_1 );

    if ( level._id_60D1 == "br" && var_0 _meth_86B4() )
        return 0;

    if ( istrue( var_0._id_82AC ) )
        return 0;

    return 1;
}

_id_31BE( var_0, var_1 )
{
    var_2 = _id_6DE2( var_1 );

    if ( isdefined( var_2._id_B7FB ) && var_2._id_B7FB != var_0 )
        return 0;

    if ( var_2._id_FEEB == 1 && ( !isdefined( self._id_02F2 ) || var_0 != self._id_02F2 ) )
        return 0;

    if ( var_2._id_FEEB == 2 && ( isdefined( self._id_02F2 ) && var_0 == self._id_02F2 ) )
        return 0;

    if ( level._id_EF62 && isdefined( self._id_045B ) && self._id_045B != "neutral" )
    {
        var_3 = _id_6AE1( self._id_3E7E );

        if ( var_3._id_5FA0 && var_0._id_045B != self._id_045B )
            return 0;
    }

    return 1;
}

_id_316A( var_0, var_1 )
{
    if ( !_id_06BB::_id_8570() )
        return 0;

    if ( !var_0 _id_099C::_giveweapon() )
        return 0;

    if ( var_0 _meth_822E() )
        return 0;

    if ( var_0 _meth_86C6() )
        return 0;

    if ( istrue( var_0._id_82AC ) )
        return 0;

    var_2 = _id_6AE1( self._id_3E7E );

    if ( isdefined( var_2._id_2B76 ) && distancesquared( var_0._id_02EA, _id_6DE2( var_1 )._id_02EA ) >= var_2._id_2B76 )
        return 0;

    if ( !self._id_8AAA )
        return 0;

    return 1;
}

_id_99CE( var_0, var_1 )
{
    var_0 _meth_80E0( var_1 );

    if ( isdefined( var_0._id_FE90 ) )
        var_0._id_FE90 _meth_80E0( var_1 );

    if ( !var_0 _id_31BD( var_1, var_0._id_FE90, 0 ) )
    {
        var_0 disableoffhandweapons( var_1 );

        if ( isdefined( var_0._id_FE90 ) )
            var_0._id_FE90 disableoffhandweapons( var_1 );
    }
    else
    {
        if ( !var_0 _id_31BE( var_1, undefined ) )
            var_0 disableoffhandweapons( var_1 );

        if ( isdefined( var_0._id_FE90 ) )
        {
            if ( !var_0 _id_31BE( var_1, var_0._id_FE90 ) )
                var_0._id_FE90 disableoffhandweapons( var_1 );
        }
    }
}

_id_10A89()
{
    for (;;)
    {
        foreach ( var_1 in level._id_3E63._id_FDB1 )
        {
            if ( !isdefined( var_1 ) )
            {
                thread _id_077B::_id_5578( "airdrop crate was deleted incorrectly." );
                continue;
            }

            var_1 makeunusable();
            var_1 _meth_8798();

            if ( isdefined( var_1._id_FE90 ) )
            {
                var_1._id_FE90 makeunusable();
                var_1._id_FE90 _meth_8798();
            }

            var_2 = level._id_B758;

            if ( level._id_EF62 && isdefined( var_1._id_045B ) && var_1._id_045B != "neutral" )
            {
                var_3 = _id_6AE1( var_1._id_3E7E );

                if ( var_3._id_5FA0 )
                    var_2 = level._id_EF67[var_1._id_045B]["alivePlayers"];
            }

            foreach ( var_5 in var_2 )
            {
                var_6 = distancesquared( var_1._id_02EA, var_5._id_02EA ) < 57600.0;

                if ( var_6 )
                    _id_99CE( var_1, var_5 );
            }
        }

        wait 0.1;
    }
}

_id_10A88()
{
    if ( getdvarint( "scr_airdrop_fast_usable_crates", 0 ) )
    {
        thread _id_10A89();
        return;
    }

    for (;;)
    {
        foreach ( var_1 in level._id_3E63._id_FDB1 )
        {
            if ( !isdefined( var_1 ) )
            {
                thread _id_077B::_id_5578( "airdrop crate was deleted incorrectly." );
                continue;
            }

            var_1 makeunusable();

            if ( isdefined( var_1._id_FE90 ) )
                var_1._id_FE90 makeunusable();

            foreach ( var_3 in level._id_B758 )
                _id_99CE( var_1, var_3 );
        }

        wait 0.1;
    }
}

_id_B903( var_0, var_1 )
{
    var_2 = _id_6DE2( var_1 );
}

_id_E945( var_0, var_1 )
{
    var_2 = _id_6DE2( var_1 );
}

_id_6DE2( var_0 )
{
    return _id_077B::_id_F07F( isdefined( var_0 ), var_0, self );
}

_id_3E77( var_0, var_1 )
{
    var_2 = _id_6AE1( self._id_3E7E );

    if ( isdefined( var_2._id_3E78 ) )
        self thread [[ var_2._id_3E78 ]]();

    if ( !isdefined( var_0 ) )
        var_0 = ( 0, 0, 0 );

    if ( !isdefined( var_1 ) )
        var_1 = ( 0, 0, 0 );

    self _meth_8415();
    self _meth_8254( self._id_02EA, var_1 * 40000 );
    self._id_B03C = 1;
    _id_3F98();
    _id_392F();
    thread _id_A0E3();
    thread _id_A105();
    thread _id_A11F();
}

_id_3E76()
{
    if ( !istrue( self._id_B03C ) )
        return;

    self._id_B03C = undefined;
    self._id_B03F = undefined;
    self _meth_8544();
    _id_392F();
    _id_3901();
    _id_A106();
    _id_A120();
}

_id_D5CD()
{
    self._id_A244 = undefined;
    self._id_F9A4 = ::_id_3E7F;
}

_id_392F()
{
    self._id_A244 = 1;
    self._id_F9A4 = undefined;
}

_id_A0E3()
{
    self endon( "death" );
    var_0 = 0.1;
    thread _id_A0E2( var_0, 8 );
    var_1 = 0;
    var_2 = 0;
    var_3 = 1;
    var_4 = undefined;
    var_5 = undefined;

    if ( _id_099D::_id_8A10( "game", "lpcFeatureGated" ) )
        var_5 = _id_099D::_id_6D05( "game", "lpcFeatureGated" );

    for (;;)
    {
        var_6 = _id_68D0();
        var_7 = _id_68CE();

        if ( isdefined( var_6 ) && isdefined( var_7 ) )
        {
            if ( var_6 <= 5.0 && var_7 <= 1.0 )
            {
                var_1++;
                var_2 = 0;

                if ( var_1 == 6 )
                {
                    self._id_B03F = 1;
                    var_4 = self._id_02EA;
                    thread _id_0EBF( var_3 );

                    if ( isdefined( var_5 ) && [[ var_5 ]]() )
                    {
                        _id_A106();

                        if ( isdefined( self._id_8D49 ) )
                            self._id_8D49 _meth_809A();
                    }

                    var_0 = 0.1;
                    thread _id_A0E2( var_0, 3, 3 );
                    var_3 = undefined;
                    _id_4823();
                }
            }
            else
            {
                if ( isdefined( var_4 ) )
                {
                    if ( distancesquared( self._id_02EA, var_4 ) <= 2500 )
                    {
                        wait( var_0 );
                        continue;
                    }
                }

                var_2++;
                var_1 = 0;

                if ( var_2 == 1 )
                {
                    self._id_B03F = undefined;
                    thread _id_436A();
                    var_0 = 0.1;
                    thread _id_A0E2( var_0, 8 );
                }
            }

            wait( var_0 );
            continue;
        }

        waitframe();
    }
}

_id_A0E2( var_0, var_1, var_2 )
{
    _id_3901();
    self endon( "death" );
    self endon( "clear_average_velocities" );
    self._id_9504 = [];
    self._id_1771 = [];
    self._id_103A0 = 0;
    self._id_10398 = 0;
    self._id_10399 = var_1;

    if ( isdefined( var_2 ) )
    {
        var_2 = int( clamp( var_2, 0, var_1 ) );

        if ( var_2 > 0 )
        {
            for ( var_3 = 0; var_3 < var_2; var_3++ )
            {
                self._id_9504[self._id_103A0 + var_3] = 0;
                self._id_1771[self._id_103A0 + var_3] = 0;
            }
        }
    }

    for (;;)
    {
        var_4 = self _meth_846D( 0 );
        var_5 = _func_029C( var_4 );
        var_6 = _func_029D( var_4 );
        self._id_9504[self._id_10398] = _func_0130( var_5 );
        self._id_1771[self._id_10398] = _func_0130( var_6 );
        self._id_10398++;
        var_7 = self._id_10398 - self._id_103A0;

        if ( var_7 > var_1 )
        {
            var_8 = _id_077B::_id_9FB1( var_7, var_1 );

            for ( var_3 = 0; var_3 < var_8; var_3++ )
            {
                self._id_9504[self._id_103A0 + var_3] = undefined;
                self._id_1771[self._id_103A0 + var_3] = undefined;
            }

            self._id_103A0 = self._id_103A0 + var_8;
        }

        self._id_1F75 = undefined;
        self._id_1F6F = undefined;
        wait( var_0 );
    }
}

_id_68D0()
{
    if ( isdefined( self._id_1F75 ) )
        return self._id_1F75;

    if ( !isdefined( self._id_9504 ) )
        return undefined;

    if ( self._id_10398 - self._id_103A0 < self._id_10399 )
        return undefined;

    _id_2EB8();
    return self._id_1F75;
}

_id_68CE()
{
    if ( isdefined( self._id_1F6F ) )
        return self._id_1F6F;

    if ( !isdefined( self._id_1771 ) )
        return undefined;

    if ( self._id_10398 - self._id_103A0 < self._id_10399 )
        return undefined;

    _id_2EB8();
    return self._id_1F6F;
}

_id_2EB8()
{
    var_0 = 0;
    var_1 = 0;

    for ( var_2 = self._id_103A0; var_2 < self._id_10398; var_2++ )
    {
        var_0 = var_0 + self._id_9504[var_2];
        var_1 = var_1 + self._id_1771[var_2];
    }

    self._id_1F75 = var_0 / self._id_10399;
    self._id_1F6F = var_1 / self._id_10399;
}

_id_3901()
{
    self notify( "clear_average_velocities" );
    self._id_9504 = undefined;
    self._id_1771 = undefined;
    self._id_10399 = undefined;
    self._id_103A0 = undefined;
    self._id_10398 = undefined;
    self._id_1F75 = undefined;
    self._id_1F6F = undefined;
}

_id_A105( var_0 )
{
    _id_A106();
    self endon( "monitorImpactEnd" );
    self._id_A108 = 1;
    self _meth_84FB();
    _id_A107( var_0 );

    if ( isdefined( self ) )
        thread _id_A106();
}

_id_A107( var_0 )
{
    self endon( "death" );

    if ( isdefined( var_0 ) )
        wait( var_0 );

    var_1 = 0;

    for (;;)
    {
        self waittill( "collision", var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 );

        if ( isdefined( var_9 ) && isdefined( var_9._id_00DE ) && var_9._id_00DE == "scriptable_iw8_chicken_01" )
            thread _id_1352( var_9 );

        if ( isdefined( var_9 ) && _id_7D3B( var_9 ) )
        {
            if ( var_9 _id_098C::_id_8883() )
                var_9 thread _id_098C::_id_7850();
        }

        if ( gettime() - var_1 >= 200 )
        {
            var_1 = gettime();
            var_10 = _func_02C5( var_5 );
            var_11 = _func_00D6( var_10["name"], 9 );

            if ( var_11 == "user_terrain1" )
                var_11 = "user_terrain_1";

            _id_B840( var_6, var_7, var_8, var_11 );
        }
    }
}

_id_1352( var_0 )
{
    self endon( "death" );
    var_1 = gettime();

    while ( gettime() - var_1 < 3000 )
    {
        var_0 _meth_80B7( 100, var_0._id_02EA, self, self, "MOD_CRUSH" );
        wait 0.5;
    }
}

_id_A106()
{
    if ( !istrue( self._id_A108 ) )
        return;

    self notify( "monitorImpactEnd" );
    self._id_A108 = undefined;
    self physics_registerforcollisioncallback();
}

_id_7D3B( var_0 )
{
    if ( !istrue( self._id_B03F ) )
    {
        if ( isdefined( var_0._id_00DE ) )
        {
            if ( var_0._id_00DE == "worldSpawn" )
                return 0;
            else if ( var_0._id_00DE == "script_vehicle" )
            {
                if ( var_0 _id_098C::_id_8883() )
                {
                    var_1 = _id_6AE1( self._id_3E7E );
                    var_2 = self._id_02EA + anglestoup( self._id_0054 ) * var_1._id_739D;
                    return var_0._id_02EA[2] <= var_2[2];
                }
            }
        }
    }

    return 0;
}

_id_A11F()
{
    _id_A120();
    self endon( "death" );
    self endon( "monitorPlayerImpactEnd" );
    var_0 = self;

    if ( isdefined( self._id_A1AD ) )
        var_0 = self._id_A1AD;

    var_1 = undefined;

    if ( isdefined( self._id_02F2 ) )
        var_1 = self._id_02F2;

    while ( isdefined( var_0 ) )
    {
        var_0 waittill( "player_pushed", var_2, var_3 );

        if ( isdefined( var_2 ) && ( _func_0117( var_2 ) || _func_0102( var_2 ) ) && var_2 _id_099C::_giveweapon() )
        {
            var_4 = var_3[2] <= -8;
            var_5 = 0;
            var_6 = undefined;

            if ( var_2 tagexists( "j_mainroot" ) )
            {
                var_6 = var_2 gettagorigin( "j_mainroot" );
                var_7 = _id_6AE1( self._id_3E7E );
                var_8 = self._id_02EA + anglestoup( self._id_0054 ) * var_7._id_739D;
                var_5 = var_6[2] <= var_8[2];
            }

            if ( var_4 && var_5 )
            {
                var_9 = var_1;

                if ( !isdefined( var_9 ) )
                    var_9 = var_2;

                var_2 _meth_80B7( var_2._id_027F * 2, var_6, var_9, self, "MOD_CRUSH", self._id_A90B );
            }
        }
    }
}

_id_A120()
{
    self notify( "monitorPlayerImpactEnd" );
}

_id_B840( var_0, var_1, var_2, var_3 )
{
    if ( var_2 < 50 )
        return;

    _func_0196( _id_077B::_id_6A40( "airdrop_crate_impact" ), var_0, var_1 );

    if ( var_2 < 150 )
        thread _id_0823::carepackage_impact_small( var_0 );
    else if ( var_2 < 300 )
        thread _id_0823::carepackage_impact_med( var_0 );
    else
        thread _id_0823::carepackage_impact_large( var_0 );
}

_id_3F98()
{
    if ( _id_099D::_id_8A10( "game", "lpcFeatureGated" ) && [[ _id_099D::_id_6D05( "game", "lpcFeatureGated" ) ]]() )
        return;

    if ( !_id_099D::_id_8A10( "spawn", "addSpawnDangerZone" ) )
        return;

    _id_4824();
    var_0 = _id_6AE1( self._id_3E7E );
    var_1 = undefined;

    if ( isdefined( self._id_02F2 ) && isdefined( self._id_045B ) )
        var_1 = [[ _id_099D::_id_6D05( "spawn", "addSpawnDangerZone" ) ]]( self._id_4802, var_0._id_432A, var_0._id_4327, self._id_045B, 30.0, self._id_02F2, 1 );
    else if ( isdefined( self._id_045B ) )
        var_1 = [[ _id_099D::_id_6D05( "spawn", "addSpawnDangerZone" ) ]]( self._id_4802, var_0._id_432A, var_0._id_4327, self._id_045B, 30.0 );
    else
        var_1 = _id_E39B( self._id_4802, var_0._id_432A, var_0._id_4327, 30.0 );

    self._id_4328 = var_1;
    return var_1;
}

_id_E39B( var_0, var_1, var_2, var_3 )
{
    if ( _id_099D::_id_8A10( "spawn", "addSpawnDangerZone" ) )
    {
        var_4 = [[ _id_099D::_id_6D05( "spawn", "addSpawnDangerZone" ) ]]( var_0, var_1, var_2, undefined, var_3, level._id_B758[_func_01B8( level._id_B758.size )], 1 );
        self._id_4328 = var_4;
        return var_4;
    }
}

_id_4824()
{
    if ( _id_099D::_id_8A10( "spawn", "isSpawnDangerZoneAlive" ) && _id_099D::_id_8A10( "spawn", "removeSpawnDangerZone" ) )
    {
        var_0 = self._id_4328;

        if ( isdefined( var_0 ) && [[ _id_099D::_id_6D05( "spawn", "isSpawnDangerZoneAlive" ) ]]( var_0 ) )
            [[ _id_099D::_id_6D05( "spawn", "removeSpawnDangerZone" ) ]]( var_0 );

        self._id_4328 = undefined;
    }
}

_id_0B80()
{
    self notify( "createNavObstacle" );
    self endon( "createNavObstacle" );

    if ( isdefined( self._id_A3D4 ) )
        _func_02AC( self._id_A3D4 );

    var_0 = _id_6AE1( self._id_3E7E );
    var_1 = _func_02AA( self._id_02EA, var_0._id_A3D3, self._id_0054 );
    self._id_A3D4 = var_1;
    childthread _id_0DA9( var_1, self._id_02EA, var_0._id_A3D5 );
    return var_1;
}

_id_0DA9( var_0, var_1, var_2 )
{
    self endon( "death" );

    while ( distancesquared( var_1, self._id_02EA ) < var_2 )
        wait 0.5;

    thread _id_0B80();
}

_id_0B92()
{
    self notify( "createNavObstacle" );

    if ( isdefined( self._id_A3D4 ) )
        _func_02AC( self._id_A3D4 );

    self._id_A3D4 = undefined;
}

_id_3FF7()
{
    var_0 = _id_6AE1( self._id_3E7E );

    if ( isdefined( var_0._id_A1AD ) )
    {
        if ( isdefined( self._id_A1AD ) )
            self._id_A1AD _meth_809A();

        var_1 = _func_0205( "script_model", self._id_02EA );
        var_1 _meth_80BE();
        var_1._id_0054 = self._id_0054;
        var_1._id_02F2 = self._id_02F2;
        var_1._id_F9A5 = 1;
        var_1._id_8D49 = self._id_8D49;
        var_1._id_A1AD = 1;
        var_1 _meth_808C( level._id_3E63._id_A1AD );
        var_1 _meth_820B( self );
        self._id_A1AD = var_1;
        var_1._id_3E4B = self;
    }
}

_id_483A()
{
    if ( isdefined( self._id_A1AD ) )
        self._id_A1AD _meth_809A();

    self._id_A1AD = undefined;
}

_id_3E7F( var_0 )
{
    var_0 _meth_80B7( 1000, var_0._id_02EA, self._id_02F2, self, "MOD_CRUSH", self._id_A90B );
    self endon( "death" );
    var_0 endon( "death_or_disconnect" );

    if ( _func_0117( var_0 ) && var_0 _id_099C::_giveweapon() )
    {
        if ( _id_099D::_id_8A10( "airdrop", "unresolvedCollisionNearestNode" ) )
            [[ _id_099D::_id_6D05( "airdrop", "unresolvedCollisionNearestNode" ) ]]( var_0, undefined, self );
    }
}

_id_0B7F()
{
    if ( istrue( self._id_4AE5 ) )
        return;

    _id_0766::_id_D586( self._id_75D8 );
    var_0 = _id_6AE1( self._id_3E7E );
    var_1 = undefined;

    if ( isdefined( self._id_75CE ) )
    {
        if ( level._id_EF62 && isdefined( self._id_045B ) )
        {
            if ( !_id_0999::_id_89D2() )
                var_1 = _id_0766::_id_D58E( self._id_045B, self._id_75CE, var_0._id_75DA, 1, var_0._id_75D3, var_0._id_75D9, undefined, 1 );

            if ( isdefined( var_1 ) )
            {
                if ( _id_099D::_id_8A10( "game", "isMLGMatch" ) )
                {
                    if ( [[ _id_099D::_id_6D05( "game", "isMLGMatch" ) ]]() )
                        _func_035A( var_1, "spectator" );
                }
            }
        }
        else if ( isdefined( self._id_02F2 ) )
        {
            if ( !_id_0999::_id_89D2() )
                var_1 = _id_0766::_id_D58E( self._id_02F2, self._id_75CE, var_0._id_75DA, 1, var_0._id_75D3, var_0._id_75D9, undefined, 1 );

            if ( isdefined( var_1 ) )
            {
                if ( _id_099D::_id_8A10( "game", "isMLGMatch" ) )
                {
                    if ( [[ _id_099D::_id_6D05( "game", "isMLGMatch" ) ]]() )
                        _func_035A( var_1, "spectator" );
                }
            }
        }
        else if ( !_id_0999::_id_89D2() )
            _id_0766::_id_D58E( level._id_EF86, self._id_75CE, var_0._id_75DA, 1, var_0._id_75D3, var_0._id_75D9 );
    }

    self._id_75D8 = var_1;
    self._id_75D0 = 1;
    return var_1;
}

_id_0B91()
{
    _id_0766::_id_D586( self._id_75D8 );
    self._id_75D8 = undefined;
    self._id_75D0 = 0;
}

_id_3FF0()
{
    _id_4838();
    var_0 = undefined;

    if ( isdefined( self._id_9F0C ) && !istrue( self._id_10414 ) )
    {
        var_1 = undefined;

        if ( _id_099D::_id_8A10( "game", "createObjective" ) )
            var_1 = _id_099D::_id_6D05( "game", "createObjective" );

        if ( isdefined( var_1 ) )
        {
            if ( level._id_EF62 && isdefined( self._id_045B ) )
                var_0 = self [[ var_1 ]]( self._id_9F0C, self._id_045B, 1, 1, 0 );
            else if ( isdefined( self._id_02F2 ) )
                var_0 = self [[ var_1 ]]( self._id_9F0C, undefined, 1, 1, 0 );
            else
                var_0 = self [[ var_1 ]]( self._id_9F0C, undefined, 0, 1, 0 );
        }
    }

    self._id_9F0F = var_0;
    self._id_9F0E = 1;
    return var_0;
}

_id_4838()
{
    if ( isdefined( self._id_9F0F ) )
    {
        if ( _id_099D::_id_8A10( "game", "returnObjectiveID" ) )
            [[ _id_099D::_id_6D05( "game", "returnObjectiveID" ) ]]( self._id_9F0F );
    }

    self._id_9F0F = undefined;
    self._id_9F0E = 0;
}

_id_10C26()
{
    self endon( "death" );

    foreach ( var_1 in level._id_B758 )
        _id_FD7E( var_1 );

    waitframe();
    childthread _id_10C27();
}

_id_10C27()
{
    for (;;)
    {
        level waittill( "joined_team", var_0 );
        _id_FD7E( var_0 );
    }
}

_id_FD7E( var_0 )
{
    self._id_5F99 _meth_847B( var_0 );
    self._id_5400 _meth_847B( var_0 );

    if ( var_0._id_045B == "spectator" )
    {
        self._id_5F99 _meth_83CA( var_0 );
        return;
    }

    if ( level._id_EF62 && isdefined( self._id_045B ) )
    {
        if ( var_0._id_045B == self._id_045B )
            self._id_5F99 _meth_83CA( var_0 );
        else
            self._id_5400 _meth_83CA( var_0 );

        return;
    }

    if ( !level._id_EF62 && isdefined( self._id_02F2 ) )
    {
        if ( var_0 == self._id_02F2 )
            self._id_5F99 _meth_83CA( var_0 );
        else
            self._id_5400 _meth_83CA( var_0 );

        return;
    }
}

_id_9835( var_0, var_1, var_2 )
{
    self endon( "death" );
    var_0 endon( "death" );
    self notify( "looseLinkTo" );
    self endon( "looseLinkToEnd" );

    while ( istrue( self._id_B03C ) )
    {
        self._id_02EA = var_0._id_02EA + var_1;
        waitframe();
    }

    self _meth_820B( var_0 );
}

_id_1138()
{
    level._id_3E63._id_3E79[self getentitynumber()] = self;
}

_id_C49F( var_0 )
{
    if ( !isdefined( level._id_3E63 ) )
        return;

    level._id_3E63._id_3E79[var_0] = undefined;
}

_id_6CA3( var_0, var_1 )
{
    if ( isdefined( var_1 ) )
    {
        if ( !isalive( var_1 ) )
            var_1 = [ var_1 ];
    }

    var_2 = [];
    var_3 = [];
    var_4 = 0;

    foreach ( var_11, var_6 in var_0 )
    {
        if ( var_6 > 0 )
        {
            var_7 = 0;

            if ( isdefined( var_1 ) )
            {
                if ( var_1.size > 0 )
                {
                    foreach ( var_10, var_9 in var_1 )
                    {
                        if ( var_9 == var_11 )
                        {
                            var_1[var_10] = undefined;
                            var_7 = 1;
                            break;
                        }
                    }
                }
                else
                    var_1 = undefined;
            }

            if ( !var_7 )
            {
                var_4 = var_4 + var_6;
                var_2[var_2.size] = var_11;
                var_3[var_3.size] = var_4;
            }
        }
    }

    var_12 = _func_01B8( var_4 );
    var_11 = undefined;

    for ( var_13 = 0; var_13 < var_2.size; var_13++ )
    {
        var_4 = var_3[var_13];

        if ( var_12 < var_4 )
        {
            var_11 = var_2[var_13];
            break;
        }
    }

    return var_11;
}

_id_69AF()
{
    return ::_id_4586;
}

#using_animtree("scriptables");

_id_69B0()
{
    return _func_0079( %mp_military_carepackage_straps_falling );
}

_id_4586( var_0 )
{
    if ( !isdefined( self ) )
        return;

    if ( istrue( self._id_87FB ) )
        return;

    if ( !isdefined( var_0 ) )
        return;

    var_1 = _func_0079( %mp_military_carepackage_straps_falling );

    if ( isdefined( var_1 ) )
        var_1 = _func_0147( 0, var_1 - 0.05 );

    var_0 _meth_8373( "anims", "capture", 0 );
    var_0 _meth_8373( "capture", "start", 0 );

    if ( isdefined( var_1 ) )
        _id_076B::_id_7A8B( var_1 );

    _func_0196( _id_077B::_id_6A40( "airdrop_crate_capture" ), self._id_02EA, anglestoforward( self._id_0054 ), anglestoup( self._id_0054 ) );
}

_id_69B2()
{
    return 0;
}

_id_69B1()
{
    return ::_id_458B;
}

_id_458B( var_0 )
{

}

_id_69B6()
{
    return level._id_3E63._id_A1AD;
}

_id_6B93()
{
    if ( !isdefined( level._id_3E63 ) )
        return 0;

    return level._id_3E63._id_3E79.size;
}

_id_F3F6()
{
    if ( !isdefined( self._id_54F1 ) )
    {
        if ( self _meth_81CD() )
        {
            var_0 = self _meth_815A();

            if ( isdefined( var_0 ) && isdefined( var_0._id_3E4B ) )
            {
                self._id_54EF = var_0;
                self._id_54F0 = var_0._id_3E4B;
            }

            self._id_54F1 = gettime() + 1000;
        }
    }
    else if ( gettime() >= self._id_54F1 )
    {
        self._id_54EF = undefined;
        self._id_54F0 = undefined;
        self._id_54F1 = undefined;
    }
    else
    {
        foreach ( var_2 in level._id_3E63._id_3E79 )
        {
            if ( isdefined( var_2 ) && istrue( var_2._id_B03C ) && !istrue( var_2._id_B03F ) )
            {
                if ( isdefined( self._id_54EF ) )
                {
                    if ( isdefined( var_2._id_A1AD ) )
                    {
                        if ( self._id_54EF != var_2._id_A1AD )
                        {
                            if ( self _meth_81EF( var_2._id_A1AD ) )
                            {
                                self._id_54EF = undefined;
                                self._id_54F0 = undefined;
                                self._id_54F1 = undefined;

                                if ( _id_099D::_id_8A10( "damage", "_suicide" ) )
                                    self thread [[ _id_099D::_id_6D05( "damage", "_suicide" ) ]]();
                                else
                                    self _meth_83FD();

                                return;
                            }
                        }
                    }

                    if ( self._id_54F0 != var_2 )
                    {
                        if ( self _meth_81EF( var_2 ) )
                        {
                            self._id_54EF = undefined;
                            self._id_54F0 = undefined;
                            self._id_54F1 = undefined;

                            if ( _id_099D::_id_8A10( "damage", "_suicide" ) )
                                self thread [[ _id_099D::_id_6D05( "damage", "_suicide" ) ]]();
                            else
                                self _meth_83FD();

                            return;
                        }
                    }
                }
                else if ( self _meth_81EF( var_2 ) || isdefined( var_2._id_A1AD ) && self _meth_81EF( var_2._id_A1AD ) )
                {
                    self._id_54EF = undefined;
                    self._id_54F0 = undefined;
                    self._id_54F1 = undefined;

                    if ( _id_099D::_id_8A10( "damage", "_suicide" ) )
                        self thread [[ _id_099D::_id_6D05( "damage", "_suicide" ) ]]();
                    else
                        self _meth_83FD();

                    return;
                }
            }
        }
    }
}

_id_AD37( var_0 )
{
    if ( isdefined( self._id_320E ) && self._id_320E == var_0 )
        return;

    self._id_320E = var_0;
    var_1 = [ self ];

    if ( isdefined( self._id_FE90 ) )
        var_1[var_1.size] = self._id_FE90;

    foreach ( var_3 in var_1 )
    {
        if ( !self._id_EB9C || var_3._id_FEEB == 2 )
            var_3 _meth_832B( self._id_320E );
    }
}

_id_AD49( var_0 )
{
    if ( isdefined( self._id_C581 ) && self._id_C581 == var_0 )
        return;

    self._id_C581 = var_0;
    var_1 = [ self ];

    if ( isdefined( self._id_FE90 ) )
        var_1[var_1.size] = self._id_FE90;

    foreach ( var_3 in var_1 )
    {
        if ( self._id_EB9C && var_3._id_FEEB == 1 )
            var_3 _meth_832B( self._id_C581 );
    }
}

_id_AD3E( var_0 )
{
    if ( !isdefined( self._id_75CE ) && !isdefined( var_0 ) )
        return;

    if ( isdefined( self._id_75CE ) && isdefined( var_0 ) && self._id_75CE == var_0 )
        return;

    if ( !isdefined( var_0 ) )
    {
        self._id_75CE = undefined;

        if ( isdefined( self._id_ED68 ) )
            self._id_ED68 _id_0B91();
    }
    else
    {
        self._id_75CE = var_0;

        if ( self._id_75D0 )
        {
            if ( isdefined( self._id_75D8 ) )
                _func_0350( self._id_75D8, var_0 );
            else
                _id_0B7F();
        }
    }
}

_id_AD42( var_0 )
{
    if ( !isdefined( self._id_9F0C ) && !isdefined( var_0 ) )
        return;

    if ( isdefined( self._id_9F0C ) && isdefined( var_0 ) && self._id_9F0C == var_0 )
        return;

    if ( !isdefined( var_0 ) )
    {
        self._id_9F0C = undefined;
        _id_4838();
    }
    else
    {
        self._id_9F0C = var_0;

        if ( self._id_9F0E )
        {
            if ( isdefined( self._id_9F0F ) && _id_099D::_id_8A10( "game", "updateObjectiveIcon" ) )
                [[ _id_099D::_id_6D05( "game", "updateObjectiveIcon" ) ]]( self._id_9F0F, var_0 );
            else
                _id_3FF0();
        }
    }
}

_id_AD4C( var_0 )
{
    if ( self._id_EB9C == var_0 )
        return;

    self._id_EB9C = var_0;

    if ( self._id_EB9C )
    {
        var_1 = [ self ];

        if ( isdefined( self._id_FE90 ) )
            var_1[var_1.size] = self._id_FE90;

        foreach ( var_3 in var_1 )
        {
            if ( var_3._id_FEEB == 1 )
                var_3 _meth_832B( self._id_C581 );
        }
    }
}

_id_81E9()
{
    level._id_3E63._id_8E3B = [];
    level._id_3E63._id_8E34 = [];
    level._id_3E63._id_8E39 = [];
    var_0 = ::_id_8DB1;
    var_1 = ::_id_8DB2;
    var_2 = _id_6AE1( "killstreak" );
    var_2._id_0EBE = var_0;
    var_2._id_3201 = var_1;
    var_2 = _id_6AE1( "killstreak_no_owner" );
    var_2._id_0EBE = var_0;
    var_2._id_3201 = var_1;
    var_2._id_EB9B = 0;
    var_2._id_5400 = undefined;
    var_3 = getdvarint( "#x3de250bf4cdcd9cab", 0 ) || getdvarint( "#x398d84acbf2bee889", 0 );

    if ( var_3 )
    {
        _id_10B3( "intel", undefined, undefined, 100 );
        _id_10B3( "lmg_streak", undefined, undefined, 100 );
        _id_10B3( "uav", undefined, undefined, 80 );
        _id_10B3( "counter_spy_plane", undefined, undefined, 80 );
        _id_10B3( "mortar_barrage", undefined, undefined, 60 );
        _id_10B3( "glide_bomb", undefined, undefined, 60 );
        _id_10B3( "warmachine", undefined, undefined, 40 );
        _id_10B3( "attack_dogs", undefined, undefined, 10 );
    }
    else
    {
        _id_10B3( "intel", undefined, undefined, 100 );
        _id_10B3( "lmg_streak", undefined, undefined, 100 );
        _id_10B3( "guard_dog", undefined, undefined, 100 );
        _id_10B3( "uav", undefined, undefined, 80 );
        _id_10B3( "counter_spy_plane", undefined, undefined, 80 );
        _id_10B3( "mortar_barrage", undefined, undefined, 60 );
        _id_10B3( "glide_bomb", undefined, undefined, 60 );
        _id_10B3( "precision_airstrike", undefined, undefined, 40 );
        _id_10B3( "warmachine", undefined, undefined, 40 );
        _id_10B3( "attack_dogs", undefined, undefined, 10 );
    }

    game["dialog"]["airdrop_hijacked"] = "mp_glob_kill_bchr_cpea";
}

_id_816D()
{
    level._id_3E63._id_8E3B = [];
    level._id_3E63._id_8E34 = [];
    level._id_3E63._id_8E39 = [];
    var_0 = ::_id_8DB1;
    var_1 = ::_id_8DB2;
    var_2 = _id_6AE1( "killstreak" );
    var_2._id_0EBE = var_0;
    var_2._id_3201 = var_1;
    var_2 = _id_6AE1( "killstreak_no_owner" );
    var_2._id_0EBE = var_0;
    var_2._id_3201 = var_1;
    var_2._id_EB9B = 0;
    var_2._id_5400 = undefined;
    var_3 = 0;
    _id_10B3( "intel", undefined, undefined, 100 );
    _id_10B3( "uav", undefined, undefined, 100 );
    _id_10B3( "lmg_streak", undefined, undefined, 100 );
    _id_10B3( "counter_spy_plane", undefined, undefined, 100 );
    _id_10B3( "guard_dog", undefined, undefined, 100 );
    _id_10B3( "precision_airstrike", undefined, undefined, 100 );
    _id_10B3( "glide_bomb", undefined, undefined, 100 );
    _id_10B3( "toma_strike", undefined, undefined, 50 );
    _id_10B3( "warmachine", undefined, undefined, 50 );
    _id_10B3( "attack_dogs", undefined, undefined, 20 );
}

_id_81EA( var_0 )
{
    waittillframeend;
    var_1 = _id_077B::_id_F07F( _id_09AD::_id_940B(), var_0, 0 );
    _id_10B3( "bradley", undefined, undefined, var_1 );
}

_id_10B3( var_0, var_1, var_2, var_3 )
{
    level._id_3E63._id_8E34[var_0] = var_1;
    level._id_3E63._id_8E39[var_0] = var_2;
    level._id_3E63._id_8E3B[var_0] = var_3;
}

_id_6ABF( var_0, var_1 )
{
    var_2 = _func_020F();
    var_2._id_EA0F = var_0;
    var_2._id_EB9C = var_1;
    return var_2;
}

_id_AD41( var_0, var_1 )
{
    level._id_3E63._id_8E3B[var_0] = var_1;
}

_id_8DB1( var_0 )
{
    var_1 = self._id_432F;
    var_2 = level._id_3E63._id_8E34[var_1._id_EA0F];

    if ( isdefined( var_2 ) )
        _id_AD37( var_2 );

    var_3 = level._id_3E63._id_8E39[var_1._id_EA0F];

    if ( isdefined( var_3 ) )
        _id_AD49( var_3 );

    var_4 = var_1._id_EB9C;

    if ( isdefined( var_4 ) )
        _id_AD4C( var_4 );
}

_id_8DB2( var_0 )
{
    var_1 = self._id_432F._id_EA0F;
    var_2 = 0;

    switch ( var_1 )
    {
        case "bradley":
            if ( !_id_09AD::_id_940B() )
                var_1 = "pac_sentry";

            break;
        case "juggernaut":
            if ( !istrue( var_0._id_88C5 ) )
            {
                var_2 = 1;

                if ( _id_099D::_id_8A10( "airdrop", "applyImmediateJuggernaut" ) )
                    var_0 [[ _id_099D::_id_6D05( "airdrop", "applyImmediateJuggernaut" ) ]]( var_2 );
                else
                    var_0 _id_098F::_id_F78B( var_2 );
            }

            break;
    }

    if ( !istrue( var_2 ) )
    {
        if ( _id_099D::_id_8A10( "airdrop", "awardKillstreak" ) )
            var_0 thread [[ _id_099D::_id_6D05( "airdrop", "awardKillstreak" ) ]]( var_1, self._id_02F2, self );

        if ( _id_099D::_id_8A10( "airdrop", "showKillstreakSplash" ) )
            var_0 [[ _id_099D::_id_6D05( "airdrop", "showKillstreakSplash" ) ]]( var_1, undefined, 1 );
    }

    if ( isdefined( self._id_02F2 ) && var_0 == self._id_02F2 )
    {
        if ( _id_099D::_id_8A10( "sound", "trySayLocalSound" ) )
            level thread [[ _id_099D::_id_6D05( "sound", "trySayLocalSound" ) ]]( self._id_02F2, "airdrop_acquire" );
    }
    else if ( isdefined( self._id_045B ) )
    {
        if ( var_0._id_045B != self._id_045B )
        {
            if ( _id_099D::_id_8A10( "player", "giveUnifiedPoints" ) )
                var_0 [[ _id_099D::_id_6D05( "player", "giveUnifiedPoints" ) ]]( "hijacker" );

            if ( isdefined( self._id_02F2 ) )
            {
                if ( _id_099D::_id_8A10( "hud", "showSplash" ) )
                    self._id_02F2 [[ _id_099D::_id_6D05( "hud", "showSplash" ) ]]( "hijacked_airdrop", undefined, var_0 );
            }

            self._id_02F2 thread _id_0A64::_id_9120( "airdrop_hijacked" );
        }
        else
        {

        }
    }
}

_id_6CA4( var_0, var_1, var_2 )
{
    if ( !isdefined( var_2 ) )
        var_2 = "airdrop";

    var_2 = _id_6CA3( level._id_3E63._id_8E3B, var_0 );

    if ( var_1 _id_099B::_id_0C1B( "specialty_reaper" ) )
        _id_099B::_id_C0AF();

    return var_2;
}

_id_B157( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !isdefined( var_2 ) || var_2 == "random" )
        var_2 = _id_6CA4();

    var_5 = _id_077B::_id_F07F( isdefined( var_0 ), "killstreak", "killstreak_no_owner" );
    var_6 = _id_6ABF( var_2, 0 );
    var_7 = _id_B146( var_0, var_1, var_5, var_3, var_4, var_6 );

    if ( !isdefined( var_7 ) )
        return undefined;

    if ( isdefined( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "hud", "teamPlayerCardSplash" ) )
            level thread [[ _id_099D::_id_6D05( "hud", "teamPlayerCardSplash" ) ]]( "used_airdrop", var_0 );
    }

    return var_7;
}

_id_5017( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    if ( !isdefined( var_2 ) || var_2 == "random" )
        var_2 = _id_6CA4();

    var_6 = _id_077B::_id_F07F( isdefined( var_0 ), "killstreak", "killstreak_no_owner" );
    var_7 = _id_6ABF( var_2, 0 );
    var_8 = _id_5008( var_0, var_1, var_6, var_3, var_4, var_5, var_7 );

    if ( !isdefined( var_8 ) )
        return undefined;

    if ( isdefined( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "hud", "teamPlayerCardSplash" ) )
            level thread [[ _id_099D::_id_6D05( "hud", "teamPlayerCardSplash" ) ]]( "used_airdrop", var_0 );
    }

    return var_8;
}

_id_5019( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7 )
{
    if ( !isdefined( var_2 ) || var_2 == "random" )
        var_2 = _id_6CA4( undefined, var_0 );

    var_8 = _id_077B::_id_F07F( isdefined( var_0 ), "killstreak", "killstreak_no_owner" );
    var_9 = _id_6ABF( var_2, 0 );
    var_9._id_10313 = var_6;
    var_10 = _id_500A( var_0, var_1, var_8, var_3, var_4, var_5, var_9, var_7 );

    if ( !isdefined( var_10 ) )
        return undefined;
    else if ( !isdefined( var_10._id_3E79 ) || !isdefined( _id_077B::_id_1B84( var_10._id_3E79 ) ) )
        return undefined;

    if ( isdefined( var_0 ) )
    {
        var_0 thread _id_136F( var_7 );

        if ( _id_099D::_id_8A10( "hud", "teamPlayerCardSplash" ) )
            level thread [[ _id_099D::_id_6D05( "hud", "teamPlayerCardSplash" ) ]]( "used_airdrop", var_0 );
    }

    return var_10;
}

_id_136F( var_0, var_1 )
{
    self endon( "death_or_disconnect" );
    level endon( "game_ended" );

    if ( level._id_60D1 == "grnd" )
        return;

    var_2 = undefined;

    if ( _id_099D::_id_8A10( "sound", "playKillstreakDeployDialog" ) )
    {
        _id_076B::_id_7A8B( 0.75 );
        [[ _id_099D::_id_6D05( "sound", "playKillstreakDeployDialog" ) ]]( self, var_0._id_EA0F );
        var_2 = 1.5;
    }

    var_3 = var_0._id_EA0F;

    if ( isdefined( var_1 ) )
        var_3 = var_1;

    thread _id_099B::_id_B85C( "use_" + var_3, 1, var_2 );
}

_id_5018( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    if ( !isdefined( var_2 ) || var_2 == "random" )
        var_2 = _id_6CA4();

    var_7 = _id_077B::_id_F07F( isdefined( var_0 ), "killstreak", "killstreak_no_owner" );
    var_8 = _id_6ABF( var_2, 0 );
    var_8._id_10313 = var_6;
    var_9 = _id_5009( var_0, var_1, var_7, var_3, var_4, 30000, 30000, var_5, var_8 );

    if ( !isdefined( var_9 ) )
        return undefined;
    else if ( !isdefined( var_9._id_3E4B ) )
        return undefined;

    if ( isdefined( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "hud", "teamPlayerCardSplash" ) )
            level thread [[ _id_099D::_id_6D05( "hud", "teamPlayerCardSplash" ) ]]( "used_airdrop", var_0 );
    }

    return var_9._id_3E4B;
}

_id_F734( var_0 )
{
    var_1 = var_0._id_EA0F;
    var_2 = var_1;
    var_3 = undefined;

    if ( !isdefined( var_2 ) )
        var_2 = "airdrop";

    var_4 = 4;

    if ( _id_0999::_id_88E4() )
        var_4 = 10;

    var_5 = 1;

    if ( ( level._id_957C.size >= var_4 || level._id_59C1 >= var_4 ) && var_2 != "airdrop_mega" )
    {
        if ( _id_099D::_id_8A10( "hud", "showErrorMessage" ) )
            self [[ _id_099D::_id_6D05( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/MAX_AIRDROPS" );

        return 0;
    }
    else if ( _id_099D::_id_8A10( "killstreak", "currentActiveVehicleCount" ) && _id_099D::_id_8A10( "killstreak", "maxVehiclesAllowed" ) )
    {
        if ( [[ _id_099D::_id_6D05( "killstreak", "currentActiveVehicleCount" ) ]]() >= [[ _id_099D::_id_6D05( "killstreak", "maxVehiclesAllowed" ) ]]() || level._id_59C1 + var_5 >= [[ _id_099D::_id_6D05( "killstreak", "maxVehiclesAllowed" ) ]]() )
        {
            if ( _id_099D::_id_8A10( "hud", "showErrorMessage" ) )
                self [[ _id_099D::_id_6D05( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/TOO_MANY_VEHICLES" );

            return 0;
        }
    }

    var_6 = getdvarint( "scr_airDrop_sticky", 0 );

    if ( var_2 == "airdrop" && var_6 )
        var_0._id_47CD = _func_034C( "deploy_airdrop_mp_sticky" );

    return 1;
}

_id_1380( var_0, var_1 )
{
    if ( istrue( var_1 ) )
        thread _id_137B( var_0 );
}

_id_137B( var_0 )
{
    self endon( "disconnect" );
    self _meth_824A( "cancel_deploy", "+actionslot 3" );
    self _meth_824A( "cancel_deploy", "+actionslot 4" );
    self _meth_824A( "cancel_deploy", "+actionslot 5" );
    self _meth_824A( "cancel_deploy", "+actionslot 6" );
    var_1 = _id_077B::waittill_any_return( "cancel_deploy", "weapon_switch_started" );

    if ( !isdefined( var_1 ) )
        return;

    var_0 notify( "killstreak_finished_with_deploy_weapon" );
}

_id_1384( var_0 )
{
    var_0._id_1382 = var_0._id_EA0F;

    if ( _id_099D::_id_8A10( "vehicle", "incrementFauxVehicleCount" ) )
        [[ _id_099D::_id_6D05( "vehicle", "incrementFauxVehicleCount" ) ]]();

    var_1 = undefined;

    if ( _id_099D::_id_8A10( "airdrop", "getTargetMarker" ) )
        var_1 = self [[ _id_099D::_id_6D05( "airdrop", "getTargetMarker" ) ]]( var_0 );

    if ( !isdefined( var_1._id_96B8 ) )
    {
        if ( _id_099D::_id_8A10( "vehicle", "decrementFauxVehicleCount" ) )
            [[ _id_099D::_id_6D05( "vehicle", "decrementFauxVehicleCount" ) ]]();

        return 0;
    }

    if ( _id_099D::_id_8A10( "killstreak", "logKillstreakEvent" ) )
        self [[ _id_099D::_id_6D05( "killstreak", "logKillstreakEvent" ) ]]( var_0._id_1382, self._id_02EA );

    _id_1383( var_1, var_0._id_1382, var_0 );
    return 1;
}

_id_1383( var_0, var_1, var_2 )
{
    var_3 = _id_077B::_id_4FE0( var_0._id_96B8, 50, -200, ( 0, 0, 1 ) );
    var_3 = var_3 + ( 0, 0, 1 );
    var_4 = _func_0205( "script_model", var_3 );
    var_4 setmode( "offhand_wm_grenade_smoke" );
    var_4._id_0054 = ( 0, 90, 90 );
    var_5 = _func_0205( "script_model", var_3 );
    var_5 setmode( "ks_crate_marker_mp" );
    var_5 _meth_8373( "smoke", "on", 0 );

    if ( isdefined( var_0._id_04C5 ) )
        var_0._id_04C5 _meth_809A();
}

_id_F764()
{
    var_0 = _id_099B::_id_4034( "airdrop", self );
    return _id_F765( var_0 );
}

_id_F765( var_0 )
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    var_0._id_47CD = _func_034C( "s4_deploy_airdrop_mp" );
    var_1 = undefined;

    switch ( var_0._id_EA0F )
    {
        case "airdrop":
            var_1 = 1;
            break;
        default:
            var_1 = 0;
    }

    if ( var_1 )
    {
        if ( !_id_09BC::_id_C58D() )
        {
            _id_07B9::_id_DCBD( "KILLSTREAKS/AIR_SPACE_TOO_CROWDED" );
            return 0;
        }
    }

    if ( !_id_F734( var_0 ) )
    {
        if ( var_1 )
            _id_09BC::_id_396E();

        return 0;
    }

    if ( isdefined( level._id_8DD2 ) )
    {
        if ( !level [[ level._id_8DD2 ]]( var_0 ) )
        {
            if ( var_1 )
                _id_09BC::_id_396E();

            _id_07B9::_id_DCBD( "KILLSTREAKS/AIR_SPACE_TOO_CROWDED" );
            return 0;
        }
    }

    var_2 = _id_0990::_id_EA00( var_0, var_0._id_47CD, "grenade_fire", undefined, ::_id_1380, ::_id_137F, undefined, ::_id_1381 );

    if ( !istrue( var_2 ) )
    {
        if ( var_1 )
            _id_09BC::_id_396E();

        return 0;
    }

    if ( isdefined( level._id_8DAD ) )
    {
        if ( !level [[ level._id_8DAD ]]( var_0 ) )
            return 0;
    }

    return 1;
}

_id_137F( var_0, var_1, var_2 )
{
    var_0._id_1382 = var_0._id_EA0F;

    if ( _id_099D::_id_8A10( "killstreak", "incrementFauxVehicleCount" ) )
        [[ _id_099D::_id_6D05( "killstreak", "incrementFauxVehicleCount" ) ]]();

    var_2._id_02F2 = self;
    var_2 thread _id_137E( var_0._id_1382, undefined, var_0 );

    if ( _id_099D::_id_8A10( "killstreak", "logKillstreakEvent" ) )
        self [[ _id_099D::_id_6D05( "killstreak", "logKillstreakEvent" ) ]]( var_0._id_1382, self._id_02EA );

    var_0._id_137F = 1;
    var_0 notify( "killstreak_finished_with_deploy_weapon" );
    return "success";
}

_id_137E( var_0, var_1, var_2 )
{
    level endon( "game_ended" );
    var_3 = self._id_02F2._id_0054;
    self waittill( "explode", var_4 );
    var_5 = self._id_02F2;

    if ( !isdefined( var_5 ) )
    {
        if ( _id_099D::_id_8A10( "vehicle", "decrementFauxVehicleCount" ) )
            [[ _id_099D::_id_6D05( "vehicle", "decrementFauxVehicleCount" ) ]]();

        _id_09BC::_id_396E();
        return;
    }

    waitframe();

    if ( _id_099D::_id_8A10( "vehicle", "decrementFauxVehicleCount" ) )
        [[ _id_099D::_id_6D05( "vehicle", "decrementFauxVehicleCount" ) ]]();

    var_7 = undefined;

    if ( var_0 == "airdrop" )
        var_7 = _id_5019( var_5, var_5._id_045B, undefined, var_4, var_3 + ( 0, 180, 0 ), var_4, 1, var_2 );
    else if ( var_0 == "airdrop_multiple" )
    {
        if ( _id_099D::_id_8A10( "airdrop", "airdropMultipleDropCrates" ) )
            var_7 = [[ _id_099D::_id_6D05( "airdrop", "airdropMultipleDropCrates" ) ]]( var_5, var_5._id_045B, var_4, var_3 + ( 0, 180, 0 ), var_4, var_2 );
    }

    if ( !isdefined( var_7 ) )
    {
        if ( _id_099D::_id_8A10( "hud", "showErrorMessage" ) )
            var_5 [[ _id_099D::_id_6D05( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/VEHICLE_REFUND_KILLSTREAK" );

        if ( _id_099D::_id_8A10( "hud", "awardKillstreakFromStruct" ) )
            var_5 [[ _id_099D::_id_6D05( "killstreak", "awardKillstreakFromStruct" ) ]]( var_2._id_A2A3 );

        return;
    }

    var_5 _id_099B::_id_C13C( var_2 );
}

_id_1381( var_0 )
{
    if ( istrue( var_0._id_137F ) )
    {
        if ( isdefined( level._id_8DBA ) )
            level thread [[ level._id_8DBA ]]( var_0 );
    }

    if ( isdefined( var_0._id_1382 ) && !istrue( var_0._id_137F ) )
    {
        if ( _id_099D::_id_8A10( "vehicle", "decrementFauxVehicleCount" ) )
            [[ _id_099D::_id_6D05( "vehicle", "decrementFauxVehicleCount" ) ]]();
    }
}

_id_8130()
{
    var_0 = _id_6AE1( "battle_royale" );
    var_0._id_320E = &"MP/BR_CRATE";
    var_0._id_5400 = undefined;
    var_0._id_EB9B = 0;
    var_0._id_75CE = undefined;
    var_0._id_049F = -1;
    var_0._id_FE70 = 180;
    var_0._id_F221 = undefined;
    var_0._id_0EBE = ::_id_2B28;
    var_0._id_3201 = ::_id_2B29;
}

_id_690B( var_0 )
{
    var_1 = _func_020F();
    var_1._id_048F = var_0;
    return var_1;
}

_id_2B28( var_0 )
{
    if ( istrue( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "airdrop", "registerCrateForCleanup" ) )
            [[ _id_099D::_id_6D05( "airdrop", "registerCrateForCleanup" ) ]]( self );
    }
}

_id_2B29( var_0 )
{
    if ( _id_099D::_id_8A10( "airdrop", "makeItemsFromCrate" ) )
        self [[ _id_099D::_id_6D05( "airdrop", "makeItemsFromCrate" ) ]]( var_0 );
}

_id_4FF7( var_0 )
{
    var_1 = _id_077B::_id_F07F( _id_077B::_id_3A02(), "weapon", "attachment" );
    var_2 = _id_500A( undefined, undefined, "battle_royale", var_0, ( 0, _func_01B6( 360 ), 0 ), var_0, _id_690B( var_1 ) );

    if ( !isdefined( var_2 ) )
        return undefined;
    else if ( !isdefined( var_2._id_3E79 ) || !isdefined( _id_077B::_id_1B84( var_2._id_3E79 ) ) )
        return undefined;

    return var_2._id_3E4B;
}

_id_4FF6( var_0 )
{
    var_1 = _id_077B::_id_F07F( _id_077B::_id_3A02(), "weapon", "attachment" );
    var_2 = _id_5009( undefined, undefined, "battle_royale", var_0, ( 0, _func_01B6( 360 ), 0 ), 30000, 30000, var_0, _id_690B( var_1 ) );

    if ( !isdefined( var_2 ) )
        return undefined;
    else if ( !isdefined( var_2._id_3E4B ) )
        return undefined;

    return var_2._id_3E4B;
}

_id_8131()
{
    var_0 = _id_6AE1( "battle_royale_loadout" );
    var_0._id_320E = &"MP/BR_CRATE_LOADOUT";
    var_0._id_506A = "vm_equip_gen_care_package_00";
    var_0._id_5F99 = undefined;
    var_0._id_5400 = undefined;
    var_0._id_A1AD = undefined;
    var_0._id_EB9B = 0;
    var_0._id_75CE = undefined;
    var_0._id_049F = -1;
    var_0._id_FE70 = 180;
    var_0._id_F221 = undefined;
    var_0._id_5FA0 = 1;
    var_0._id_ADA0 = 0.5;
    var_0._id_AC8C = 0.5;
    var_0._id_0EBE = ::_id_2BBA;
    var_0._id_3201 = ::_id_2BBB;
    var_0._id_4820 = ::_id_2BBC;
    var_0._id_483C = 0;
    var_0._id_AAAB = 1;
}

_id_2BBA( var_0 )
{
    if ( istrue( var_0 ) )
    {
        if ( _id_099D::_id_8A10( "airdrop", "registerCrateForCleanup" ) )
            [[ _id_099D::_id_6D05( "airdrop", "registerCrateForCleanup" ) ]]( self );

        if ( _id_099D::_id_8A10( "airdrop", "brLoadoutCrateFirstActivation" ) )
            [[ _id_099D::_id_6D05( "airdrop", "brLoadoutCrateFirstActivation" ) ]]( self );
    }
}

_id_2BBB( var_0 )
{
    _id_6FEC( var_0 );
}

_id_2BBE( var_0 )
{
    if ( !isdefined( self._id_A78A ) )
        self._id_A78A = 0;

    if ( !isdefined( self._id_B7D6 ) )
        self._id_B7D6 = [];

    if ( !isdefined( self._id_B77D ) )
        self._id_B77D = [];

    self._id_B77D[var_0 getentitynumber()] = var_0;
    self._id_B7D6[self._id_B7D6.size] = var_0;
    self._id_A78A++;

    if ( isdefined( self._id_B71F ) )
    {
        foreach ( var_2 in self._id_B71F )
        {
            if ( isdefined( self._id_ACEB ) && isdefined( self._id_ACEB[var_2] ) && isdefined( self._id_ACEB[var_2]._id_B7D8 ) )
            {
                if ( self._id_ACEB[var_2]._id_B7D8.size == 1 && self._id_ACEB[var_2]._id_B7D8[0] == var_0 )
                {
                    if ( _id_099D::_id_8A10( "airdrop", "outlineDisable" ) )
                        [[ _id_099D::_id_6D05( "airdrop", "outlineDisable" ) ]]( var_2, self );

                    self._id_B71F = _id_077B::_id_1B96( self._id_B71F, var_2 );
                    break;
                }
            }
        }
    }

    if ( self._id_A78A >= level._id_EF67[var_0._id_045B]["teamCount"] )
    {
        if ( isdefined( self._id_B71F ) )
        {
            foreach ( var_5 in self._id_B71F )
            {
                if ( _id_099D::_id_8A10( "airdrop", "outlineDisable" ) )
                    [[ _id_099D::_id_6D05( "airdrop", "outlineDisable" ) ]]( var_5, self );
            }
        }

        if ( isdefined( self._id_35E2 ) && isdefined( self._id_35E2._id_84D5 ) )
            self._id_35E2._id_84D5 = 0;

        thread _id_4822();
    }
}

_id_2BBC( var_0 )
{
    if ( _id_099D::_id_8A10( "airdrop", "brOnLoadoutCrateDestroyed" ) )
        [[ _id_099D::_id_6D05( "airdrop", "brOnLoadoutCrateDestroyed" ) ]]( var_0 );
}

_id_6FEC( var_0 )
{
    if ( _id_099D::_id_8A10( "airdrop", "br_giveDropBagLoadout" ) )
        [[ _id_099D::_id_6D05( "airdrop", "br_giveDropBagLoadout" ) ]]( var_0 );
}

_id_4FFC( var_0, var_1, var_2 )
{
    return _id_5008( undefined, var_0, "battle_royale_loadout", var_1, ( 0, _func_01B6( 360 ), 0 ), var_2 );
}

_id_812F()
{
    var_0 = _id_6AE1( "battle_royale_c130_loot" );
    var_0._id_320E = &"MP/DMZ_LOOT_CRATE_CAPTURE";
    var_0._id_506A = "vm_equip_gen_care_package_00";
    var_0._id_5F99 = undefined;
    var_0._id_5400 = undefined;
    var_0._id_A1AD = undefined;
    var_0._id_EB9B = 0;
    var_0._id_75CE = undefined;
    var_0._id_049F = -1;
    var_0._id_FE70 = 180;
    var_0._id_F221 = 600;
    var_0._id_5FA0 = 1;
    var_0._id_ADA0 = 0.5;
    var_0._id_AC8C = 0.5;
    var_0._id_0EBE = ::_id_2B1A;
    var_0._id_3201 = ::_id_2B1B;
    var_0._id_4820 = ::_id_2B1C;
    var_0._id_3E78 = ::_id_2B1D;
    var_0._id_483C = 1;
}

_id_2B1A( var_0 )
{

}

_id_2B1B( var_0 )
{
    self _meth_8373( "objective_map", "inactive", 0 );

    if ( _id_099D::_id_8A10( "br_c130Airdrop", "c130Airdrop_onCrateUse" ) )
        self [[ _id_099D::_id_6D05( "br_c130Airdrop", "c130Airdrop_onCrateUse" ) ]]( var_0 );

    if ( _id_099D::_id_8A10( "br_c130Airdrop", "dmzTut_crateUsed" ) )
        self [[ _id_099D::_id_6D05( "br_c130Airdrop", "dmzTut_crateUsed" ) ]]( var_0 );

    if ( isdefined( self._id_DE52 ) )
    {
        self._id_DE52 _meth_8373( "smoke_signal", "off", 0 );
        self._id_DE52 _meth_809A();
    }

    if ( isdefined( level._id_2E18 ) )
        level._id_2E18 = _id_077B::_id_1B96( level._id_2E18, self );
}

_id_2B1C( var_0 )
{
    self _meth_8373( "objective_map", "inactive", 0 );

    if ( isdefined( self._id_DE52 ) )
    {
        self._id_DE52 _meth_8373( "smoke_signal", "off", 0 );
        self._id_DE52 _meth_809A();
    }

    if ( isdefined( level._id_2E18 ) )
        level._id_2E18 = _id_077B::_id_1B96( level._id_2E18, self );
}

_id_2B1D()
{
    self _meth_8373( "crate_audio", "detach", 0 );
}

_id_4FF5( var_0, var_1, var_2 )
{
    var_3 = 250;
    var_4 = level._id_2E01;
    var_5 = 1000;
    var_6 = 10500;
    var_7 = 7500;
    var_8 = 3000;
    var_9 = var_1 + ( 0, 0, var_5 );
    var_10 = _id_3F95( undefined, undefined, "battle_royale_c130_loot", var_0, ( 0, 0, 0 ), var_1, undefined, 0 );

    if ( isdefined( var_10 ) )
    {
        var_10._id_DDB1 = 1;

        if ( var_9[2] < var_0[2] )
        {
            var_11 = undefined;
            var_12 = distance( var_0, var_9 );

            if ( var_12 >= var_6 )
                var_11 = "brc130_drop_high";
            else if ( var_12 >= var_7 )
                var_11 = "brc130_drop_med";
            else if ( var_12 >= var_8 )
                var_11 = "brc130_drop_low";

            if ( isdefined( var_11 ) )
            {
                var_13 = 1000;
                var_14 = _func_0205( "script_model", var_9 + ( 0, 0, var_13 ) );
                var_14._id_0054 = var_2;
                var_14 setmode( "tag_origin" );
                var_15 = _func_0205( "script_model", var_10._id_02EA );
                var_15._id_0054 = var_10._id_0054;
                var_15 setmode( "veh8_mil_lnd_carepackage_parachute_br" );
                var_10 thread _id_10A9A();
                var_15 thread _id_10A9B( var_14 );
            }
            else
                var_10 _id_3E77();
        }
        else
            var_10 _id_3E77();

        var_16 = "cashdrop_common";
        var_17 = getdvarint( "scr_dmz_airdrop_ingame_obj", 1 );

        if ( var_17 )
            var_16 = "cashdrop_common_world";

        var_10 _meth_8373( "objective_map", var_16, 0 );
        var_10 _meth_8373( "crate_audio", "parachuting", 0 );
        var_10._id_DE52 = _func_0205( "script_model", var_1 );
        var_10._id_DE52 setmode( "ks_airdrop_crate_br" );
        var_10._id_DE52 _meth_8373( "smoke_signal", "on", 0 );
    }

    return var_10;
}

_id_10A9A()
{
    self endon( "death" );
    wait( self._id_1884 );

    if ( isdefined( self ) )
    {
        self _meth_83EB();
        _id_3E77();
    }
}

_id_10A9B( var_0 )
{
    self endon( "death" );
    wait( self._id_1884 );

    if ( isdefined( self ) )
        self _meth_809A();

    if ( isdefined( var_0 ) )
        var_0 _meth_809A();
}

_id_8132()
{
    var_0 = _id_6AE1( "battle_royale_chopper_loot" );
    var_0._id_320E = &"MP/DMZ_PLUNDER_CRATE_CAPTURE";
    var_0._id_506A = "vm_equip_gen_care_package_00";
    var_0._id_5F99 = undefined;
    var_0._id_5400 = undefined;
    var_0._id_A1AD = undefined;
    var_0._id_EB9B = 0;
    var_0._id_75CE = undefined;
    var_0._id_049F = -1;
    var_0._id_FE70 = 180;
    var_0._id_F221 = 600;
    var_0._id_5FA0 = 1;
    var_0._id_ADA0 = 0.5;
    var_0._id_AC8C = 0.5;
    var_0._id_0EBE = ::_id_2BC2;
    var_0._id_3201 = ::_id_2BC3;
    var_0._id_4820 = ::_id_2BC4;
    var_0._id_483C = 1;
}

_id_2BC2( var_0 )
{

}

_id_2BC3( var_0 )
{
    self _meth_8373( "objective_map", "inactive", 0 );

    if ( _id_099D::_id_8A10( "br_lootchopper", "lootChopper_onCrateUse" ) )
        self [[ _id_099D::_id_6D05( "br_lootchopper", "lootChopper_onCrateUse" ) ]]( var_0 );

    if ( isdefined( self._id_DE52 ) )
    {
        self._id_DE52 _meth_8373( "smoke_signal", "off", 0 );
        self._id_DE52 _meth_809A();
    }
}

_id_2BC4( var_0 )
{
    self _meth_8373( "objective_map", "inactive", 0 );

    if ( isdefined( self._id_DE52 ) )
    {
        self._id_DE52 _meth_8373( "smoke_signal", "off", 0 );
        self._id_DE52 _meth_809A();
    }
}

_id_4FFE( var_0, var_1 )
{
    var_2 = _id_5008( undefined, undefined, "battle_royale_chopper_loot", var_0, ( 0, _func_01B6( 360 ), 0 ), var_1 );

    if ( isdefined( var_2 ) )
    {
        var_2._id_DDB1 = 1;
        var_3 = "cashdrop_common";
        var_4 = getdvarint( "scr_dmz_airdrop_ingame_obj", 1 );

        if ( var_4 )
            var_3 = "cashdrop_common_world";

        var_2 _meth_8373( "objective_map", var_3, 0 );
        var_2._id_DE52 = _func_0205( "script_model", var_1 );
        var_2._id_DE52 setmode( "ks_airdrop_crate_br" );
        var_2._id_DE52 _meth_8373( "smoke_signal", "on", 0 );
    }

    return var_2;
}

_id_8258()
{
    var_0 = _id_6AE1( "esc_cache" );
    var_0._id_320E = &"MP/ESC_CACHE_USE_HINT";
    var_0._id_FED9 = "tag_use";
    var_0._id_FEAE = 200;
    var_0._id_FE70 = 160;
    var_0._id_049F = 0;
    var_0._id_5F99 = "military_crate_large_stackable_01";
    var_0._id_5400 = undefined;
    var_0._id_A1AD = undefined;
    var_0._id_EB9B = 0;
    var_0._id_75CE = undefined;
    var_0._id_049F = -10000;
    var_0._id_75CE = undefined;
    var_0._id_9F0C = undefined;

    if ( _id_099D::_id_8A10( "airdrop", "captureLootCacheCallback" ) )
        var_0._id_3201 = [[ _id_099D::_id_6D05( "airdrop", "captureLootCacheCallback" ) ]]();

    var_0._id_483C = 0;
    var_0._id_AAAB = 1;
    var_0._id_3211 = undefined;
    var_0._id_4845 = undefined;
    var_0._id_F221 = undefined;
}

_id_6C55( var_0 )
{
    var_1 = _func_020F();
    var_1._id_3BC7 = var_0;
    return var_1;
}

_id_B166( var_0, var_1, var_2 )
{
    var_3 = _id_B146( undefined, undefined, "esc_cache", var_1, var_2, _id_6C55( var_0 ) );
    return var_3;
}

_id_811E()
{
    level._id_3E63._id_1B61 = [];
    level._id_3E63._id_1AF6 = [];
    var_0 = _id_6AE1( "arm_no_owner" );
    var_0._id_0EBE = ::_id_1AF7;
    var_0._id_3201 = ::_id_1AF8;
    var_0._id_EB9B = 0;
    var_0._id_5400 = undefined;
    var_0._id_75D3 = 5000;
    var_0._id_F221 = 180;
    _id_1064( "uav", undefined, 5, 10 );
    _id_1064( "manual_turret", undefined, 5, 5 );
    _id_1064( "cruise_predator", undefined, 4, 40 );
    _id_1064( "scrambler_drone_guard", undefined, 4, 20 );
    _id_1064( "precision_airstrike", undefined, 3, 60 );
    _id_1064( "toma_strike", undefined, 2, 40 );
    _id_1064( "chopper_gunner", undefined, 2, 30 );
    _id_1064( "pac_sentry", undefined, 2, 30 );
    _id_1064( "gunship", undefined, 2, 30 );
    thread _id_811F();
}

_id_811F()
{
    waittillframeend;
    var_0 = _id_077B::_id_F07F( _id_09AD::_id_940B(), 50, 0 );
    _id_1064( "bradley", undefined, 4, var_0 );
}

_id_1064( var_0, var_1, var_2, var_3 )
{
    level._id_3E63._id_1AF9[var_0] = var_2;
    level._id_3E63._id_1B61[var_0] = var_3;
    level._id_3E63._id_1AF6[var_0] = var_1;
}

_id_68B1( var_0 )
{
    var_1 = _func_020F();
    var_1._id_EA0F = var_0;
    return var_1;
}

_id_1AF7( var_0 )
{
    var_1 = self._id_432F;
    var_2 = level._id_3E63._id_1AF6[var_1._id_EA0F];

    if ( isdefined( var_2 ) )
        _id_AD37( var_2 );
}

_id_1AF8( var_0 )
{
    if ( _id_099D::_id_8A10( "killstreak", "giveKillstreak" ) )
        var_0 thread [[ _id_099D::_id_6D05( "killstreak", "giveKillstreak" ) ]]( self._id_432F._id_EA0F, 0, 0, self._id_02F2 );
}

_id_812C()
{
    var_0 = _id_6AE1( "base_nuke" );
    var_0._id_0EBE = ::_id_228B;
    var_0._id_3201 = ::_id_228C;
    var_0._id_EB9B = 0;
    var_0._id_5400 = undefined;
    var_0._id_75D3 = 5000;
    var_0._id_75CE = "icon_waypoint_bomb";
    var_0._id_F221 = 180;
    var_0._id_9F0C = "splash_icon_nuke";
    var_0._id_ADA0 = 5;
    var_0._id_AC8C = 5;
    var_0._id_320E = &"MP/ARMSRACE_CRATE_PICKUP";
}

_id_228B( var_0 )
{

}

_id_228C( var_0 )
{
    var_1 = 400;
    var_2 = 50;
    var_3 = 256;
    var_4 = var_3 * var_3;
    var_5 = [];
    var_6 = var_0._id_0309["team"];

    foreach ( var_8 in level._id_B758 )
    {
        if ( distancesquared( var_8._id_02EA, var_0._id_02EA ) <= var_4 && var_8._id_0309["team"] == var_6 )
            var_5[var_5.size] = var_8;
    }

    if ( var_5.size > 0 && _id_099D::_id_8A10( "game", "givePlayerCash" ) )
    {
        var_10 = _func_0147( var_1 / var_5.size, var_2 );

        foreach ( var_12 in var_5 )
            var_12 [[ _id_099D::_id_6D05( "game", "givePlayerCash" ) ]]( var_10 );
    }

    var_0._id_A719 = 1;

    if ( _id_099D::_id_8A10( "game", "checkBaseNukeCrateCarrier" ) && [[ _id_099D::_id_6D05( "game", "checkBaseNukeCrateCarrier" ) ]]( var_0._id_02EA, undefined ) )
        return;

    var_0._id_9F0C = "splash_icon_nuke";
    var_0 _id_3FF0();

    if ( _id_099D::_id_8A10( "game", "monitorNukeCrateCarrier" ) )
        var_0 thread [[ _id_099D::_id_6D05( "game", "monitorNukeCrateCarrier" ) ]]();

    var_0 iprintlnbold( "Return the Nuke Crate to an ally base to nuke an enemy base!" );
}

_id_6C9D( var_0 )
{
    var_1 = _id_68B2( var_0 );
    var_2 = _id_6CA3( level._id_3E63._id_1B61, var_1 );
    return var_2;
}

_id_68B2( var_0 )
{
    var_1 = level._id_45B2;
    var_2 = undefined;

    if ( var_1 > 1 )
    {
        var_2 = [];

        foreach ( var_5, var_4 in level._id_3E63._id_1AF9 )
        {
            if ( var_1 > var_4 )
                var_2[var_2.size] = var_5;
        }
    }

    return var_2;
}

_id_4FEC( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !isdefined( var_1 ) || var_1 == "random" )
        var_1 = _id_6C9D( var_0 );

    var_5 = _id_68B1( var_1 );
    var_6 = _id_500A( undefined, var_0, "arm_no_owner", var_2, var_3, var_4, var_5 );

    if ( !isdefined( var_6 ) )
        return undefined;
    else if ( !isdefined( var_6._id_3E79 ) || !isdefined( _id_077B::_id_1B84( var_6._id_3E79 ) ) )
        return undefined;

    foreach ( var_8 in var_6._id_3E79 )
        return var_8;
}
