// S4 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_021D()
{
    _id_0A28::_id_C25C( "hover_jet", ::_id_F788 );
    level._id_7AF5 = [];
    _id_0A86::_id_D41E( "hover_jet", 12 );

    if ( _id_099D::_id_8A10( "vehicle_damage", "setWeaponHitDamageDataForVehicle" ) )
        [[ _id_099D::_id_6D05( "vehicle_damage", "setWeaponHitDamageDataForVehicle" ) ]]( "thermite_bolt_mp", 1, "hover_jet" );

    if ( _id_099D::_id_8A10( "vehicle_damage", "setVehicleHitDamageDataForWeapon" ) )
        [[ _id_099D::_id_6D05( "vehicle_damage", "setVehicleHitDamageDataForWeapon" ) ]]( "hover_jet", 24, "thermite_bolt_mp" );

    _id_7F9D();
    _id_7F9E();
    level._id_7D85 = 0;
    level._id_7D8C["allies"] = 0;
    level._id_7D8C["axis"] = 0;
}

#using_animtree("mp_vehicles_always_loaded");

_id_7F9D()
{
    level._id_CC24["hover_jet"]["airstrike_flyby"] = %mp_halfa_flyin;
    level._id_CC24["hover_jet"]["exit"] = %mp_halfa_exit;
}

_id_7F9E()
{
    game["dialog"]["hover_jet_move"] = "hover_jet_acknowledge";
    game["dialog"]["hover_jet_guard"] = "hover_jet_guard";
    game["dialog"]["hover_jet_flares"] = "hover_jet_flares";
    game["dialog"]["hover_jet_damage_heavy"] = "hover_jet_health_low";
    game["dialog"]["hover_jet_damage_med"] = "hover_jet_health_med";
    game["dialog"]["hover_jet_damage_light"] = "hover_jet_health_high";
    game["dialog"]["hover_jet_crash"] = "hover_jet_crash";
    game["dialog"]["hover_jet_attack_air"] = "hover_jet_air_target";
}

_id_10D90( var_0 )
{
    _id_0A2B::_id_E6E1();
    return 1;
}

_id_F787()
{
    var_0 = _id_099B::_id_4034( "hover_jet", self );
    return _id_F788( var_0 );
}

_id_F788( var_0 )
{
    var_1 = self._id_045B;

    if ( !_id_09BC::_id_C58D() )
    {
        _id_07B9::_id_DCBD( "KILLSTREAKS/AIR_SPACE_TOO_CROWDED" );
        return 0;
    }

    level._id_7D85++;
    var_2 = 1;

    if ( _id_0999::_id_88E4() )
        var_2 = 2;

    if ( level._id_7AF5.size >= var_2 || level._id_7AF5.size + level._id_7D85 > var_2 )
    {
        _id_07B9::_id_DCBD( "KILLSTREAKS/AIR_SPACE_TOO_CROWDED" );
        level._id_7D85--;
        _id_09BC::_id_396E();
        return 0;
    }

    if ( _id_0999::_id_88E4() && level._id_EF62 )
    {
        var_3 = 1;
        level._id_7D8C[var_1]++;

        if ( _id_099B::_id_6B8D( var_1, level._id_7AF5 ) + level._id_7D8C[var_1] > var_3 )
        {
            level._id_7D85--;
            level._id_7D8C[var_1]--;

            if ( _id_099D::_id_8A10( "hud", "showErrorMessage" ) )
                [[ _id_099D::_id_6D05( "hud", "showErrorMessage" ) ]]( "KILLSTREAKS/MAX_FRIENDLY_VTOL_JET" );

            _id_09BC::_id_396E();
            return 0;
        }
    }

    var_4 = _id_0D70( var_0 );
    var_4 = istrue( var_4 );
    level._id_7D85--;

    if ( _id_0999::_id_88E4() && level._id_EF62 )
        level._id_7D8C[var_1]--;

    if ( !var_4 )
        _id_09BC::_id_396E();

    return var_4;
}

_id_0D70( var_0 )
{
    level endon( "game_ended" );
    self endon( "disconnect" );

    if ( isdefined( level._id_8DD2 ) )
    {
        if ( !level [[ level._id_8DD2 ]]( var_0 ) )
            return 0;
    }

    var_1 = _id_0990::_id_EA01( var_0, _func_034C( "ks_remote_map_mp" ), 1, ::_id_10D90 );

    if ( !istrue( var_1 ) )
        return 0;

    if ( isdefined( level._id_8DAD ) )
    {
        if ( !level [[ level._id_8DAD ]]( var_0 ) )
            return 0;
    }

    var_2 = _id_7AD4( var_0, 1 );

    if ( !isdefined( var_2 ) )
        return 0;

    var_0 notify( "killstreak_finished_with_deploy_weapon" );
    thread _id_E6B8( self, var_0, var_2 );
    var_3 = undefined;

    if ( _id_099D::_id_8A10( "sound", "playKillstreakDeployDialog" ) )
    {
        [[ _id_099D::_id_6D05( "sound", "playKillstreakDeployDialog" ) ]]( self, var_0._id_EA0F );
        var_3 = 2.0;
    }

    thread _id_099B::_id_B85C( "use_" + var_0._id_EA0F, 1, var_3 );
    _id_06BB::_id_F737( level._id_9B9D, "hover_jet", self._id_02EA );
    thread _id_07BA::_id_EF8A( "used_hover_jet", self );
    return 1;
}

_id_7AD4( var_0, var_1 )
{
    _id_06BB::_id_156B( 0 );
    self _meth_867D( "mp_killstreak_overlay" );
    var_2 = _id_0A2B::_id_6D00( var_0, var_1 );

    if ( !isdefined( var_2 ) )
    {
        _id_06BB::_id_156B( 1 );
        self _meth_867E( "mp_killstreak_overlay" );
        return undefined;
    }

    _id_06BB::_id_156B( 1 );
    self _meth_867E( "mp_killstreak_overlay" );
    return var_2;
}

_id_E6B8( var_0, var_1, var_2 )
{
    level endon( "game_ended" );
    var_3 = _id_099B::_id_6ABC();
    var_4 = 24000;
    var_5 = 6500;
    var_6 = 3250;
    var_7 = 1500;
    var_8 = ( 0, 0, 0 );
    var_9 = 1500;
    var_10 = var_0._id_0054;
    var_11 = 1;

    if ( isdefined( var_3 ) )
        var_6 = var_3._id_02EA[2] + 750;

    var_12 = _id_0999::_id_6AF9();

    if ( isdefined( var_12 ) && var_12 == "locale_6" )
        var_6 = var_6 + 500;

    var_14 = var_2[0]._id_96B8;
    var_10 = _id_0982::_id_2FB2( var_0, var_14, var_6 );
    var_15 = _id_0982::_id_6A2F( var_14, var_10, var_4, var_3, var_6, var_5, var_9, var_1._id_EA0F, var_11 );
    var_16 = var_15["startPoint"];
    var_17 = var_15["endPoint"];
    var_18 = "veh8_mil_air_halfa_mp";

    if ( _id_099C::_id_6C48( var_0 ) )
        var_18 = "veh8_mil_air_halfa_east_mp";

    _id_09BC::_id_396E();
    var_19 = _id_09BC::_id_0D54( var_0, var_16, var_10, "veh_hover_jet_mp", var_18 );

    if ( !isdefined( var_19 ) )
        return;

    var_20 = 45;
    var_19._id_03C7 = 250;
    var_19._id_0E1F = 175;
    var_19._id_01FF = 2500;
    var_19._id_027F = 2500;
    var_19._id_0054 = _func_025B( var_10 );
    var_19._id_935B = var_20;
    var_19._id_045B = var_0._id_045B;
    var_19._id_02F2 = var_0;
    var_19._id_EA0B = var_1;
    var_19._id_EA0F = var_1._id_EA0F;
    var_19._id_5C6A = 1;
    var_19._id_C787 = var_14;
    var_19._id_419D = 0;
    var_19._id_5D24 = var_6;
    var_19._id_7ABD = var_7;
    var_19._id_9F67 = 6;
    var_19._id_0309["team"] = var_19._id_045B;
    var_19._id_24A9 = undefined;
    var_19._id_24A8 = undefined;
    var_19._id_5CD2 = var_15["directionAngles"];
    var_19 _meth_834A( 0, 90 );
    var_19 _meth_8436( var_19._id_03C7, var_19._id_0E1F );
    var_19 sethintstring( 50, 100, 50 );
    var_19 _meth_8395( 0.05 );
    var_19 _meth_83BA( 45, 25, 25, 0.5 );
    var_19 setorigin( var_19._id_02F2 );
    var_19 _meth_82F0( 1 );
    var_19 _meth_8356( 700 );
    var_19 _meth_83A5( var_19._id_045B );
    level._id_7AF5[level._id_7AF5.size] = var_19;
    var_19 _id_0A6F::_id_112C( var_1._id_EA0F, "Killstreak_Air", var_19._id_02F2, 0, 1, 100 );
    var_19 _meth_8373( "blinking_lights", "on", 0 );
    var_19 _meth_8373( "thrusters", "active", 0 );
    var_19 _meth_8373( "contrails", "on", 0 );
    var_19._id_F81C = _func_0210( "misc_turret", var_19 gettagorigin( "tag_turret" ), "hover_jet_turret_mp" );
    var_19._id_F81C setmode( "veh8_mil_air_halfa_turret" );
    var_19._id_F81C._id_02F2 = var_19._id_02F2;
    var_19._id_F81C._id_045B = var_19._id_045B;
    var_19._id_F81C._id_0054 = var_19._id_0054;
    var_19._id_F81C._id_EA0B = var_1;
    var_19._id_F81C _meth_820B( var_19, "tag_turret", ( 0, 0, 5 ), ( 0, 0, 0 ) );
    var_19._id_F81C _meth_839F( var_19._id_045B );
    var_19._id_F81C _meth_839C( 0 );
    var_19._id_F81C _meth_834F( "manual_target" );
    var_19._id_F81C _meth_8376( var_19._id_02F2 );
    var_19._id_F81C _meth_8309( 45 );
    var_19._id_F81C _meth_8223();
    var_19._id_F81C _meth_8330( 360 );
    var_19._id_F81C _meth_8371( 360 );
    var_19._id_F81C _meth_82EF( 90 );
    var_19._id_F81C _meth_8394( 90 );
    var_19._id_F81C _meth_8301( 0.5, "pitch" );
    var_19._id_F81C _meth_8301( 0.5, "yaw" );
    var_19._id_F81C _meth_8300( 0.65 );
    var_19._id_8D49 = _func_0205( "script_model", var_19._id_F81C gettagorigin( "bi_center" ) );
    var_19._id_8D49 _meth_820B( var_19, "tag_origin", ( -500, 0, 500 ), ( 0, 0, 0 ) );
    var_19._id_F81C.groundpos = _func_0205( "script_model", var_19._id_02EA );
    var_19._id_F81C.groundpos setmode( "tag_origin" );
    var_19._id_F81C.groundpos _meth_80BE();

    if ( _id_099D::_id_8A10( "killstreak", "addToActiveKillstreakList" ) )
        var_19 [[ _id_099D::_id_6D05( "killstreak", "addToActiveKillstreakList" ) ]]( var_1._id_EA0F, "Killstreak_Air", var_0, 0, 1, 100 );

    var_19._id_1887 = var_1._id_EA0F;
    var_19._id_CBC3 = _func_0205( "script_model", var_19._id_C787 * ( 1, 1, 0 ) + ( 0, 0, var_6 ) );
    var_19._id_CBC3._id_0054 = var_19._id_0054;
    var_19._id_CBC3 setmode( "tag_origin" );
    var_19 thread _id_7AD0( var_14 );
    var_19 _id_7AE1();
    var_24 = _func_0079( level._id_CC24[var_19._id_1887]["airstrike_flyby"] );
    var_25 = _id_077B::_id_65D2( level._id_CC24[var_19._id_1887]["airstrike_flyby"], "contrail_off" );
    var_19._id_CBC3 thread _id_069D::_id_181D( var_19, "airstrike_flyby" );
    var_19 thread _id_7AC7( var_25, "contrails", "off" );
    var_19 thread _id_7AD6();
    var_19 thread _id_7AEE();
    var_19 _id_07E9::_id_C2A4( "Killstreak_Air", self );
    var_19 _id_0A6F::_id_8D9E( var_1._id_EA0F, "destroyed_hover_jet", undefined, "timeout_hover_jet", "callout_destroyed_hover_jet" );
    var_19 _id_0A6F::_id_8DA8( var_1._id_EA0F );
    var_19 _id_0A6F::_id_8DA7( var_1._id_EA0F, ::_id_7ADC );
    var_19 _id_0A6F::_id_8DA6( var_1._id_EA0F, ::_id_7AD5 );
    var_19 thread _id_0A1B::_id_5C5F( ::_id_7AD7 );
    _id_076B::_id_7A8B( var_24 );

    if ( !isdefined( var_19 ) )
        return;

    if ( isdefined( var_19._id_CBC3 ) )
        var_19._id_CBC3 _meth_809A();

    var_19 _id_E6B9( var_1 );
}

_id_7AC7( var_0, var_1, var_2 )
{
    self endon( "death" );
    self endon( "crashing" );
    level endon( "game_ended" );
    _id_076B::_id_7A8B( var_0 );
    self _meth_8373( var_1, var_2, 0 );
}

_id_7AE1()
{
    thread _id_077B::_id_46C3( 0.05, ::_id_7ADF );
    thread _id_077B::_id_46C3( 6, ::_id_7AE0 );
    thread _id_077B::_id_46C3( 14, ::_id_7AE2 );
}

_id_7ADF()
{
    self _meth_827D( "ks_hoverjet_approach" );
}

_id_7AE0()
{
    self _meth_827D( "ks_hoverjet_flyby" );
}

_id_7AE2()
{
    self _meth_827D( "ks_hoverjet_return" );
}

_id_7AD0( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    var_1 = _id_077B::_id_65D2( level._id_CC24["hover_jet"]["airstrike_flyby"], "attack" );
    var_2 = var_1 - 4;
    _id_076B::_id_7A8B( var_2 );
    var_3 = [ "physicscontents_clipshot", "physicscontents_missileclip" ];
    var_4 = _func_02C4( var_3 );
    var_5 = self._id_0054 * ( 0, 1, 0 );
    var_6 = anglestoforward( var_5 );
    var_7 = anglestoright( var_5 );
    var_8 = [ var_0 - var_6 * 2250 + var_7 * 750, var_0 - var_6 * 1500 - var_7 * 750, var_0 - var_6 * 750 + var_7 * 250, var_0 - var_7 * 250, var_0 + var_6 * 750 + var_7 * 750, var_0 + var_6 * 1500 - var_7 * 750, var_0 + var_6 * 2250 + var_7 * 250, var_0 + var_6 * 3000 - var_7 * 250 ];
    var_9 = [ "tag_right_aphid_missile", "tag_left_aphid_missile", "tag_right_archer_missile", "tag_left_archer_missile" ];
    var_10 = 0;
    var_11 = [];

    foreach ( var_22, var_13 in var_8 )
    {
        var_14 = var_13 + ( 0, 0, 10000 );
        var_15 = var_13 - ( 0, 0, 10000 );
        var_16 = _id_077A::_id_C042( var_14, var_15, level._id_33D8, var_4 );
        var_17 = _id_06BB::_id_B7AC( var_16["position"], 1000 );
        var_18 = _id_7ACC( var_17, var_11 );
        var_19 = self gettagorigin( var_9[var_10] ) + anglestoforward( self gettagangles( var_9[var_10] ) ) * 300;
        var_20 = _id_09A2::_id_0C2D( _func_034C( "hover_jet_proj_mp" ), var_19, var_16["position"], self._id_02F2 );
        var_20._id_8D49 = _func_0205( "script_model", var_20._id_02EA );
        var_20._id_8D49 _meth_820B( var_20, "tag_origin", ( -100, 0, 500 ), ( 0, 0, 0 ) );
        var_20._id_8D49 thread _id_7ADB( var_16["position"], var_20._id_0054 );
        var_20._id_EA0B = self._id_EA0B;
        self._id_EA0B._id_DA5E++;
        thread _id_7ACD( var_10 + 1 );

        if ( isdefined( var_18 ) )
        {
            var_13 = var_18._id_02EA;
            var_11[var_11.size] = var_18;
            thread _id_7AC5( var_20, 0.05, var_18 );
        }

        wait 0.5;
        var_10++;

        if ( var_10 > var_9.size - 1 )
            var_10 = 0;
    }

    var_11 = undefined;
}

_id_7ADB( var_0, var_1 )
{
    self endon( "death" );
    _id_076B::_id_7A8B( 2 );
    self _meth_8415();
    self _meth_823B( var_0 - anglestoforward( var_1 ) * 750, 6 );
    _id_076B::_id_7A8B( 7 );
    self _meth_809A();
}

_id_7ACD( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    self _meth_8373( "fire_missile_" + var_0, "on", 0 );
    _id_076B::_id_7A8B( 0.5 );
    self _meth_8373( "fire_missile_" + var_0, "off", 0 );
}

_id_7ACC( var_0, var_1 )
{
    var_2 = undefined;

    foreach ( var_4 in var_0 )
    {
        if ( level._id_EF62 && var_4._id_045B == self._id_045B )
            continue;

        if ( var_4 == self._id_02F2 )
            continue;

        if ( _id_077B::_id_1B78( var_1, var_4 ) )
            continue;

        if ( var_4 scripts\mp\tac_ops\hostage_utility::_id_0BF6( "specialty_blindeye" ) )
            continue;

        var_2 = var_4;
        break;
    }

    return var_2;
}

_id_7AC5( var_0, var_1, var_2 )
{
    self endon( "death" );
    level endon( "game_ended" );
    _id_076B::_id_7A8B( var_1 );
    var_0 _meth_8232( var_2, ( 0, 0, 10 ) );
}

_id_7AC6( var_0 )
{
    self endon( "death" );
    level endon( "game_ended" );
    self _meth_8373( "explode" + var_0, "active", 0 );
    wait 1;
    self _meth_8373( "explode" + var_0, "neutral", 0 );
}

_id_E6B9( var_0 )
{
    thread _id_7AC4();
}

_id_7AC4()
{
    self endon( "death" );
    self endon( "leaving" );
    self endon( "crashing" );
    level endon( "game_ended" );
    thread _id_7AF0( self._id_935B );
    thread _id_7AF1();
    thread _id_7AE7();
    thread _id_7ADE( self._id_C787 );
}

_id_7AD7( var_0, var_1, var_2, var_3 )
{
    self endon( "death" );
    self endon( "crashing" );
    level endon( "game_ended" );

    for (;;)
    {
        if ( !isdefined( var_2 ) )
            break;

        var_4 = var_2 _meth_8174( 0, 0, 0 );
        var_5 = distance( self._id_02EA, var_4 );

        if ( var_5 < 4000 && var_2._id_5C6A > 0 )
        {
            var_2 _id_099B::_id_B85C( "hover_jet_flares", 1 );
            _id_0A1B::_id_5C64( var_2 );
            var_2 thread _id_0A1B::_id_5C62( "jet_flares", var_3 );
            var_6 = var_2 _id_0A1B::_id_5C56();
            self _meth_8232( var_6 );
            self notify( "missile_pairedWithFlare" );
            return;
        }

        waitframe();
    }
}

_id_7AF0( var_0 )
{
    self endon( "death" );
    self endon( "leaving" );
    self endon( "crashing" );
    level endon( "game_ended" );
    _id_076B::_id_7A8B( var_0 );
    _id_099B::_id_B85C( "timeout_" + self._id_EA0B._id_EA0F, 1 );
    thread _id_7AD9();
}

_id_7AEE()
{
    self endon( "death" );
    level waittill( "game_ended" );
    self._id_C135 = 1;
    self._id_02F2 _id_099B::_id_C13C( self._id_EA0B );
}

_id_7AF1()
{
    self endon( "death" );
    self endon( "leaving" );
    self endon( "crashing" );
    level endon( "game_ended" );
    thread _id_7ADA( "disconnect" );
    thread _id_7ADA( "joined_team" );
}

_id_7ADA( var_0 )
{
    self endon( "death" );
    self endon( "leaving" );
    self endon( "crashing" );
    level endon( "game_ended" );
    self._id_02F2 waittill( var_0 );
    thread _id_7AD9();
}

_id_7AE7()
{
    self endon( "death" );
    self endon( "leaving" );
    self endon( "crashing" );
    level endon( "game_ended" );
    self._id_F81C._id_8D49 = self._id_8D49;
    self _meth_834A( 15, 15 );
    self _meth_8436( 45, 10 );
    thread _id_7AED();
    thread _id_7AC9();
    self _meth_8373( "thrusters", "idle", 0 );
}

_id_7ADE( var_0 )
{
    self endon( "death" );
    self endon( "leaving" );
    self endon( "crashing" );
    level endon( "game_ended" );
    var_1 = [ self, self._id_F81C ];

    for (;;)
    {
        var_2 = self._id_02EA;
        var_3 = var_0 * ( 1, 1, 0 ) + ( 0, 0, self._id_02EA[2] );
        var_4 = _id_077A::_id_E406( var_2, var_3, 256, var_1 );
        var_5 = 0;
        var_6 = var_0[0];
        var_7 = var_0[1];

        if ( isdefined( var_4 ) )
        {
            if ( var_4["hittype"] != "hittype_none" )
            {
                var_6 = var_4["position"][0];
                var_7 = var_4["position"][1];
                var_5 = 1;
            }
        }

        var_8 = _id_7AD3( var_6, var_7, 20 );
        var_9 = ( var_6, var_7, var_8 );
        self _meth_83A3( var_9, 1 );
        self waittill( "near_goal" );

        if ( !istrue( var_5 ) )
        {
            self._id_41A8 = var_9;
            self notify( "hoverJet_moveToNewlocation", var_9 );
            break;
        }
    }

    self _meth_807D();
}

_id_7AD3( var_0, var_1, var_2 )
{
    var_3 = self._id_7ABD;
    var_5 = _id_7AE8( var_0, var_1 );
    var_6 = var_5 + var_3;
    var_6 = var_6 + _func_01B8( var_2 );
    return var_6;
}

_id_7AE8( var_0, var_1 )
{
    self endon( "death" );
    self endon( "acquiringTarget" );
    self endon( "leaving" );
    var_2 = -99999;
    var_3 = self._id_02EA[2];
    var_4 = level._id_1F74;
    var_5 = _id_077A::_id_3EC3( 0, 1, 1, 1, 1, 0, 0, 0, 0 );
    var_6 = _id_077A::_id_E406( ( var_0, var_1, var_3 ), ( var_0, var_1, var_2 ), 512, self, var_5, 1 );

    if ( var_6["position"][2] < var_4 )
        var_7 = var_4;
    else
        var_7 = var_6["position"][2];

    return var_7;
}

_id_7AC9()
{
    self notify( "engageGround" );
    self endon( "engageGround" );
    self endon( "death" );
    self endon( "crashing" );
    self endon( "leaving" );
    level endon( "game_ended" );

    for (;;)
    {
        var_0 = undefined;

        if ( !isdefined( self._id_24A9 ) )
        {
            [self._id_24A9, var_0] = _id_7AD2();
            self notify( "acquiringTarget", self._id_24A9 );

            if ( !isdefined( self._id_24A9 ) )
            {
                _id_076B::_id_7A8B( 0.25 );
                continue;
            }
        }

        var_2 = undefined;

        if ( istrue( var_0 ) )
            var_2 = self._id_24A9 _id_099C::_id_6E1B();

        self._id_F81C _meth_8388( self._id_F81C.groundpos );

        if ( !isdefined( self._id_24A8 ) )
            self setlookat( self._id_24A9 );

        thread _id_7AF3( self._id_24A9 );
        thread _id_7AF2( self._id_24A9, undefined, var_2 );
        thread _id_7AF4( self._id_24A9 );
        _id_7ACF( var_0 );
        _id_076B::_id_7A8B( 1 );
    }
}

_id_7AD2()
{
    self endon( "death" );
    self endon( "leaving" );
    var_0 = _id_0985::_id_36A1( self._id_F81C, 3000, 0, 1 );
    var_1 = undefined;
    var_2 = undefined;
    var_3 = undefined;

    foreach ( var_5 in var_0 )
    {
        if ( !_id_0985::_id_36A6( var_5._id_030F ) )
            continue;

        var_6 = 0;
        var_7 = 0;
        var_8 = abs( _func_025B( var_5._id_030F._id_02EA - self._id_02EA )[1] );
        var_9 = abs( self gettagangles( "tag_flash" )[1] );
        var_8 = abs( var_8 - var_9 );
        var_10 = var_5._id_030F _meth_8194();

        foreach ( var_12 in var_10 )
        {
            var_13 = visionsetnight( var_12 );

            if ( var_13 == "rocketlauncher" )
                var_8 = var_8 - 40;
        }

        if ( istrue( var_5._id_EF0C ) )
        {
            var_7 = 1;
            var_8 = var_8 + 40;
        }

        if ( !isdefined( var_1 ) || var_1 > var_8 )
        {
            var_1 = var_8;
            var_2 = var_5._id_030F;
            var_3 = var_7;
        }
    }

    return [ var_2, var_3 ];
}

_id_7ACF( var_0 )
{
    var_1 = weaponburstcount( "hover_jet_turret_mp" );
    var_2 = 0;
    var_3 = 0;
    var_4 = 100;

    while ( isdefined( self ) && isdefined( self._id_24A9 ) && !isdefined( self._id_87BD ) && !isdefined( self._id_88EE ) )
    {
        if ( self._id_F81C _id_7AE9() )
        {
            var_6 = undefined;

            if ( istrue( var_0 ) )
                var_6 = self._id_24A9._id_02EA;
            else
                var_6 = self._id_24A9 gettagorigin( "j_mainroot" );

            _id_0985::_id_36B4( self._id_F81C, self._id_24A9, var_6, var_4 );

            if ( var_3 == 15 )
                var_4 = 50;
            else if ( var_3 == 30 )
                var_4 = undefined;

            self._id_F81C _meth_83C0( "tag_flash" );
            var_3++;
            self._id_F81C._id_EA0B._id_DA5E++;
        }

        _id_076B::_id_7A8B( var_1 );
    }
}

_id_7AE9()
{
    var_0 = 0.996;
    var_1 = anglestoforward( self gettagangles( "tag_flash" ) );
    var_2 = _func_025A( self.groundpos._id_02EA - self._id_02EA );
    var_3 = _func_0257( var_1, var_2 );

    if ( isdefined( self _meth_817F( 1 ) ) && var_3 >= var_0 )
        return 1;

    return 0;
}

_id_7AC8()
{
    self notify( "engageAir" );
    self endon( "engageAir" );
    self endon( "death" );
    self endon( "leaving" );
    level endon( "game_ended" );

    for (;;)
    {
        if ( !isdefined( self._id_24A8 ) )
        {
            var_0 = [];
            var_0 = _id_077B::_id_1B72( level._id_77BE, level._id_957C, level._id_EB97 );
            self._id_24A8 = _id_7AD1( var_0 );
            self notify( "hoverJet_acquiringAirTarget", self._id_24A8 );

            if ( !isdefined( self._id_24A8 ) )
            {
                _id_076B::_id_7A8B( 0.5 );
                continue;
            }
        }

        thread _id_7AF3( self._id_24A8 );
        _id_7ACE();
        _id_076B::_id_7A8B( 1 );
    }
}

_id_7ACE()
{
    var_0 = "right";
    var_1 = _func_034C( "hover_jet_proj_mp" );
    var_2 = undefined;
    self setlookat( self._id_24A8 );

    while ( isdefined( self ) && isdefined( self._id_24A8 ) )
    {
        var_3 = 5;

        if ( !istrue( var_2 ) )
        {
            _id_099B::_id_B85C( "hover_jet_attack_air" );
            var_2 = 1;
        }

        while ( var_3 > 0 && isdefined( self._id_24A8 ) && !_id_7AC0( self._id_24A8 ) )
        {
            var_3 = var_3 - level._id_5F1B;
            waitframe();
        }

        if ( isdefined( self._id_24A8 ) )
            _id_7ADD( self._id_24A8 );
        else
            break;

        if ( isdefined( self._id_24A8 ) )
        {
            var_5 = self gettagorigin( "tag_" + var_0 + "_archer_missile" ) + anglestoforward( self._id_0054 ) * 100;
            var_6 = var_5 + anglestoforward( self._id_0054 ) * 100;
            var_7 = _id_09A2::_id_0C2D( var_1, var_5, var_6, self._id_02F2 );
            var_8 = _id_7AE5( self._id_24A8 );
            var_7 _meth_8232( self._id_24A8, var_8 );
            var_7._id_EA0B = self._id_EA0B;

            if ( var_0 == "right" )
                var_0 = "left";
            else
                var_0 = "right";
        }
        else
            break;

        _id_076B::_id_7A8B( 2 );
    }

    if ( istrue( self._id_A218 ) )
    {
        thread _id_7ADE( self._id_41A8 );
        self._id_A218 = undefined;
    }
}

_id_7AE5( var_0 )
{
    var_1 = ( 0, 0, 0 );

    if ( isdefined( var_0._id_EA0B ) )
    {
        switch ( var_0._id_EA0B._id_EA0F )
        {
            case "chopper_gunner":
            case "chopper_support":
                var_1 = ( 0, 0, -50 );
                break;
            case "radar_drone_overwatch":
                var_1 = ( 0, 0, -30 );
                break;
            case "hover_jet":
                var_1 = ( 0, 0, 20 );
                break;
            case "scrambler_drone_guard":
                var_1 = ( 0, 0, 10 );
                break;
        }
    }

    return var_1;
}

_id_7AC0( var_0 )
{
    var_1 = 0.866;
    var_2 = anglestoforward( self._id_0054 );
    var_3 = _func_025A( var_0._id_02EA - self._id_02EA );
    var_4 = _func_0257( var_2, var_3 );
    return _id_077B::_id_F07F( var_4 >= var_1, 1, 0 );
}

_id_7ABF( var_0 )
{
    return _id_077B::_id_F07F( distance2dsquared( var_0._id_02EA, self._id_02EA ) < 1000000, 1, 0 );
}

_id_7ADD( var_0 )
{
    while ( isdefined( var_0 ) && _id_7ABF( var_0 ) )
    {
        var_1 = undefined;
        var_2 = anglestoforward( self._id_0054 );
        var_3 = anglestoright( self._id_0054 );
        var_4 = self._id_02EA - var_2 * 1000;
        var_5 = self._id_02EA + 707.0 * ( var_3 - var_2 );
        var_6 = self._id_02EA + 707.0 * ( -1 * var_2 - var_3 );
        var_7 = [ var_4, var_5, var_6 ];
        var_8 = [ self, var_0 ];

        foreach ( var_10 in var_7 )
        {
            if ( _id_077A::_id_E40A( self._id_02EA, var_10, 256, var_8 ) )
                var_1 = var_10 * ( 1, 1, 0 ) + ( 0, 0, var_0._id_02EA[2] );
        }

        if ( isdefined( var_1 ) )
        {
            self._id_A218 = 1;
            self _meth_83A3( var_1, 1 );
        }

        waitframe();
    }
}

_id_7AED()
{
    self endon( "death" );
    self endon( "crashing" );
    self endon( "leaving" );
    level endon( "game_ended" );
    self _meth_8356( 100 );
    self._id_FE8E = _func_0205( "script_model", self._id_02EA );
    self._id_FE8E setmode( "tag_origin" );
    self._id_FE8E _id_0A6F::_id_D5C5( self._id_02F2, &"KILLSTREAKS_HINTS/HOVER_JET_GUARD", 360, 360, 30000, 30000, 2 );
    self._id_FE8E _meth_820B( self );

    while ( isdefined( self._id_FE8E ) )
    {
        self._id_FE8E waittill( "trigger", var_0 );
        _id_099B::_id_B85C( "hover_jet_move" );
        self _meth_8373( "thrusters", "active", 0 );

        if ( isdefined( var_0 ) )
        {
            thread _id_7ADE( var_0._id_02EA );
            thread _id_7AEC();
        }
    }
}

_id_7AEC()
{
    self endon( "death" );
    self endon( "leaving" );
    self waittill( "near_goal" );
    self _meth_8373( "thrusters", "idle", 0 );
    _id_099B::_id_B85C( "hover_jet_guard" );
}

_id_7AE3()
{
    self notify( "random_movement" );
    self endon( "random_movement" );
    self endon( "stopRand" );
    self endon( "death" );
    self endon( "acquiringTarget" );
    self endon( "leaving" );
}

_id_7ADC( var_0 )
{
    var_1 = var_0._id_006E;
    var_2 = var_0._id_A90B;
    var_3 = var_0._id_9CBF;
    var_4 = var_0._id_0134;
    var_5 = var_0._id_7C7C;
    self._id_41A9 = self._id_01FF - var_4;

    if ( self._id_41A9 > 0 )
    {
        if ( self._id_41A9 <= 2000 && self._id_419D == 0 )
        {
            self._id_419D = 1;
            self _meth_8373( "body_damage_light", "on" );
            _id_099B::_id_B85C( "hover_jet_damage_light" );
        }
        else if ( self._id_41A9 <= 1000 && self._id_419D == 1 )
        {
            self._id_419D = 2;
            self _meth_8373( "body_damage_medium", "on" );
            _id_099B::_id_B85C( "hover_jet_damage_med" );
        }
        else if ( self._id_41A9 <= 500 && self._id_419D == 2 )
        {
            self._id_419D = 3;
            self _meth_8373( "body_damage_heavy", "on" );
            _id_099B::_id_B85C( "hover_jet_damage_heavy" );
        }
    }

    return 1;
}

_id_7AD5( var_0 )
{
    self._id_8D60 = var_0._id_A90B;
    return 1;
}

_id_7AD6()
{
    level endon( "game_ended" );
    self endon( "hover_jet_gone" );
    self waittill( "death" );

    if ( !isdefined( self ) )
        return;

    if ( !_id_0A7F::_id_88DC( self._id_8D60 ) )
        _id_7AC3( 75 );

    thread _id_7ACA();
}

_id_7AC3( var_0 )
{
    self endon( "explode" );
    self._id_87BD = 1;
    self._id_8D49 _meth_8415();
    self._id_8D49._id_02EA = self._id_02EA + ( 0, 0, 100 );

    if ( isdefined( self._id_FE8E ) && isdefined( self._id_02F2 ) )
        self._id_FE8E disableoffhandweapons( self._id_02F2 );

    self _meth_807D();
    self notify( "crashing" );
    self _meth_827D( "ks_hoverjet_crash" );
    self _meth_834A( 10, 50 );
    self _meth_8436( var_0, 20, 20 );
    self _meth_8356( 100 );
    var_1 = _id_7ACB( 2500 );

    if ( !isdefined( var_1 ) )
        return;

    _id_099B::_id_B85C( "hover_jet_crash", 1 );
    self _meth_83A3( var_1, 0 );
    thread _id_7AE6( var_0 );
    self waittill( "near_goal" );
    _id_0998::_id_B894();
}

_id_7AE6( var_0 )
{
    self endon( "death" );
    self _meth_83BA( var_0, 50, 50, 0.5 );

    while ( isdefined( self ) )
    {
        self _meth_8389( self._id_0054[1] + var_0 * 0.5 );
        wait 0.5;
    }
}

_id_7ACB( var_0 )
{
    var_1 = self._id_02EA;
    var_2 = 1000;
    var_3 = undefined;
    var_4 = anglestoforward( self._id_0054 );
    var_5 = anglestoright( self._id_0054 );
    var_6 = var_1 + var_4 * var_0 - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 - var_4 * var_0 - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 + var_5 * var_0 - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 - var_5 * var_0 - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 + 0.707 * var_0 * ( var_4 + var_5 ) - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 + 0.707 * var_0 * ( var_4 - var_5 ) - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 + 0.707 * var_0 * ( var_5 - var_4 ) - ( 0, 0, var_2 );
    var_7 = _id_077A::_id_C042( var_1, var_6, self );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    var_6 = var_1 + 0.707 * var_0 * ( -1 * var_4 - var_5 ) - ( 0, 0, var_2 );

    if ( _id_077A::_id_C047( var_1, var_6, self ) )
    {
        var_3 = var_6;
        return var_3;
    }

    return var_3;
}

_id_7ACA()
{
    self notify( "explode" );
    self _meth_8287( self._id_02EA, 1000, 200, 200, self._id_02F2, "MOD_EXPLOSIVE", "hover_jet_turret_mp" );
    self _meth_8373( "explode", "on", 0 );
    wait 0.35;
    thread _id_7AC2( 1 );
}

_id_7AD9()
{
    self endon( "death" );
    self._id_88EE = 1;
    self notify( "leaving" );

    if ( isdefined( self._id_FE8E ) && isdefined( self._id_02F2 ) )
        self._id_FE8E disableoffhandweapons( self._id_02F2 );

    _id_7AC1( undefined, 1 );
    self _meth_834A( 0, 0 );
    self _meth_8436( 35, 25 );
    var_0 = self._id_02EA + anglestoforward( ( 0, _func_01B8( 360 ), 0 ) ) * 500;
    var_0 = var_0 + ( 0, 0, 900 );
    self _meth_83A3( var_0, 1 );
    self _meth_861E( level._id_CC24["hover_jet"]["exit"] );
    self _meth_827D( "ks_hoverjet_leave" );
    self waittill( "goal" );
    _id_076B::_id_7A8B( 1 );
    self _meth_8373( "contrails", "on", 0 );
    var_1 = self._id_02EA + anglestoforward( self._id_0054 ) * 24000;
    self _meth_8436( 250, 75 );
    self _meth_83A3( var_1, 1 );
    self waittill( "goal" );
    self notify( "hover_jet_gone" );
    _id_7AC2();
}

_id_7AC2( var_0 )
{
    if ( isdefined( self._id_F81C ) )
    {
        self._id_F81C _meth_8312( undefined );
        self._id_F81C _meth_809A();
    }

    if ( isdefined( self._id_FE8E ) )
        self._id_FE8E _meth_809A();

    if ( isdefined( self._id_8D49 ) )
        self._id_8D49 _meth_809A();

    if ( isdefined( self._id_F81C.groundpos ) )
        self._id_F81C.groundpos _meth_809A();

    if ( isdefined( self._id_CBC3 ) )
        self._id_CBC3 _meth_809A();

    self _meth_8373( "blinking_lights", "off", 0 );
    self _meth_8373( "thrusters", "off", 0 );
    self._id_EA0B._id_5787 = istrue( var_0 );

    if ( !istrue( self._id_C135 ) )
        self._id_02F2 _id_099B::_id_C13C( self._id_EA0B );

    level._id_7AF5 = _id_077B::_id_1B96( level._id_7AF5, self );
    _id_09BC::_id_0B8F( self );
}

_id_7AF3( var_0 )
{
    var_1 = var_0 getentitynumber();
    self endon( "hoverJet_breakOffTarget " + var_1 );
    self endon( "hoverJet_breakOffAllTargets" );
    self endon( "death" );
    self endon( "leaving" );

    if ( _func_0117( var_0 ) )
        thread _id_7AEF( var_0 );
    else
        thread _id_7AEA( var_0 );

    thread _id_7AEB( var_0, "hoverJet_targetLost " + var_1 );
    thread _id_7AEB( var_0, "hoverJet_targetNotInView " + var_1 );
    thread _id_7AEB( var_0, "hoverJet_moveToNewlocation" );
    thread _id_7AEB( var_0, "hoverJet_targetTimeout" );
}

_id_7AEF( var_0 )
{
    var_1 = var_0 getentitynumber();
    self endon( "hoverJet_breakOffTarget " + var_1 );
    self endon( "hoverJet_breakOffAllTargets" );
    self endon( "death" );
    self endon( "leaving" );
    var_0 waittill( "death_or_disconnect" );
    self notify( "hoverJet_targetLost " + var_1 );
}

_id_7AEA( var_0 )
{
    var_1 = var_0 getentitynumber();
    self endon( "hoverJet_breakOffTarget " + var_1 );
    self endon( "hoverJet_breakOffAllTargets" );
    self endon( "death" );
    self endon( "leaving" );
    var_0 waittill( "death" );
    self notify( "hoverJet_targetLost " + var_1 );
}

_id_7AEB( var_0, var_1 )
{
    var_2 = var_0 getentitynumber();
    self endon( "hoverJet_breakOffTarget " + var_2 );
    self endon( "hoverJet_breakOffAllTargets" );
    self endon( "death" );
    self endon( "leaving" );
    self waittill( var_1 );
    _id_7AC1( var_2 );
}

_id_7AF2( var_0, var_1, var_2 )
{
    var_3 = var_0 getentitynumber();
    self endon( "death" );
    self endon( "leaving" );
    self endon( "hoverJet_breakOffTarget " + var_3 );
    self endon( "hoverJet_breakOffAllTargets" );
    self._id_24A9 endon( "death_or_disconnect" );
    var_4 = undefined;

    if ( !isdefined( var_1 ) )
        var_1 = 500;

    var_5 = _id_077A::_id_3EC3( 0, 1, 0, 1, 0, 1, 0, 1, 1 );
    var_6 = [ self._id_F81C ];

    if ( isdefined( var_2 ) )
    {
        var_6[var_6.size] = var_2;
        var_7 = var_2 _meth_8150();

        if ( isdefined( var_7 ) && var_7.size > 0 )
            var_6 = _id_077B::_id_1B72( var_6, var_7 );
    }

    for (;;)
    {
        var_8 = _id_077A::_id_C047( self._id_F81C gettagorigin( "tag_barrel" ), var_0 gettagorigin( "j_head" ), var_6, var_5 );

        if ( !istrue( var_8 ) )
        {
            if ( !isdefined( var_4 ) )
                var_4 = gettime();

            if ( gettime() - var_4 > var_1 )
            {
                self notify( "hoverJet_targetNotInView " + var_3 );
                return;
            }
        }
        else
            var_4 = undefined;

        wait 0.25;
    }
}

_id_7AF4( var_0 )
{
    var_1 = var_0 getentitynumber();
    self endon( "death" );
    self endon( "leaving" );
    self endon( "hoverJet_breakOffTarget " + var_1 );
    self endon( "hoverJet_breakOffAllTargets" );
    self._id_24A9 endon( "death_or_disconnect" );
    _id_076B::_id_7A8B( 5 );
    self notify( "hoverJet_targetTimeout" );
}

_id_7AC1( var_0, var_1 )
{
    var_2 = undefined;

    if ( !isdefined( var_0 ) || istrue( var_1 ) )
    {
        self._id_24A9 = undefined;
        self._id_24A8 = undefined;
        self _meth_807D();
        self._id_F81C _meth_8085();
        self._id_F81C.groundpos _meth_8415();
        var_2 = "Breaking off all targets";
        self notify( "hoverJet_breakOffAllTargets" );
        return;
    }
    else
    {
        if ( isdefined( self._id_24A9 ) && var_0 == self._id_24A9 getentitynumber() )
        {
            var_2 = "Breaking off ground target: " + self._id_24A9._id_02BA;
            self._id_24A9 = undefined;
            self._id_F81C _meth_8085();
            self._id_F81C.groundpos _meth_8415();
        }
        else if ( isdefined( self._id_24A8 ) && var_0 == self._id_24A8 getentitynumber() )
        {
            var_2 = "Breaking off air target: " + self._id_24A8._id_02AE;
            self._id_24A8 = undefined;
        }
        else
            var_2 = "Breaking off removed target: " + var_0;

        if ( !isdefined( self._id_24A9 ) && !isdefined( self._id_24A8 ) )
            self _meth_807D();
    }

    self notify( "hoverJet_breakOffTarget " + var_0 );
}

_id_7AD1( var_0 )
{
    self endon( "death" );
    self endon( "leaving" );
    var_1 = undefined;
    var_2 = undefined;
    var_3 = 0;

    foreach ( var_5 in var_0 )
    {
        if ( !isdefined( var_5 ) )
            continue;

        if ( !istrue( var_3 ) )
        {
            if ( level._id_EF62 && var_5._id_045B == self._id_045B )
                continue;

            if ( var_5._id_02F2 == self._id_02F2 )
                continue;
        }

        var_7 = distance2dsquared( var_5._id_02EA, self._id_02EA );

        if ( var_7 >= 6250000 )
            continue;

        if ( !isdefined( var_2 ) || var_7 < var_2 )
        {
            var_1 = var_5;
            var_2 = var_7;
        }
    }

    return var_1;
}
